### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by chkpnt** [jankotek/mapdb#1019]
The [documentation](https://jankotek.gitbooks.io/mapdb/) is currently unavailable:

<img width="969" alt="grafik" src="https://github.com/jankotek/mapdb/assets/1956979/de20b5ac-eefc-48e0-92ca-96c781bd80c1">

**Comment by aardes** [comment]
Documents are available:

https://jankotek.gitbooks.io/mapdb/content/

**Comment by chkpnt** [comment]
Okay, thanks. It's apparently back.
