### ISSUE TITLE
eclipse-collections dependencies are not set to specific version and fail

### ISSUE THREAD

**Issue by bratwurzt** [jankotek/mapdb#1024]
Exception:

UnsupportedClassVersionError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

because

<ec.version>[7.0.0,)</ec.version>

selects latest version 12.0.0.M2

Please hardcode the compatible versions and manage them manually.

**Comment by slovdahl** [comment]
I saw the same too, but I think MapDB version 3.0.9 has the version locked down a little bit at least. Compare https://mvnrepository.com/artifact/org.mapdb/mapdb/3.0.8 and https://mvnrepository.com/artifact/org.mapdb/mapdb/3.0.9

![image](https://github.com/jankotek/mapdb/assets/1417619/9e92c689-0654-42e6-a951-ee48b759223a)

vs

![image](https://github.com/jankotek/mapdb/assets/1417619/8c52cf1e-0607-4e90-a6d5-44a23b7b08ac)

Guava should also be locked down to be honest. :shrug:

**Comment by bratwurzt** [comment]
@slovdahl Thank you for this! I'm going to close the ticket, since this is resolved in 3.0.9+

**Comment by bratwurzt** [comment]
It seems like 3.0.9 as compiled with jdk11

**Comment by jankotek** [comment]
What exactly is the issue? 

MapDB should run on any JDK11+, with some workarounds for` sun.misc.Unsafe`. If you need JDK 1.8, use MapDB 3.0.8. 
To manage dependencies (EC, Guava) do version pinning in Maven.

**Comment by bratwurzt** [comment]
> What exactly is the issue?

I've explained quite extensively in the issue description, but I'll try to TL;DR:

mapdb 3.0.8 has no upper limit for eclipse collections version:
<ec.version>[7.0.0,)</ec.version>
which means maven will take the latest available:
12.0.0.M2

which is built with jdk11.

**Comment by 0loky0** [comment]
Hey 

Had the same issue in my build pipeline since few (all build projects fails) 

> To manage dependencies (EC, Guava) do version pinning in Maven.

@jankotek what did you mean ?

Do exclusions and manually add dependency needed ?

**Comment by LeboyX** [comment]
I have also recently run into this issue, to also discover that 3.0.9, which conveniently pins an upper-bound on Eclipse Collections, can't work with Java 8. While I can manually force the 3.0.8 dependency in my own project, that doesn't really feel like a scalable solution. I shouldn't be managing the dependencies of my dependencies. If a single version is known to work with MapDB, shouldn't the MapDB project pin that, itself, so every downstream client doesn't have to do so on its behalf? 

I would argue the unbounded version requirement for Eclipse Collections is, itself, a bug; new releases of Eclipse Collections can quietly break MapDB 3.0.8, forcing its dependents to "figure it out". Can an upper bound, as was clearly done in 3.0.9, be added in a Java 8-compatible way? Why would a version upgrade from 3.0.8 to 3.0.9, a very minor patch, drop support for Java 8 so suddenly?

**Comment by inn0le** [comment]
This fixed the issue with Java 8, Gradle 3.4 and mapdb 3.0.7.

```
configurations.all {
    resolutionStrategy {
        force 'org.eclipse.collections:eclipse-collections-api:12.0.0.M2'
        force 'org.eclipse.collections:eclipse-collections:12.0.0.M2'
        force 'org.eclipse.collections:eclipse-collections-forkjoin:12.0.0.M2'
    }
}
```

**Comment by brearley** [comment]
Not had to pin versions before, after a google and read the gradle docs I got to this:

    implementation("org.eclipse.collections:eclipse-collections") {
        because("Later Versions are built with higher JDK and fail")
        version {
            strictly("12.0.0.M2")
        }
    }
    implementation("org.eclipse.collections:eclipse-collections-api") {
        because("Later Versions are built with higher JDK and fail")
        version {
            strictly("12.0.0.M2")
        }
    }
    implementation("org.eclipse.collections:eclipse-collections-forkjoin") {
        because("Later Versions are built with higher JDK and fail")
        version {
            strictly("12.0.0.M2")
        }
    }

**Comment by jankotek** [comment]
There is new release 3.0.10, it is compiled with JDK 8 and EC are bounded. It should hit Maven Central in couple of hours.

**Comment by LeboyX** [comment]
I can confirm on my project that 3.0.10 resolves the issue as well. I really appreciate the quick turnaround on this. Thank-you.
