### ISSUE TITLE
mapdb now requires Java 11 due to change in org.eclipse.collections

### ISSUE THREAD

**Issue by tlipkis** [jankotek/mapdb#1025]
The most recent release of org.eclipse.collections (12.0.0.M3) was built with Java 11.  Because `ec.version` in the mapdb pom is an open-ended minimum version only, mapdb now (as of 2023/8/28) requires Java 11.  Was that intentional?  Java 8 is still in fairly widespread use.

**Comment by LeboyX** [comment]
TL;DR; Upgrade to 3.0.10. It supports Java 8, bounds the Eclipse Collections version to avoid breaking things. 

This was encountered by a number of people, including myself. You can see the recent, resolved issue here: https://github.com/jankotek/mapdb/issues/1024.

**Comment by tlipkis** [comment]
Excellent, thanks.  Sorry for the duplicate issue.  (I looked, but not for the right string :)
