### ISSUE TITLE
Question on how data is persisted

### ISSUE THREAD

**Issue by siddhsql** [jankotek/mapdb#1027]
Hello,

I came across this library recently. I have some questions:

1. First, if I create a fileDB, do I need to close it (by calling `close` method) to save the data?
2. Second, does it do a complete overwrite of everything to disk every time `close` is called? E.g., I create a hashmap of 1 billion elements and I call `close`. Then I add 1 more element and call `close`. What happens?

**Comment by jankotek** [comment]
You need to call close(), else files may get corrupted. Content of files is persisted after you close file. So you will have billion plus one entries.
