### ISSUE TITLE
Transaction Isolation

### ISSUE THREAD

**Issue by siddhsql** [jankotek/mapdb#1031]
AFAICT there is no transaction isolation with this db (version 3.0.10 is currently the latest).
https://jankotek.gitbooks.io/mapdb/content/db/
>One DB object represents single transaction. The example above uses single global transaction per store, which is sufficient for some usages

is that correct?

**Comment by jankotek** [comment]
That is outdated, transaction isolation was in 1.0. New version do not have Tx isolation.
