### ISSUE TITLE
Primitive arrays as key/vals

### ISSUE THREAD

**Issue by jankotek** [jankotek/MapDB#190]
`String` is wrapper for `byte[]` or `char[]`. However using primitive arrays directly has performance advantages. MapDB should be able to use these as keys and values in collections. 

This includes:
 - serializers
 - key serializer for BTreeMap
 - comparators  for BTreeMap
 - hashers for HTreeMap

**Comment by yoocos** [comment]
What is the status of this issue? Is it possible to use arrays as key ?
And if so, how are the arrays ordered in a BTree?

**Comment by yoocos** [comment]
I am looking at the code and I was wondering if I understand it correctly. Currently, you don't do delta-packed serialization for String correct ? ( I wanted to take it as an example to try to do delta-packed key for int[])

**Comment by jankotek** [comment]
Delta packing is done for numbers. 
Strings should be packed  with 
common prefix

**Comment by yoocos** [comment]
Sorry for the question, but does it mean that String isn't packed with common prefix yet or is it?

**Comment by jankotek** [comment]
Strings and also byte[] keys 
already have common 
prefix compression.

**Comment by jankotek** [comment]
This is now fixed. Primitive arrays are first class citizens in MapDB 2.0
