### ISSUE TITLE
Adding entries and lookup become slower as input data files grow in size

### ISSUE THREAD

**Issue by wcarus** [jankotek/mapdb#240]
Open TreeSet using any combination (or none) of transactionEnable and compressionEnable. Master input file contains approx. 725K key-value entries. Randomly sampled 1, 5, 10, 15, 16, 17, 18, 19, and 20% of entries of master file. Performance storing and looking up entries increases roughly linearly until about 19% of master file (approx. 138K entries). Lookup then slows down dramatically (it is about 30% of time to store for smaller sized input files; and then becomes almost 200% of time to store at around 19K entries).

**Comment by jankotek** [comment]
Write amplification should be greatly reduced in 2.0
