### ISSUE TITLE
how to configure memory limit

### ISSUE THREAD

**Issue by os72** [jankotek/mapdb#276]
(1) If I set a DB memory limit and the consumption goes beyond it throws exception:

Exception in thread "main" java.io.IOError: java.io.IOException: no free space to expand Volume

(2) If I set a limit on number of records in HTreeMap it manages that (applies evictions) and continues to operate

Is there a way to get behavior (2) with DB memory limit? (Evict, don't throw exception)

Thanks!

```
    DB db = DBMaker.newDirectMemoryDB()
            .transactionDisable()
            .syncOnCommitDisable()
            //.asyncWriteEnable()
            .closeOnJvmShutdown()
            .sizeLimit(1) // in GB
            //.cacheSize(1000)
            //.cacheLRUEnable()
            .make();

    HTreeMap<Integer,String> map = db.createHashMap("foo1")
            .expireMaxSize(100000)
            .make();
```

**Comment by ieiayaobb** [comment]
Is the any detail demo for setting a memory limit? 
DBMaker.newCache(sizeInGB) will return a HTreeMap, so how can I set the summary size of all my collections with a limitation?

**Comment by jankotek** [comment]
@ieiayaobb Not really. 1.0 is bit more complicated, 2.0 is not implemented reliably yet.
