### ISSUE TITLE
Android default constructor workaround broken from 4.2 onwards

### ISSUE THREAD

**Issue by nadavwr** [jankotek/mapdb#295]
See Objenesis [issue 23](https://code.google.com/p/objenesis/issues/detail?id=23): Davlik support broken for Android 4.2

> The signature of ObjectStreamClass methods have changed in Android 4.2.  newInstance now takes a long instead of an int as the 2nd argument, and returns a long instead of an int from getConstructorId.  The VENDOR_VERSION used to identify the newer VM is 1.6.0.

This impacts code in [SerializerPojo.java:525](https://github.com/jankotek/MapDB/blob/970b748e50b939d1bede6ee9c670cf2896911bb8/src/main/java/org/mapdb/SerializerPojo.java#L525-L527), referenced here from latest commit at this time.

Perhaps another 'androidConstructorJelly' can be added, in line with 'androidConstructorGinger'.

**Comment by jankotek** [comment]
Fixed in 2.0 branch
