### ISSUE TITLE
preallocate memory option

### ISSUE THREAD

**Issue by os72** [jankotek/mapdb#299]
mapdb seems to allocate memory on demand - it may be useful to have an option to  preallocate all (or some) of the given size

For example, puts run faster the second time around - off-heap test with 1M records, 32 byte key, 512 byte value gives:

puts 1: 15.294 sec: 65,385.118 ops/sec, 33.922 MB/sec
puts 2: 9.296 sec: 107,573.15 ops/sec, 55.809 MB/sec

```
DBMaker.newDirectMemoryDB()
.sizeLimit(sizeLimit)
.transactionDisable()
.syncOnCommitDisable()
.make();
```

**Comment by jankotek** [comment]
Allocation in 2.0 is rewritten. There is new option `DBMaker.allocateStartSize(size)` and `DBMaker.allocateIncrement(size)`
