### ISSUE TITLE
infinit loop when HashMap iteration

### ISSUE THREAD

**Issue by OBOne** [jankotek/mapdb#306]
Hi,
Just to inform you about a bug.
When i use mapdb and want to iterate over key values, i fell in an infinit loop.
My "for each" statement return me the same object key again and again (same system id).
I profile it and and i see all the time is consume by next, moveToNext and advance at line 972 of file HTreeMap. The advance method return always new list again and again.
After that, i must delete my mapDB file if i want to run correctly my program.
I hope you find it and try to reproduct it.

Sincerly,

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ?

**Comment by jankotek** [comment]
No update, MapDB 2 has a few improved check. Dont have time to look at 1.0

**Comment by jankotek** [comment]
Not going to fix this issue, MapDB 2.0 has assertions to prevent this.
