### ISSUE TITLE
Segmented Engine Wrapper for better concurrent scalability

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#310]
`java.util.ConcurrentHashMap` and `HTreeMap` use  simple trick to get concurrent scalability. They split hash into segments, each handled under a different lock. 

MapDB Store should handle concurrent writes well, but in practice it does not scale linearly. So we could use the same segment trick. `HTreeMap` has 16 segments, each of them could have its own store.

**Comment by bwzhang2011** [comment]
@jankotek, how about such going ?

**Comment by jankotek** [comment]
Already done in 2.0 and 3.0
