### ISSUE TITLE
Delete old files on opening, if they are corrupted

### ISSUE THREAD

**Issue by chrisdwalton** [jankotek/mapdb#316]
This is a feature request rather than a bug.    

Since there is no way to recover from a corrupt database file, it would be nice to have a .deleteCorruptFile() option when attempting to open a database.   If the database file is not corrupt then the database is opened, otherwise the database file is deleted and a fresh database file is opened.

Chris

**Comment by jankotek** [comment]
Moved to TODO list, closing.
