### ISSUE TITLE
Improve Weak/Soft cache

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#317]
There is memory leak in Weak/Soft cache during high load. GC thread didn't get enough time to process all items in ReferenceQueue.
My suggested solution:
1) Add 'clean' to CacheItem. For Soft/Weak cache will release referent. It will be called after remove and put in concurrent map. So only Reference instances will be added to reference queue.
2) Purge reference queue after some count of modification in concurrent map (10% of cache size)

 Thank you
    Martin

**Comment by jankotek** [comment]
Weak/Soft cache was rewritten in 2.0. Now it uses something similar to `expungeStaleEntries` without background thread. It can also use multiple background threads.
