### ISSUE TITLE
Allow controlling the classloader for the SerializerPojo

### ISSUE THREAD

**Issue by stephenc** [jankotek/mapdb#328]
At present, SerializerPojo uses the current Thread's context classloader. While this is a reasonable default, it should be possible to control the classloader that will be used when creating the DB or (better yet) when makeOrGet the stores. Something like

    db = DBMaker.newFileDB(...)
        .setClassLoader(myClassLoader)
        .make();

or

    db = createHashMap("name").setClassLoader(myClassLoader).makeOrGet();

The latter form is probably a larger scoped change. The reason for wanting it though is to allow a singleton `DB` instance to be used across multiple classloaders.

As an example of where this issue arrises. If you are using MapDB as a data store within a Jenkins plugin, each Jenkins plugin gets its own classloader, so currently you need to wrap your use of the MapDB maps within 

            ClassLoader old = Thread.currentThread().getContextClassLoader();
            try {
               Thread.currentThread().setContextClassLoader(Jenkins.getInstance().getPluginManager().uberClassLoader);
                // call MapDB here
            } finally {
                Thread.currentThread().setContextClassLoader(old);
            }

In order to ensure that it resolves the classes correctly. I think this hoop jumping is only required up to the call to `makeOrGet` but it is hard to be certain.

**Comment by maggu2810** [comment]
Are there any progress, news, ...?

**Comment by jankotek** [comment]
@maggu2810 1.1 become 2.0. I still plan to include this, but no progress on code.

**Comment by jankotek** [comment]
Already solved, see https://github.com/jankotek/mapdb/issues/555
