### ISSUE TITLE
Perf - proposal: Value serializer for value array

### ISSUE THREAD

**Issue by jandam** [jankotek/MapDB#340]
I suggest to introduce extended value serialization interface that will support storing array of values. Something like BTreeKeySerializer.
- custom serialization for value array (decreased usage of disk space) - main improvement
- can improve performance in some cases

Proposed interface is not intended as final version.

```java
public abstract class BTreeValueSerializer<A> extends Serializer<A> {
    public abstract void serialize(DataOutput out, Object[] values, int size) throws IOException;
    public abstract Object[] deserialize(DataInput in, int size) throws IOException;
}
```
Current BTreeMap:391
```java
                    for(Object val:value.vals()){
                        assert(val!=null);
                        if(valsOutsideNodes){
                            long recid = ((ValRef)val).recid;
                            DataOutput2.packLong(out, recid);
                        }else{
                            valueSerializer.serialize(out,  val);
                        }
                    }
```
Proposed code in BTreeMap
valueSerializer.serialize(out, value.vals(), value.vals().length)

**Comment by jankotek** [comment]
Closing, already present in 2.0 branch.
