### ISSUE TITLE
Requirement for Serializer to be Serializable is burdensome

### ISSUE THREAD

**Issue by samskivert** [jankotek/MapDB#345]
I am unable to use a custom serializer because of the requirement that serializers themselves be serialized and stored in the database catalog. My serializers must contain references to runtime data structures that cannot themselves be serialized.

This seems like an unfortunate architectural choice. My code, and I'm sure the vast majority of code out there that uses MapDB, looks like:

```java
db.createTreeMap("name").valueSerializer(valSz).makeOrGet();
```

which is to say, the value serializer is specified *every* time I open the database, the first time (when it is created) and all subsequent times. There's no need for the serializer to be serialized and stored into the database catalog, I always pass it in.

It looks like I can hack my way around the limitation by manually creating HTreeMap etc. and duplicating all of the initialization code except the part that loads the serializers from the catalog, so thankfully I'm not forced to abandon this otherwise great tool!

**Comment by Groostav** [comment]
>jankotek added `2.0` and removed `1.1` labels

:sob: 

I really don't like this requirement also.

On our codebase we use guava's event-bus for most of our model events. This means that a couple serialized models have an event-bus on them. The handy trick I just implemented was to have the derserializer ask guice to inject any field it finds that are `@Inject private transient Whatever`

But of course the whole concept of IOC is antithetical to serialization, meaning I now have to do the leg work of making sure that when a serializer for mapdb is loaded, it will _somehow_ find the appropriate environment and get a copy of the appropriate injector. This isn't difficult for me to do now, but its wierd and burdensome code (if you were to add a second Event Bus to our project, you would likely blow-up serialization. No fun). 

Why does this requirement even exist? Was it put in place as some sort of version protection scheme? When would you not be able to get an instance of the Serializer through more conventional means (ie, through your builder objects)?

Please bump this back to 1.1

**Comment by jankotek** [comment]
There is not going to be 1.1. MapDB 2.0 
already had first alpha release and is 
going to be in beta in couple of weeks.

**Comment by Groostav** [comment]
@jankotek can you get this into one of your upcoming alpha releases?

In the name of nice progress bars -> deep integration with serializers -> unserializable objects in XStream 'converters' -> unserializable serializers. I really need this if we're going to continue using MapDB.

**Comment by Groostav** [comment]
I could fork & PR this myself if need be, it honestly doesn't look so hard to implement.

**Comment by Groostav** [comment]
Thanks so much for this @jankotek!

I cloned and built a snapshot and pushed it into my branch, everything seems to be OK. needless to say I'm anxious for a release that starts with a `2` and doesn't have the phrase `alpha` or `SNAPSHOT` in it.
