### ISSUE TITLE
BTreeMap and outside node value crash after delete

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#354]
Have a BTreeMap with values stored outside of nodes. If an iterator contains deserialized node with reference to an value and it gets deleted: The iterator will try to fetch non-existing recid from store and will fail with an IOError.

The outside values must be replaced with thumbstone marker for off-line deletion. Not deleted.

**Comment by jankotek** [comment]
I now understand where is the problem. There is a race condition between external value removal and removal from BTreeMap. It means that BTreeMap.get() must be write locked if external values are enabled.

**Comment by datumbox** [comment]
Could this also be related to the [issue-664](https://github.com/jankotek/mapdb/issues/664)?
