### ISSUE TITLE
Problem with tests. Maven doesn't compile

### ISSUE THREAD

**Issue by leznikm8** [jankotek/mapdb#362]
Failed tests: 
  BrokenDBTest.canDeleteDBOnBrokenLog:92 Can't delete index
Tests in error: 
  StoreWALTest.discard_corrupted_log:109 » IO java.io.IOException: The requested...
Tests run: 1750, Failures: 1, Errors: 1, Skipped: 4

**Comment by jankotek** [comment]
Fixed in both branches

**Comment by leznikm8** [comment]
Thanks!!!
