### ISSUE TITLE
IndexOutOfBoundsException when inserting data

### ISSUE THREAD

**Issue by TeofilisMartisius** [jankotek/MapDB#364]
Hi,

I tried writing to a MapDb, and I get this exception. It's random, but always happens, I haven't seen this go through 1m records successfully on my machine. I think this is fairly critical, as this is a crash on basic-use, and this error makes MapDB unusable for me.

It's a simple use-case, and should work. I think it's worth adding something like this to your test suite as a sanity check.

I run this testcase on Debian Linux 64 bit inside a VMWare VM on Windows-7 64 bit, multi-core CPU. Kernel version 3.2.0-4-amd64, Debian 7.6, filesystem on /tmp is ext4.

It crashes using 64bit Java 1.8.0_11 fairly quickly,after ~300k rows
It crashes using 64bit Java 1.6.0_32, but gets further, ~700k rows
It crashes using 64bit Java 1.7.0_51-b13, but gets to ~850k rows

Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putLong(DirectByteBuffer.java:802)
	at org.mapdb.Volume$ByteBufferVol.putLong(Volume.java:304)
	at org.mapdb.StoreWAL.walIndexVal(StoreWAL.java:310)
	at org.mapdb.StoreWAL.preallocate(StoreWAL.java:173)
	at org.mapdb.EngineWrapper.preallocate(EngineWrapper.java:43)
	at org.mapdb.AsyncWriteEngine.put(AsyncWriteEngine.java:301)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.EngineWrapper.put(EngineWrapper.java:53)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:581)
	at org.mapdb.HTreeMap.put(HTreeMap.java:480)
	at noid.CrashMapDb.main(CrashMapDb.java:24)

Test case to reproduce this:

package test;

import java.io.File;
import java.util.Map;
import java.util.UUID;
import org.mapdb.DB;
import org.mapdb.DBMaker;

public class CrashMapDb {
    public static void main(String arg[]) throws Exception {
        DB db = DBMaker.newFileDB(new File("/tmp/mapdb.db")).
            asyncWriteEnable().closeOnJvmShutdown().mmapFileEnable().make();
        Map<String, String> map = db.getHashMap("test");
        Runtime run = Runtime.getRuntime();
        String value = null;
        for (int i = 0; i < 1000000; i++) {
            String key = UUID.randomUUID().toString();
            if (value == null || i % 2 == 0) {
                value = UUID.randomUUID().toString();
            }
            map.put(key, value);
            if (i % 50000 == 0) {
                double free = run.freeMemory() / 1024.0 / 1024.0;
                double total = run.totalMemory() / 1024.0 / 1024.0;
                System.out.format("read %10d free = %10.2f total=%10.2f %n", i, free, total);
                db.commit();
            }
        }
        db.commit();
        db.close();
    }
}

**Comment by freakolowsky** [comment]
any progress on this issue ... at least a workaround (if possible other than "turn async off")

**Comment by gdaniel** [comment]
Hi,
It seems that the bugfix in the release 1.0.7 was not enough:
I still have an IndexOutOfBoundException that appears randomly when I add values.

     [java] java.lang.IndexOutOfBoundsException
     [java] java.lang.IndexOutOfBoundsException
     [java] 	at java.nio.Buffer.checkIndex(Buffer.java:538)
     [java] 	at java.nio.DirectByteBuffer.putLong(DirectByteBuffer.java:796)
     [java] 	at org.mapdb.Volume$ByteBufferVol.putLong(Volume.java:304)
     [java] 	at org.mapdb.StoreWAL.walIndexVal(StoreWAL.java:310)
     [java] 	at org.mapdb.StoreWAL.preallocate(StoreWAL.java:173)
     [java] 	at org.mapdb.EngineWrapper.preallocate(EngineWrapper.java:43)
     [java] 	at org.mapdb.AsyncWriteEngine.put(AsyncWriteEngine.java:301)
     [java] 	at org.mapdb.EngineWrapper.put(EngineWrapper.java:53)
     [java] 	at org.mapdb.Caches$LRU.put(Caches.java:61)
     [java] 	at org.mapdb.HTreeMap.putInner(HTreeMap.java:581)
     [java] 	at org.mapdb.HTreeMap.put(HTreeMap.java:480)

If I remove mmapFileEnableIfSupported then the DB is correctly saved.
