### ISSUE TITLE
java.sql.Timestamp not serialized/deserialized correctly

### ISSUE THREAD

**Issue by suxonoff** [jankotek/MapDB#365]
There is special support for java.util.Date here - https://github.com/jankotek/MapDB/blob/31ed3b47dcafeaa289f60ab20090ef68c441c1b3/src/main/java/org/mapdb/SerializerBase.java#L215

But if you put any child of java.util.Date then you wil get strange results on deserialization:

e.g. if you put Timestamp.valueOf("2014-08-04 08:20:56.607001") then you will get back 1970-01-01 03:00:00.607001 (nanos are OK, but fastTime is transient and not handled separately)

**Comment by jankotek** [comment]
Already fixed in previous versions
