### ISSUE TITLE
SerializerPojo throws NotSerializableException for Class field

### ISSUE THREAD

**Issue by bouchov** [jankotek/MapDB#373]
I was trying to integrate MapDB in one old project to improve performance and found problem with fields serialization of type java.lang.Class if this class is not serializable.
This is a test case https://github.com/bouchov/mapdb/blob/master/java/org/mapdb/SerializerPojoTest2.java  - test_Pojo fails.
I've also made a workaround https://github.com/bouchov/mapdb/blob/master/SerializerPojo.patch

**Comment by jankotek** [comment]
Fixed in both branches
