### ISSUE TITLE
Constantly growing DB file with custom serializers

### ISSUE THREAD

**Issue by jfiedler** [jankotek/MapDB#376]
I observed constant growing MapDB size when using a file backed queue with custom serializers. The same queue works fine when just putting strings but seems to grow constantly if persisting the same strings via a custom serializer. I created a standalone Junit test case demonstrating the problem.

Test Case: https://gist.github.com/jfiedler/4c2a34e0d752dd93f22a
Group Discussion: https://groups.google.com/d/msg/mapdb/03m2LX7tEpg/13SL7GW9bx8J

**Comment by jankotek** [comment]
Investigated. 'It is a feature'. Free space tables cause some overhead. Small items in queues are almost worst case scenario.
