### ISSUE TITLE
Excessive memory allocation if asyncWriteEnable()

### ISSUE THREAD

**Issue by chemist777** [jankotek/mapdb#392]
If i specify `asyncWriteEnable()` for DB creation, then JVM memory usage starts grow at high rate.
This results in agressive GC pressure.
Cause of this: infinite loop in `AsyncWriteEngine` in which `writeCache.longMapIterator()` called and `new MapIterator()` object created every some ms.

**Comment by bwzhang2011** [comment]
@jankotek, any update for such issue.

**Comment by jankotek** [comment]
I could not replicate issue. The async writer eats CPU and memory, but its within limitations of 1.0 design. Most of this issue is fixed in 2.0.
