### ISSUE TITLE
Reading from heapstore or filedb with hardrefcacheenabled is way slower than simple ConcurrentHashMap

### ISSUE THREAD

**Issue by mousom** [jankotek/MapDB#406]
Our use-case is something where we have more than enough RAM to hold all entries but we want them to be persisted on disk.
I tried two different configurations for load testing
```
 File dbFile = File.createTempFile("testmapdb", "testspeed");
    DB db = DBMaker.newFileDB(dbFile)
        .cacheSize(256 * 1024)
        .cacheHardRefEnable()
        .make();
    Map<Long, QualitySignals> cache =
        db.createHashMap("testSpeed")
            .keySerializer(Serializer.LONG)
            .valueSerializer(QS_SERIALIZER)
            .make();
```

This was 6-7 times slower than simple ConcurrentHashMap for reading 1M items
Then I used following one just to see if the in-memory cache used by mapdb is causing the slowness
```
  DB db = DBMaker
        .newHeapDB()
        .cacheSize(256 * 1024)
        .make();
    Map<Long, QualitySignals> cache = db
        .createHashMap("cache")
        .make();
```
And it turned out no better. I was expecting it to be closer to HashMap or ConcurrentHashMap.

We have just started evaluating mapdb so please let me know if my configurations or expectations are wrong and this is expected or you need more information.

Appreciate it.

**Comment by jankotek** [comment]
Outdated, closing
