### ISSUE TITLE
Extremely large file and slow loading

### ISSUE THREAD

**Issue by matzschmanski** [jankotek/MapDB#408]
Hey,
on startup i load a lot of xml files and store some information in maps.
I have tried using the `0.9.7` Version and was verry happy with it but when i switched to `1.0.6` i got problems regarding the performance.

I use this for creation:
`DBMaker.newFileDB("D:/misc/db/map.db").closeOnJvmShutdown().make();`
For the information of aproximately 3000 loaded xml files (the information i need not the files) the mapDB file needs 30mb of storage (on `0.9.7` )

I have stopped the startup when the mapDB file consumed more than 1GB of disk space and only about 10% of the total xml files had been loaded.

I have tried out all Version newer than `0.9.7`, they all seem to behave the same in this matter.

Is there something wrong / changed so much that it is no longer usable for my use case?

Kind Regards

**Comment by jankotek** [comment]
Closing, its on my todo list for MapDB 2.0
