### ISSUE TITLE
RFE: push method for buidling maps

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#415]
Please add push method for filling maps. Pump is pull method. Pump pulls data from iterator. Push method can be implemented with Builder pattern.
Pseudocode to demonstrate the idea. Not API suggestion.
MapDBBuilder builder = new MapDBBuilder(<destMap>, <comparator>, <presort>, ...);
...
  builder.put(<key>, <value>);
  builder.put(<key>, <value>);
...
  builder.build();

**Comment by jankotek** [comment]
Can be done easily with queue and background thread.

**Comment by jandam** [comment]
Yes, queue and background thread it was my first try. But there was huge overhead in standard Java queue. I don't want to use another library with better implementation.
  Second try was 'batched' queue. Queued item was array of records. It was better but still complicated due to synchronization/interrupts/exceptions... 
  Third and current solution is to store all data to files in same way as sort during Pump phase. And then I use standard Pump without sorting. Disadvantage is that sorted data are written and then read (in total 2x serialized and 1x deserialized). But both actions are linear without disk seeks.

**Comment by jankotek** [comment]
Done in 3.0
