### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null BTreeMap.java:2841

### ISSUE THREAD

**Issue by cep21** [jankotek/mapdb#420]
Hi,

We're using mapdb-1.0.6.  It's a recent database that was created with this release.  I'm unable to reproduce in a small use case, but are seeing this exception in production.  Unsure how to debug this error.

DB created as
```java
        return DBMaker.newFileDB(actualFileToOpen)
                .cacheSize(maxDatapointSize.get())
                .closeOnJvmShutdown()
                .checksumEnable()
                .mmapFileEnableIfSupported()
                .cacheLRUEnable()
                .cacheSoftRefEnable()
                .make();
```

We have a separate thread running in a sleep loop:
```java
db.commit();
```

We see the following exception in our logs.  Does this mean the DB is corrupted?  Is there a way to recover, or another way to resolve this issue?
```
2014-12-05T07:12:36.235Z ERROR [tsworker-1] [s.d.t.TsCreator  ] {}: Failed to create time series
java.lang.ArrayIndexOutOfBoundsException: null
        at org.mapdb.BTreeMap.arrayPut(BTreeMap.java:2841) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.BTreeMap.put2(BTreeMap.java:743) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.BTreeMap.put(BTreeMap.java:643) ~[mapdb-1.0.6.jar:na]
......
```

**Comment by jankotek** [comment]
Possibly data corruption, but most likely race condition in BTreeMap.

**Comment by easel** [comment]
I'm seeing this same issue. I'm shipping the files back and forth to S3 a lot, so the chance of data corruption is pretty high. I may also not be properly "freezing" the files prior to copying them. Any pointers how to chase this down?

**Comment by jankotek** [comment]
Make sure that store is closed correctly if transactions are disabled.

**Comment by jankotek** [comment]
Not enough information to reproduce
