### ISSUE TITLE
integration of javaagent with jvm

### ISSUE THREAD

**Issue by vikasvats** [jankotek/MapDB#426]
I am using hazelcast in my web project . I have added following dependencies in my pom.xml.

 <dependencies>
        <dependency>
            <groupId>org.mapdb</groupId>
            <artifactId>mapdb-hz-offheap</artifactId>
            <version>0.8</version>
        </dependency>
    </dependencies>

after it i am struck on second step(integration of jvm with javaagent).
Can you tell the steps of integration of javaagent jar with jvm.?

**Comment by jankotek** [comment]
It is documented on project readme on github.
