### ISSUE TITLE
Thread named HTreeMap expirator Use a lot of CPU

### ISSUE THREAD

**Issue by davy-zhang** [jankotek/mapdb#427]
When I use this code to create a HTreeMap instance.
HTreeMap<Object, Object> cache=DBMaker.newMemoryDirectDB().transactionDisable().cacheLRUEnable().make().createHashMap("testCache").expireMaxSize(10000).makeOrGet();

It creates a thread named HTreeMap expirator, But When the map size is 10015,the thread has been running use a lot of CPU and not sleep.

The following code if there is a problem ?
In ExpireRunnable Class
Method:expirePurge
code:removePerSegment=1+(size-expireMaxSize)/16;
Method:expirePurgeSegment
code:final boolean remove = ++counter < removePerSegment || ((expire!=0 || expireAccess!=0) &&  n.time+expireTimeStart<System.currentTimeMillis());

When map size is 10015 ,the removePerSegment greater than 0 and the remove are all false.

**Comment by jankotek** [comment]
I will have a look at that. 

But all expiration sizes and times are approximate. 
10015 entries does not necessary mean the 
expiration will kick in. Map size 11000 would 
definitely mean bug.

**Comment by davy-zhang** [comment]
Thank you very much for your reply.

The main problem is not the map's size larger than my set, but when the map's size is greater than the set value and determine whether to remove non-stop without the problem of high cpu usage due to really delete. Note that the main problem is that the thread will occupy 100% of the cpu, when I have multiple instances of the map, the entire machine cpu are full.

**Comment by dlg99** [comment]
When running the test code posted along with Issue 425 https://github.com/jankotek/MapDB/issues/425 I see that cache size routinely growing over configured 10,000, up to 15,000/20,000 (then drops and goes up) before it crashes with OOM.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ? we have some similar use cases.

**Comment by jankotek** [comment]
No update

**Comment by jankotek** [comment]
Should be solved in 2.0 branch
