### ISSUE TITLE
createTreeMap and ClassCastException

### ISSUE THREAD

**Issue by javalama** [jankotek/MapDB#429]
To avoid ClassCastException from byte[] to Comparator, I set the proper comparator.

```
ConcurrentNavigableMap<byte[],byte[]> mymap = 
       db.createTreeMap("mymap").comparator(Fun.BYTE_ARRAY_COMPARATOR).makeOrGet();
```

This works, I can put and get byte[] keys just fine.

However, the next time I run the program, the ClassCastException happens anyway. The exception happens on the code line above.

Anything else I need to do?

**Comment by jankotek** [comment]
This part was rewritten. Now specifying correct serializer is fine:
```
db.createTreeMap("mymap")
.keySerializer(Serializer.BYTE_ARRAY)
.valueSerializer(Serializer.BYTE_ARRAY)
.make()
```
