### ISSUE TITLE
Collection methods not implemented

### ISSUE THREAD

**Issue by pardom** [jankotek/MapDB#431]
Many of the interface methods for various collections are not implemented, but instead throw an `UnsupportedOperationException`.

For example, I should expect to be able to do this if a class implements `Collection`.

```java
Queue<String> queue = db.getQueue("myQueue");
List<String> list = new ArrayList<>(queue);
```

However, this throws an `UnsupportedOperationException` because the ArrayList constructor calls `toArray()` on `queue`. I haven't seen any mention of this limitation or reasons for it, but by implementing these interfaces I feel there is a reasonable expectation that they will work.

Can we expect implementation of these inherited methods in the future?

**Comment by jankotek** [comment]
Problem here is lock-free nature of queues. It is not possible to get content of queue without modifing it.

**Comment by jankotek** [comment]
Closing. Current queues are deprecated and will be eventually replaced by full implementation
