### ISSUE TITLE
newMemoryDirectDB  - direct memory manager

### ISSUE THREAD

**Issue by kobikis** [jankotek/MapDB#433]
I've been  using MapDb with GigaSpaces XAP using newMemoryDirectDB, In the heap we are storing our indices and using MapDB for storing the data(serialized).
Now I'm running load tests and occasionally I'm getting OOM, is there a way to monitor the MapDB direct memory size?

I think a direct memory manager which monitor and alert canbe very useful and prevent OOM.

Thanks.

**Comment by bwzhang2011** [comment]
+1

**Comment by jankotek** [comment]
`Store` class has some stats such as space usage etc. But it is broken right now in 2.0 branch. I will add necessary hooks and document them.

For 1.0 use somethink like this:

```
Store store = Store.forDB(db);
System.out.printf("store size: %,d, store free size: %,d\n",
                       store.getCurrSize(),  store.getFreeSize());
```

**Comment by jankotek** [comment]
MapDB 2 now has statistics: https://github.com/jankotek/MapDB/issues/478. 

I also believe currSize and freeSize methods from previous example are working.
