### ISSUE TITLE
RFE: BTreeMap allow counter be implemented by j.u.c.AtomicLong

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#439]
There is optimization for sizeLong by using Atomic.Long to skip iteration. For temporary tables there can be counter implemented by j.u.c.AtomicLong to minimize overhead. Every CAS on counter writes record to disk. For temporary tables that will be deleted after close. It be only in memory.

**Comment by jandam** [comment]
I suggest deffer this issue to next version. There is simple workaround with self implementing Bind.size on AtomicLong.

**Comment by jankotek** [comment]
Not going to fix this.
