### ISSUE TITLE
In-memory compaction does not delete temp files

### ISSUE THREAD

**Issue by jankotek** [jankotek/MapDB#443]

**Comment by jankotek** [comment]
Another one for the compaction file ,current name file is generated from mapdb + random long + compact ,I think that  table name + random long + compact will be safer.

**Comment by niclash** [comment]
Generating random temporary filename is available from java.io.File

On Mon, Feb 9, 2015 at 7:41 PM, Jan Kotek <notifications@github.com> wrote:

> Another one for the compaction file ,current name file is generated from
> mapdb + random long + compact ,I think that table name + random long +
> compact will be safer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jankotek/MapDB/issues/443#issuecomment-73495660>.
>



-- 
Niclas Hedhman, Software Developer
http://www.qi4j.org - New Energy for Java
