### ISSUE TITLE
Feature Request: Redis like persistance

### ISSUE THREAD

**Issue by samhendley** [jankotek/MapDB#448]
I may have asked this indirectly before but I thought I would reask in a more concrete fashion.

Is there any current (or planned) configuration that allows creating a database that redis like persistence guarantees. Basically I want to have an in-memory map that is flushed to disk "often". In my case I am willing to tolerate the loss of a few seconds of recent data if it means the database can never be corrupted. The closest configuration I could get is using async writes but if my system is shutdown uncleanly the database is toast.

Any thoughts?

**Comment by jankotek** [comment]
There is already mapdb-redis project in half finished state. I will release it once stable 2.0 is out
https://github.com/jankotek/mapdb-redis

**Comment by samhendley** [comment]
I didn't mean I wanted an implementation of the redis API, I was talking really only talking about the "write behind" behavior of redis.

**Comment by jankotek** [comment]
Its on todo list.
