### ISSUE TITLE
Empty histograms not filled on bind

### ISSUE THREAD

**Issue by mattwigway** [jankotek/mapdb#453]
If I run Bind.secondaryKeys with an empty secondary collection, the index is built. However, if I run Bind.histogram with an empty histogram map the histogram is not restored. It looks like the issue is here: https://github.com/jankotek/MapDB/blob/master/src/main/java/org/mapdb/Bind.java#L655

I see that most of the secondary listeners have a conditional along the lines of `if (secondary.isEmpty) { . . . }` and that appears to be missing here.

**Comment by jankotek** [comment]
It is bug indeed, will be fixed soon

**Comment by jankotek** [comment]
Fixed in both branches, fix will be in 1.0.8 and 2.0-beta2
