### ISSUE TITLE
nightly build

### ISSUE THREAD

**Issue by cubefriendly** [jankotek/MapDB#454]
Hi,
I started to use CircleCI for my app and of course now I have issues with mapDB dependency. 
Is there a possibility to have nightly builds?

**Comment by jankotek** [comment]
Daily builds (or last successful build) is in snapshot repo. I update it manually after most commits. 
http://www.mapdb.org/doc/getting-started.html

There is also Travis for continuous integration. 

I have no plans to extend it.

**Comment by cubefriendly** [comment]
Silly me!
You are right thank you!
