### ISSUE TITLE
Transactions Q

### ISSUE THREAD

**Issue by hugebdu** [jankotek/MapDB#455]
Jan, hey.

First of all thanks for this great lib.

I have a Q regarding transactions.
I'm trying to implement persistent job queue on top of MapDB blocking queue with multiple producers/consumers (threads).
I'd like to have a behaviour similar to any other MQ broker - when an item is polled from the queue in a transaction, it won't be available to any other consumer unless the transaction is rolled back.
I guess the transactions out-of-the-box (TxMaker) won't blend - the item consumed will be available to other threads until the transaction is committed.

Any suggestions/ideas?

Thanks in advance.

Daniel

**Comment by jankotek** [comment]
MapDB has regular transaction. So the item will be available to all transactions, but only single tx will be able to commit. Remaining transaction will be rolled back with `TxRollbackException`
