### ISSUE TITLE
worse performance with transactionDisable

### ISSUE THREAD

**Issue by cubefriendly** [jankotek/mapdb#456]
Hi,
I try to fine tune my MapDB config (2.0.0-SNAPSHOT) but I am a bit puzzled as the best config so far is no config.

my use case is that I write several maps in parallel by indexing values from a CSV file.
Here is the time for a default config:
The maps are tree maps with no particular configurations. (it is a Map<Integer,String> and Map<String,Integer>)
this benchmark show how long it took to process each 1000 lines.

1000;214
2000;101
3000;153
4000;151
5000;194
6000;258
7000;294
8000;327
9000;398
10000;436
11000;578
12000;426
13000;454
14000;486
15000;526
16000;556
17000;597
18000;633
19000;684
20000;721
21000;773
22000;839
23000;909
24000;958
25000;1002
26000;1105
27000;1138
28000;1151
29000;1191
30000;1182
31000;1240
32000;1280

now here are the benchmark with transaction disabled
1000;778
2000;709
3000;555
4000;611
5000;653
6000;2242
7000;4884
8000;7633
9000;10653
10000;13572
11000;16610
12000;16653
13000;16653
14000;16628
... [it takes ages after that] ...
I still think if there is a way for me to use data pump as I know how quicker it is but right now I am stuck with regular put(key,value). 

Is it normal that disabling transactions impacts the performance so badly? I would have thought if should improve the performance instead.

**Comment by cubefriendly** [comment]
Another interesting fact, I don't see any performance improvement if I do it on a memoryDirectDB instead of a File DB and I have the same issues (meaning disableTransaction makes it much much slower)

**Comment by cubefriendly** [comment]
I have to do some tests but I suspect the problem comes from the fact that I write in several different maps that reside in the same file. I will try tonight to separate the maps in different files and see how the performance is impacted by that.

**Comment by cubefriendly** [comment]
I think I have found what the issue is. I was using map.size() before every insert and I found out this is very costly. It works muuuch faster now

**Comment by cubefriendly** [comment]
sorry but even if it works much better, I still have a huge difference in perf between with and without transaction and not how I would have thought.

transactionDisabled:1000;732
2000;546
3000;432
4000;463
5000;435
6000;391
7000;403
8000;441
9000;441
10000;425
11000;439
12000;414
13000;409
14000;393
15000;397
16000;380
17000;382
18000;404
19000;396
20000;396
21000;397
22000;401
23000;452
24000;442
25000;386
26000;407
27000;407
28000;401
29000;400
30000;407
31000;387
32000;395

default:
1000;136
2000;46
3000;53
4000;29
5000;25
6000;24
7000;21
8000;29
9000;23
10000;17
11000;34
12000;20
13000;20
14000;17
15000;17
16000;14
17000;15
18000;14
19000;13
20000;14
21000;24
22000;22
23000;18
24000;21
25000;19
26000;19
27000;37
28000;12
29000;23
30000;13
31000;15
32000;13

**Comment by jankotek** [comment]
Transactions disabled should be MUCH faster. I think problem here is write caching, transactions have write cache. I know about this issue, but will have time to document it, enable configuration in a few weeks. 

If you feel like compiling your own MapDB version, there is a way to enable write cache while transactions are disabled. Go to 
https://github.com/jankotek/MapDB/blob/release-1.0/src/main/java/org/mapdb/DBMaker.java#L918

and replace `StoreDirect` with `StoreCached`. 

Once its done call `db.commit()` to flush write cache sometimes (even if tx are disabled).

**Comment by cubefriendly** [comment]
This is also what I thought! 
I see. Right now it is not urgent enough for me to change MapDB code on my side and merge it on every change. I will stay with transaction enabled and when this is resolved I will disable it again. 

Just an FYI, I am using MapDB 2.0 and not 1.0.x

Thanks for your explanation it makes sense. I am eager to see how faster it will be with the right config!

**Comment by cubefriendly** [comment]
Question regarding StoreDirect vs StoreCached.
I am not sure I understand what the benefit from StoreDirect against StoreCached is. In what case would someone prefer StoreDirect over StoreCached?

**Comment by jankotek** [comment]
Both use the same storage format. Both are non-
transactional stores. StoreCached extends 
StoreDirect and adds write cache, in future it will also 
have async writes.

**Comment by cubefriendly** [comment]
Cool. But then it means that StoreCached should be used if I configure transactionDisabled().writeAsyncEnabled() is that right ?

**Comment by jankotek** [comment]
No, async writes are not 
implemented yet in 2.0 
branch

**Comment by bwzhang2011** [comment]
@cubefriendly,  how about such issue going on ?

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue. is it confirmed or resolved as expected ?

**Comment by cubefriendly** [comment]
as far as my tests go, I don't see a difference between the two anymore.
I suspect that I don't see the difference because my transaction size isn't big enough to really make a difference. So for me the issue is resolved

**Comment by cubefriendly** [comment]
Sorry redid my tests and it is still very slow. I can show you the benchmark if it helps but basically even if I disable transaction and enable asyncWrite I still have significantly slower write performance

**Comment by jankotek** [comment]
Will have a look some time soon.

**Comment by cubefriendly** [comment]
Hi, I come for some news on this subject. Did you do something about it? Should I test it again ? 

Maybe I can create a test code so you can easily test it. Would it help ?

**Comment by cubefriendly** [comment]
.writeAsyncEnabled() makes it the same performance as with transaction. 
So it is good enough for me now as this way I don't have to think about commit etc ..
But still it is not faster than with transactions

**Comment by cubefriendly** [comment]
I will close this as it is not an issue anymore. You still need to know what you are doing when you disable transactions
