### ISSUE TITLE
File descriptors remain open

### ISSUE THREAD

**Issue by freakolowsky** [jankotek/MapDB#457]
On 1.0.6 @ RHEL 6.5 (Oracle Linux Server) ...

I compact db after a certain amount of data is processed. Everything works fine, but i've noticed that file descriptors remain open for the process, all descriptors for db_TSNUMBER_orig, db.p_TSNUMBER_orig and db.t ... i.e. (repeated X-times):

>/proc/27073/fd/369 -> /mapdb/EB_42/state.t
>/proc/27073/fd/370 -> /mapdb/EB_42/state_1425454206734_orig (deleted)
>/proc/27073/fd/371 -> /mapdb/EB_42/state.p_1425454206734_orig (deleted)

no direct issue, but open file descriptors are giving me false warnings as df reports wrong usage stats

ok, one small issue performace seems to drop slightly as the number of descriptors increase

**Comment by jankotek** [comment]
There is 1.0.7 bug fix release. But I believe this was not fixed. 

Would you post db configuration? How you open database with `DBMaker`?

**Comment by freakolowsky** [comment]
>		this.dbState = DBMaker
>				.newFileDB(new File(location, "state"))
>				.asyncWriteEnable()
>				.cacheLRUEnable()
>				.cacheSize(100)
>				.mmapFileEnableIfSupported()
>				.closeOnJvmShutdown()
>				.make();

**Comment by jankotek** [comment]
Closing. Could not replicate, code review seems fine. Should be fixed now.

**Comment by sayyiditow** [comment]
This issue seems to be back on v3.1.0? db.close() is called but looking at linux server using lsof command shows the files still open.

**Comment by sayyiditow** [comment]
Btw, this has no difference if we are using mmap or not. Example conf:

```
        final var db = DBMaker
                .fileDB(filePath)
                .fileLockDisable()
                .fileChannelEnable()
                .closeOnJvmShutdown()
                .make();
```
                
```
                        final var db = DBMaker
                .fileDB(filePath)
                .fileMmapEnable()
                .fileLockDisable()
                .closeOnJvmShutdown()
                .make();
```
                
Both yield same issue. The file descriptors remain open, and end up killing the application on the server until it's restarted.
