### ISSUE TITLE
HTreeMap<String, int[]> changes data in the int[]

### ISSUE THREAD

**Issue by aviadjo** [jankotek/MapDB#458]
I used HTreeMap to store above 100,000 entries if <String, int[2]>. After a month of struggling with non-rational results i found out that the data i inserted to the int[2] was changed. It doesn't happen when i insert only 10,000 entries. This bug force me to stop using HtreeMap until this bug is fixed.

**Comment by cubefriendly** [comment]
Can you be a bit more specific on what is going on?
How was the int[] changed ? Is it possible that the array was modified outside of the map ?

**Comment by aviadjo** [comment]
Yes,
I don't know how the int[] changed, i'm not touching it out side a specific function which insert data.
This phenomenon happen when i'm using HTreeMap. The same code is working fine with the default Map of Java.

**Comment by jankotek** [comment]
This issue sounds very interesting. Could you post more information, your DBMaker configuration, and perhaps hint howto reproduce this issue?

First common mistake is that int[] is not immutable. If its instance gets reused, this could cause different value:
```
int[] val = {1,2};
map.put(11,val);
val[1] = 3; //that is wrong, since value associated with 11 could change as well. 
map.put(12,val);
```

Other issue could be some sort of data corruption. Perhaps enable checksum to catch it: `DBMaker.checksumEnable()`.

**Comment by aviadjo** [comment]
I used:
public static DB m_db_off_heap_CFE = DBMaker.newMemoryDirectDB().transactionDisable().asyncWriteEnable().closeOnJvmShutdown().deleteFilesAfterClose().make();
public static int m_db_counter = 0;

public static Map<String, int[]> GetMapStringIntArray() {
        return m_db_off_heap_CFE.createHashMap(++m_db_counter + "")
                .keySerializer(Serializer.STRING)
                .valueSerializer(Serializer.INT_ARRAY)
                .counterEnable()
                .make();
 }

is something wrong?

It is important to say that my project is working great with the Java Map<String, int[]>. exactly the same code.

**Comment by aviadjo** [comment]
Maybe i used MapDB incorrectly. During runtime I change the values (int[]) of some keys in the Map. 
This is stand opposite to instructions:

* Keys and values must be immutable. MapDB may serialize them on background thread, put them into instance cache... Modifying an object after it was stored is a bad idea.
(http://www.mapdb.org/doc/getting-started.html#maven)

Now i replace that code with the remove of the entry from the map and entering new updated one. I'll check if that helps.

**Comment by aviadjo** [comment]
When i changed the update to remove and insert the problem no longer exist!

**Comment by jankotek** [comment]
> During runtime I change the values (int[]) of some keys in the Map

That is probably problem. MapDB reuses values instances in some ways and they should be immutable.
