### ISSUE TITLE
Request: Is there some safe way to just test if a store is good - checksum valid?

### ISSUE THREAD

**Issue by RoundSparrow** [jankotek/mapdb#460]
My use case is Android with a reasonably high expectation of crashing and corrupting the store.  What I suggest is a entirely safe way to detect on app start-up that the store is corrupted so I can just delete it and start over.  Just a simple method to check that the store headers and checksum - without it starting the transaction writer thread, etc?

**Comment by jankotek** [comment]
There was header checksum in 1.0, but I had to disable it to fix one bug. 

I will add this feature in 2.0. There is also other feature request for new settings, to just delete storage if its corrupted, that will be included as well.

**Comment by jankotek** [comment]
Closing this issue. Delete storage when opened corrupted store, moved to TODO list.
