### ISSUE TITLE
java.lang.IllegalAccessError: WAL not empty; commit first, than compact

### ISSUE THREAD

**Issue by zhoupo** [jankotek/mapdb#463]
Hi,

I put "localDb.commit();" before every "localDb.compact();" but still get the exception:

> Exception in thread "Thread-0" java.lang.IllegalAccessError: WAL not empty; commit first, than compact
> at org.mapdb.StoreWAL.compactPreUnderLock(StoreWAL.java:1100)
> at org.mapdb.StoreDirect.compact(StoreDirect.java:810)
> at org.mapdb.EngineWrapper.compact(EngineWrapper.java:130)
> at org.mapdb.EngineWrapper.compact(EngineWrapper.java:130)
> at org.mapdb.DB.compact(DB.java:1626)

My commit(), compact() are located in Thread.run(), and my DBMaker configuration is:

```
DB localDb = DBMaker.newFileDB(new File(filename)).closeOnJvmShutdown().make();
```

store size: 471M, including *.compact, *.compact.p, *.p, *.t
java -version: java version "1.8.0_11"
uname -r: 2.6.32-279.el6.x86_64

Thanks!

**Comment by jankotek** [comment]
Hi,

My first bet would be Async Write Enabled, but 
your configuration says otherwise. 

Will have a look at this in a few days.

**Comment by zhoupo** [comment]
Hi, @jankotek 

I found the reason via my colleague's code review. It's my fault that I put commit() / compact() into a consumer thread, and queue.offer() into a producer thread, which called by a servlet; so "queue.offer()" may be called between "commit()" and "compact()".

**Comment by jankotek** [comment]
Will handle in 2.0

**Comment by shabanovd** [comment]
Will it be possible to commit operation after lock at compact method? Mean that compact will call commit itself.

**Comment by jankotek** [comment]
@shabanovd MapDB 2.0 uses different WAL format. It is actually possible to perform multiple commits while compaction is running.

**Comment by shabanovd** [comment]
@jankotek wow, that going to be a lot of fun -)
