### ISSUE TITLE
Guava Immutable Map Not Unserialized 

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#472]
Version: 1.0.7

Setup:
    DB db = DBMaker.newFileDB("localfile")
                .closeOnJvmShutdown()
                .make();

Value class: A POJO implementing Serializable with serialVersionUID, no default constructor.
Using a field of type Map<String, Integer>. 

This works if the Map is a HashMap, or wrapped in Collections.unmodifiableMap(). However, if the Map is a ImmutableMap.copyOf(), unserializing fails. The Guava Map impls that are used (depending whether empty, 1 item, or more) do implement Serializable also.

The exception happens on the 2nd run, when the localfile exists already. The local field remains uninitialized in the value class.

**Comment by jankotek** [comment]
I will look into that. Thanks

**Comment by gravelld** [comment]
I'm seeing this with `ImmutableList` (specifically it's the `SerializedForm` which is not converted back to the list, so in my case the value is not re-assigned to an `Iterable` upon deserialisation).

**Comment by jankotek** [comment]
Can not reproduce with MapDB 2.0 and Guava 18

https://github.com/jankotek/mapdb-tools/blob/master/src/test/java/org/mapdb/SerializeGuavaTest.java
