### ISSUE TITLE
More benchmarks should be brought in

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/MapDB#473]
@jankotek , as for the benchmark of mapdb as the link of http://www.mapdb.org/benchmarks.html, I don't quite understand why concurrentHashMap faster than mapb around times.  as sharedHashMap originated from openhft, their results only showed that it would only reduce by 20~30%, so we wonder that how about the mapdb2.0 snapshot performance. as HTreeMap is important for its design, we should do more to improve its performance.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ?

**Comment by jankotek** [comment]
>  I don't quite understand why concurrentHashMap faster than mapb around times

It is new rewritten version from java 8.

> so we wonder that how about the mapdb2.0 snapshot performance

Snapshot for 2.0 are not completed yet. I will update bechnmarks once its done.

**Comment by bwzhang2011** [comment]
@jankotek, thanks for view, I think we care about the performance as the wiki show mapdb performance is not so good compared with concurrentHashMap. hope the snapshot could be provided not long in the future.
