### ISSUE TITLE
Findbugs issues with the code scan 

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/MapDB#475]
@jankotek, after checking out the master recently and also with the findbugs eclipse plugin for code review, here comes many which should be taken int consideration to some extent as follows:
![image](https://cloud.githubusercontent.com/assets/749788/6954159/6a6310e8-d901-11e4-8820-724028333362.png)

**Comment by bwzhang2011** [comment]
![image](https://cloud.githubusercontent.com/assets/749788/6954197/c165af72-d901-11e4-910c-92414a050a1b.png)

**Comment by jankotek** [comment]
Thanks, I installed findbugs in idea, will fix those issues soon
