### ISSUE TITLE
Instance cache is enabled or disable ?

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/MapDB#476]
@jankotek , I noticed that cacheDisable() in DBMaker class is tagged with deprecated and commented with "Instance cache is enable by default". but while I trace the code for cache configuration,just go to line 927 for 
protected Store.Cache createCache(boolean disableLocks, int lockScale) method,  the default cache set which referred with CC class for DEFAULT_CACHE definition is String DEFAULT_CACHE = DBMaker.Keys.cache_disable that means the cache is disabled by default. so here comes my doubt that whether cacheDisable or not.

**Comment by jankotek** [comment]
Javadoc is wrong, cache is disabled by default.
