### ISSUE TITLE
BTreeMap entries out of order

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#477]
There is report in mailing list about out of order entries in BTreeMap: https://groups.google.com/forum/#!topic/mapdb/28EKRxMzxvg 

As a test of MapDB to replace an older storage engine, I copied ~20 million key/value pairs, spread across about 100 BTreeMaps, some with only a handful of entries and others with up to 6.5M entries.

I streamed over my source data in the old storage engine in key order, and wrote to MapDB with the UnsignedBytes.legicographicComparitor from guice.  Then after shutting down and closing the db, I opened it back up and iterated over both stores comparing the raw byte[] keys and values.

MapDB had three key/value pairs out of order.  Every key/value entry is present and found when using get(key), but when iterating over the entry set, a key is very rarely out of order.  

Any Idea how to track it down?  I tried adding only a small subset of data surrounding the out of place key to try and create a small reproducible case, but it seems to happen only for stores that have at least a couple million entries.  In my case the smallest BTreeMap with the issue is 3.3M entries.

One of them by chance has this as the second entry in the store (the others are all millions in), so I printed out the expected and actual values of the first 3 entries:

expected: (key=[], val=[97, 118, 114, 111, 49])
actual: (key=[], val=[97, 118, 114, 111, 49])

expected: (key=[45, 107, 117, 121, 95, 46, 57, 54, 52, 51, 64, 104, 111, 116, 109, 97, 105, 108, 46, 99, 111, 46, 116, 104], val=[30, -14, -86, -31, -71, 19, -14, -86, -31, -71, 19, -60, -78, -69, -96, 19, -60, -78, -69, -96, 19, -12, -105, -15, -97, 19, -6, -21, -53, -16, 17, -46, -112, -18, -97, 19, -46, -112, -18, -97, 19, -46, -112, -18, -97, 19, -54, -54, -18, -97, 19, -54, -54, -18, -97, 19, -36, -19, -49, -16, 17, -106, -123, -17, -97, 19, -108, -82, -17, -97, 19, -46, -30, -87, -41, 18, 0, 0, 0, 0])
actual: (key=[-32, -72, -73, 111, 46, 107, 101, 46, 48, 49, 49, 53, 57, 52, 64, 103, 109, 97, 105, 108, 46, 99, 111, 109], val=[10, -92, -86, -99, -23, 19, -92, -86, -99, -23, 19, -112, -9, -81, -27, 19, -94, -71, -52, -8, 18, -94, -71, -52, -8, 18, 0, 0, 0, 0])

expected: (key=[45, 115, 117, 107, 99, 104, 97, 114, 111, 101, 110, 64, 104, 111, 116, 109, 97, 105, 108, 46, 99, 111, 109], val=[30, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -96, -23, -18, -97, 19, -96, -23, -18, -97, 19, -92, -28, -53, -16, 17, -92, -28, -53, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, -10, -106, -49, -16, 17, 0, 0, 0, 0])
actual: (key=[45, 107, 117, 121, 95, 46, 57, 54, 52, 51, 64, 104, 111, 116, 109, 97, 105, 108, 46, 99, 111, 46, 116, 104], val=[30, -14, -86, -31, -71, 19, -14, -86, -31, -71, 19, -60, -78, -69, -96, 19, -60, -78, -69, -96, 19, -12, -105, -15, -97, 19, -6, -21, -53, -16, 17, -46, -112, -18, -97, 19, -46, -112, -18, -97, 19, -46, -112, -18, -97, 19, -54, -54, -18, -97, 19, -54, -54, -18, -97, 19, -36, -19, -49, -16, 17, -106, -123, -17, -97, 19, -108, -82, -17, -97, 19, -46, -30, -87, -41, 18, 0, 0, 0, 0])

The second expected value shows up in the third position, with the out-of order entry showing up in the middle.   The remaining millions of entries are in order.

**Comment by jandam** [comment]
Hi,
I suspect that there is specified custom comparator but you have to create custom BTreeKeySerializer. In addition it has two public method 'compare' that you must implement.

**Comment by jankotek** [comment]
There was issue with byte[] comparator. Bytes were compared in unsigned mode (0xFF was smaller than 0xFF). I changed comparator in 2.0-beta7, so this issue should be fixed now.
