### ISSUE TITLE
StoreCached: needs upper limit for write cache

### ISSUE THREAD

**Issue by jandam** [jankotek/MapDB#482]
Under huge writes StoreCached ends with OOME. Insert should be protected by cache upper limit. Write cache limit can be per segment to eliminate contention. Only 'delete' and 'update' have to be modified. To achieve current behaviour default value for 'writeCacheLimit' can be Integer.MAX_VALUE.

```java
    @Override
    public <A> void update(long recid, A value, Serializer<A> serializer) {
...
            writeCache[lockPos].put(recid, value, serializer);
            if (writeCache[lockPos].size >= writeCacheLimit) flushWriteCacheSegment(lockPos);
...
```

**Comment by jankotek** [comment]
I am going to hook it up into `DBMaker` under `asyncWrite*` options. There will be option to activate background write thread.  And `asyncWriteCacheSize` which on overflow will cause flush, even without background thread. Default value will be around 1K records.

**Comment by jandam** [comment]
I think that flushInThread should be TRUE when executor is specified. Otherwise it can lead to OOME.

**Comment by jankotek** [comment]
StoreCached is not hooked as async writer. There is `DBMaker.asyncWriteQueueSize()` to control upper bound, default value is 1024. 

Not going to set `flushInThread` if executor is enabled. It can lead to OOEM in theory, but that depends on user settings. It would eliminate advantages of background thread (low latency put/get operations in main thread)

**Comment by jankotek** [comment]
I just realized they share write lock. So Executor can not lead to 
OOEM, because if executor gets blocked, the main thread can not 
add data to write queue

On Friday, April 17, 2015 00:16:50 jandam wrote:


I think that flushInThread should be TRUE when executor is 
specified. Otherwise it can lead to OOME.
