### ISSUE TITLE
Request:  change  namespace for MapDB 2.0 

### ISSUE THREAD

**Issue by scottcarey** [jankotek/MapDB#485]
I will need to load both MapDB 1.x and 2.0 into the same process in order to migrate incrementally while online.

If MapDB 2.0 was in a different namespace (e.g.  org.mapdb2) and different maven coordinates,  then both could co-exist without issue.

Alternatives are to release an artifact with moved contents, but this is more difficult for MapDB (requiring an additional artifact and pom), and more difficult for users if the library is used by both transitive dependencies and themselves.   

For example:  my library wants  MapDB 2.0 and MapDB 1.x simultaneously, and so I use a  'moved' artifact for the latter.  If a third party transitive dependency requires MapDB 1.x, I now have an unresolvable version compatibility situation.
If instead I rely on both 1.x and 2.x, but they are in different namespaces and maven coordinates, then I can even have two third party transitive libraries, one that uses MapDB 1.x and another using MapDB 2.0, and everything will happily work together.

I note that there is a moved artifact, but it is only available as 1.0.6 and was not built for 1.0.7 or prior.

The benefits of moving maven namespaces and package names for major version compatibility changes are large for users because it makes it easy to handle cases like the above without having to resort to OSGi or manual re-packaging.

**Comment by jankotek** [comment]
There 1.0.6 version with renamed package to `org.mapdb10`:
http://mvnrepository.com/artifact/org.mapdb/mapdb-renamed
