### ISSUE TITLE
Usage? doing read-only operations against a TreeMap - interrupting thread makes all future database use fail?

### ISSUE THREAD

**Issue by RoundSparrow** [jankotek/MapDB#487]
Hi.  Running on Android 5.x / ART runtime.  I am creating a dedicated thread that iterates a TreeMap backed by MapDB - it is a read-only usage and runs for about a minute.  It is tied to a GUI operation and sometimes I want to stop the operation due to the interactions of the user (user exits a screen and better to just cancel out the thread to free up the resources / save battery).  I'm on the latest versions, I even downloaded source from github and dropped it into my app - just to be sure it wasn't some quirky JAR issue with Android's dex process.

The problem I run into is this: **DBException$VolumeClosed** and **ClosedChannelException**

I don't understand  why a read-only Iteration of a Map, from a thread that I created, causes all future access to the Maps to fail with these exceptions.  It seems counter-intuitive to the "drop in replacement" of MapDB Map<> objects.  I have no such problems with using the same Map that is not backed by MapDB - say populated by reading from JSON.

          backgroundSearchingThread = new Thread() {
                @Override
                public void run() {
                    try {
                        // TreeMap backed by MapDB
                        for (Map.Entry<Integer, String> singleMapEntry : dataMapSource) {
                          // do work here that takes a couple minutes.
                          // This is read-only access of the dataMapSource
                          // no writes are being done on any of the data backed by MapDB.
                        }
                    } catch (Exception e0) {
                    }
                }
            };
            backgroundSearchingThread.setName("BackgroundSearchingThread");
            backgroundSearchingThread.start();

            // 20 seconds later, the user cancels the thread
            backgroundSearchingThread.interrupt();

My questions are along this line:

1. Why are the internals of the MapDB Executor thread being impacted by my thread?
2. Is there any way to "recover" the internal thread state of MapDB from this? I seem to have to force the entire database to be closed re-opened.  If i close the app and re-open it, the database works fine....

Thank you.

**Comment by jankotek** [comment]
Problems is with thread interrupt. FileChannel gets closed if some thread is interrupted while doing IO. 
Use `DBMaker.randomAccessFileEnable()` in new build
