### ISSUE TITLE
Why not put left space to LongStack?

### ISSUE THREAD

**Issue by fufufu2001** [jankotek/MapDB#492]
For StoreDirect Engine，record always  try to put in LongStack or Page end。
However,when page does not have enough space to contain a record,just new a page,and drop the left space。why not put the left page to LongStack?

**Comment by jankotek** [comment]
I am not sure I understand. Could you paste some commented code?

**Comment by fufufu2001** [comment]
in function freeDataTakeSingle,just drop the data,why not recycle it?
        //does record fit into rest of the page?
        if((lastAllocatedData%PAGE_SIZE + size)/PAGE_SIZE !=0){
            //throw away rest of the page and allocate new
            lastAllocatedData=0;
            freeDataTakeSingle(size);
        }
        //yes it fits here, increase pointer
        ret = lastAllocatedData;
        lastAllocatedData+=size;

**Comment by jankotek** [comment]
I understand now. Memory allocator is very sensitive part, and right now I want to get simple well tested version. Once I have good battery of tests, I will probably rewrite it. 

Data leak is not that bad (worst case scenario is 64K per 1MB, more likely 100 bytes per 1MB). And data gets recycled by compaction. 

I added TODOs into relevant part
