### ISSUE TITLE
mapdb.org without www does not work

### ISSUE THREAD

**Issue by razem-io** [jankotek/mapdb#493]
Recently I wanted to show a friend how awesome mapdb is. I remembered the website but it did not work. Now I know why:

http://www.mapdb.org (works)
http://mapdb.org (does not work)

Is it possible to fix this small issue?

Cheers,
Julian

**Comment by RoundSparrow** [comment]
While on the topic of the website, the bottom-left link on http://www.mapdb.org/features.html#generic-pojo-serialization to Documentation results in a 404.

**Comment by jankotek** [comment]
Will setup forwarding soon

**Comment by jankotek** [comment]
Made DNS change, http://mapdb.org should work in a few hours.

**Comment by razem-io** [comment]
Awesome! Will test it tomorrow and report back.

**Comment by razem-io** [comment]
Sorry forgot to test it. Works like expected. Thank you!
