### ISSUE TITLE
Android Studio compiling from source - suggest README instructions

### ISSUE THREAD

**Issue by RoundSparrow** [jankotek/MapDB#497]
When compiling with Google's Android Studio compiler... the Unsafe Volume sections fail due to not having specific sun classes.  My steps have been to 1) delete the one static class, 2) edit extendStoreVolumeFactory method to comment out the one if condition that references that removed class.

I think it would be a good thing to include what you consider the "officially suggested way" in the README to remove the problem class to be sure that people building from source code do not resolve the problem in different ways and introduce unexpected bugs.

Thank you.

**Comment by jankotek** [comment]
I expect dependency on Unsafe to grow. So I moved all Unsafe related stuff into two classes `UnsafeStuff` and `UnsafeStuffTest`. Those can be safely deleted, mapdb in that case will fallback into documented alternatives. 

Going to document once preprocessor is hooked up and we have official android version.
