### ISSUE TITLE
help please. Inserts taking 20 seconds on a map with 20K rows. Use SQL experience?

### ISSUE THREAD

**Issue by RoundSparrow** [jankotek/MapDB#498]
I'm using a TreeMap and my Map keys are all Integer with linear increments.   If it were SQL and slow inserts, I might use a temp table to insert into (empty) then bulk insert.

Does such a strategy make sense with MapDB?

Any and all suggestions on tuning welcome.  I'm on Android ART runtime (5.0, 5.1, etc).

**Comment by jankotek** [comment]
You could use data pump to make TreeMap faster (checkout examples). Also use correct BTreeKeySerializer class.
