### ISSUE TITLE
FileChannelVol.tryAvailable(long) does not test if storage is available (1.0.7)

### ISSUE THREAD

**Issue by simon-greatrix** [jankotek/MapDB#502]
The existing `tryAvailable` method looks like this:

```java
        @Override
        public boolean tryAvailable(long offset) {
            if(hasLimit && offset>sizeLimit) return false;
            if(offset% chunkSize !=0)
                offset += chunkSize - offset% chunkSize; //round up to multiply of chunk size

            if(offset>size)synchronized (growLock){
                try {
                    channel.truncate(offset);
                    size = offset;
                } catch (IOException e) {
                    throw new IOError(e);
                }
            }
            return true;
        }
```

The `FileChannel.truncate` method does not grow the file if the new size is larger than the current size. As far as I can tell the call to truncate above will never do anything and does not fulfill the methods contract to test if the storage will be available.

I believe that:

`channel.truncate(offset)`

should be replaced with

`raf.setLength(offset)`

For reference, the JavaDoc:

https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html#setLength(long)

https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html#truncate(long)

**Comment by jankotek** [comment]
Fixed in 2.0 branch. Not going to fix in 1.0 branch, since this is not critical error (FileChannel grows if data are written beyond EOF). And it could cause change in behaviour
