### ISSUE TITLE
StoreWAL.close does not call vol.close and so leaks file handles

### ISSUE THREAD

**Issue by batterseapower** [jankotek/MapDB#503]
https://github.com/jankotek/MapDB/blob/master/src/main/java/org/mapdb/StoreWAL.java#L1193

This means you can't e.g. rename a DB that you have just created (and then closed) using the WAL.

Note that you do call vol.close e.g. after replay (https://github.com/jankotek/MapDB/blob/master/src/main/java/org/mapdb/StoreWAL.java#L994), the lack of a close in the close method itself seems to be an oversight.

Could be related to #457 ?

**Comment by jankotek** [comment]
Thanks, this was helpful. Fixed.  I also added log warning if open Volume (file) was GCed.
