### ISSUE TITLE
off-heap HashMap not storing all elements off-heap

### ISSUE THREAD

**Issue by AndreasPetter** [jankotek/MapDB#505]
It seems that arrays which are too long are not stored off-heap even though it is being requested (checked versions 1.0.6 and 1.0.7). 
The following example demonstrates the issue (we used Eclipse Memory Analyzer to view created objects in a heap dump, images attached). A lot of data (maybe all?) seems to be on-heap. If amount in the following Scala example is decreased to s.th. like 5 everything goes off-heap, i.e. it works. Therefore I assume this is a bug, as the documentation suggests that everything should be off-heap.
```scala
package bla

import org.mapdb.{DBMaker, Store}
import scala.util.Random


object App {
  def main(args : Array[String]) {
    val db = DBMaker.newMemoryDirectDB().transactionDisable().asyncWriteEnable().make
    val cache = db.createHashMap("cache").counterEnable().expireStoreSize(1.0d).make[String, Array[Double]]
    val store = Store.forDB(db)
    val rand = new Random
    val amount = 100
    (1 to 100000).foreach { i =>
      val length = rand.nextInt(amount) 
      val bytes = new Array[Double](length)
      (1 to length).foreach( n => bytes(n - 1) = Random.nextInt(127).toDouble)
      cache.put(s"$i", bytes)
    }
    println("complete.")
  }
}
```
On-Heap with amount=100
![on-heap](https://cloud.githubusercontent.com/assets/6032072/7489534/2a95c298-f3d8-11e4-9841-e4f9213fe4de.png)

Off-heap with amount=5
![off-heap](https://cloud.githubusercontent.com/assets/6032072/7489540/3e70d122-f3d8-11e4-989d-8ef4ce63cde5.png)

**Comment by jankotek** [comment]
Problem is in instance cache. 

1) by default mapdb caches all records in cache with 32K size. For large arrays that is lot of memory. Use `DBMaker.cacheSize(100)` to make it smaller or `DBMaker.cacheDisable()` to switch it off completely. 

2) With asyncWrite background thread might not dump data into storage fast enough. That could cause high memory usage as well.
