### ISSUE TITLE
The function in Serializer may be confuse

### ISSUE THREAD

**Issue by haolly** [jankotek/MapDB#507]
there has a function in the class Serializer,
```java
  public Object valueArrayDeleteValue(Object vals, int pos) {
        Object[] valsOrig = (Object[]) vals;
        Object[] vals2 = new Object[valsOrig.length-1];
        System.arraycopy(vals,0,vals2, 0, pos-1);
        System.arraycopy(vals, pos, vals2, pos-1, vals2.length-(pos-1));
        return vals2;
    }
```
if the pos start with 0, then the code ` System.arraycopy(vals,0,vals2, 0, pos-1);` my be change to
` System.arraycopy(vals,0,vals2, 0, pos);`, so do the next line

**Comment by jankotek** [comment]
I prefer not to put if branches into code.

**Comment by jankotek** [comment]
Correction: the pos actually starts at 1, it has to do with index representation in btree
