### ISSUE TITLE
RFE: StoreCached without caching values

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#519]
Please consider new instance/config option for StoreCached that will not have write cache for values.
Caching headVol+index is very powerful feature. Write cache improves writing but randomize access to disk. Huge problem for working with standard disks.

For example I write mostly sorted data to BTreeMap  (value outside node, cannot use pump method).

What about to extract 'headVol' and 'longStack' caching to separate class?

**Comment by jankotek** [comment]
That should not be a problem, I added it as feature request. I will just allow to set write cache to zero. 

Also why Data Pump should handle Values Outside Nodes. Is there some problem with that? Perhaps I could solve it.

**Comment by jankotek** [comment]
Moved to TODO list, closing.
