### ISSUE TITLE
could mapdb add support for soft transaction memory support ?

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/mapdb#520]
As mapdb implements transaction mode with MVCC way, could it provide support for soft transaction memory (stands for STM) or some integration with spring transaction manager ?

**Comment by jankotek** [comment]
There is plan to integrate with Java Transaction API and other enterprise standards. So we will provide support for STM and Spring in couple of months

**Comment by bwzhang2011** [comment]
@jankotek, thanks for review and take it into consideration to let in on the plan.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ? what's your plan with integration towards JTA standard on some spring transaction manager style ?
