### ISSUE TITLE
Please add firstKey() and lastKey() to the BTreeMap

### ISSUE THREAD

**Issue by KIC** [jankotek/mapdb#522]
I would need a drop in replacement for ConcurrentSkipListMap and therefore I will need the methods firstKey() and lastKey(). I have tried to to this by myself but I am not sure if this is the most efficient way to do it:

```java
@Override
    public K firstKey() {
        Iterator<K> it = getDataMap().keySet().iterator();
        return it.hasNext() ? it.next() : null;
    }

    @Override
    public K lastKey() {
        Iterator<K> it = getMap().descendingKeySet().iterator();
        return it.hasNext() ? it.next() : null;
    }
```

**Comment by jankotek** [comment]
BTreeMap already implements `ConcurrentNavigableMap` so it already has both methods. I made small performance improvement on `firstKey()`.
