### ISSUE TITLE
Space allocation at startup

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#532]
We should be able to create new store with fully preallocated memory. For example in-memory store can maximaly use 20GB, there should be option to allocate this space at startup.

**Comment by bobwenx** [comment]
how about using jemalloc to preallocate memory?

**Comment by jankotek** [comment]
I think jemalloc is not in java. 
Anyway, java has all tools, we just 
need to use them in mapdb :)

**Comment by jankotek** [comment]
Moved to TODO list, closing.
