### ISSUE TITLE
NPE is thrown when accessing non-existing key for in-memory map with expireOverflow

### ISSUE THREAD

**Issue by victorbr** [jankotek/mapdb#538]
In version 2.0-alpha3 -
If in-memory map is connected to on-disk map with `expireOverflow` as detailed in the section 7.3 of the manual, `get` for a non-existing key results in NPE from `putIfAbsent` called from `get` (`valueCreator` returns `null`).
`containsKey` works correctly.

**Comment by jankotek** [comment]
Fixed, nice catch.
