### ISSUE TITLE
Custom serializers ignored on map creation

### ISSUE THREAD

**Issue by ypoluektovich** [jankotek/mapdb#540]
If DB.treeMap(String, BTreeKeySerializer, Serializer) gets called with a specific key and/or value serializer, and the map does not exist in the database yet, then the catalog entries written for this map will have default serializers. Shouldn't the supplied values get written instead?
(As of 2.0-beta1. See DB.java, line 1355.)

**Comment by jankotek** [comment]
Nice catch. It also affects HashMap and both sets.
