### ISSUE TITLE
serializable objects

### ISSUE THREAD

**Issue by tecbea** [jankotek/mapdb#541]
Hi ,
should the maps created by the map db not serializable ? 
if want to use it like in storm cluster, i cant sice they are not

regards,

**Comment by jankotek** [comment]
What is exact scenario you need to handle? Just send collection over wire and replicate it on other side? Or some sort of network synchronization?

MapDB collections are more like SQL tables. Each collection is attached to storage (files, memory buffers).

There are two ways to handle this:

1) Save collection as `java.util` counterpart. So after deserialization `HTreeMap` becomes `ConcurrentHashMap` etc. 

2) Serialize collection together with DB configuration and DB data, and restore `DB` on other side.

**Comment by jankotek** [comment]
I decided for first approach: `HTreeMap` becomes `ConcurrentHashMap` after deserialization etc.
