### ISSUE TITLE
Queue API rework in 2.0

### ISSUE THREAD

**Issue by mkalinin** [jankotek/mapdb#543]
Hi guys, I was going to use Queue API and have found that all related methods are still marked as deprecated in beta1 version. Are you still going to support queues in 2.0? if yes, what are plans on its rework? is it a big changes?

**Comment by jankotek** [comment]
I am not really happy with current implementation. But I also have no time to 
rewrite them in 2.0.  So current version is going to stay in 2.0 with deprecated flag. 

I am not sure what will happen in 2.1. Most likely I will redesign and extend Queues 
to include blocking, counted, full-dequeue implementation, multiple/single 
consumers/producers... etc. API will switch to some sort of Maker style pattern. 

In case of new queue framework, I might keep old implementation, but move it to 
separate JAR. So storage format will not change, but it will use different API to 
instantiate Queues.

But there is also small chance I will remove deprecation flag and keep current 
implementation. I am not going to leave MapDB without at least some sort of 
Queue support. 

So feel free to use current implementation, it will be supported for 2.0 lifecycle 
(probably 6+ months). But once 2.1 release with long-term support is out, there 
might be some migration needed.  

Hope this makes sense

**Comment by mkalinin** [comment]
Thanks a lot for the information
