### ISSUE TITLE
ArraySerializer with non serializable fields fails

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#546]
new description
----------------------

MapDB 2.0 tries to store serializers as part of collection definition if Serializer implements Serializable. You are using ArraySerializer, which implements Serializable, but one of the field is your serializer, which is not serializable. And it fails. 

old description
---------------------

To increase speed/ space savings with our text-heavy data I want to serialize it as ASCII. When trying out ```Serializer.STRING_ASCII``` I quickly discovered that it just calls the UTF string serializer, producing identical result (with 2.0-beta2). So I decided to try and roll my own and improve interface by using CharSequence objects instead of Strings, which could represent any other number of string representation without the need of converting them / generating GC. My code is below:

```
    public static final Serializer<CharSequence> ASCII_SERIALIZER = new Serializer<CharSequence>() {
        public void serialize(DataOutput out, CharSequence value) throws IOException {
            int SIZE = value.length();
            DataIO.packInt(out, SIZE);
            for (int i = 0; i < SIZE; i++) {
                out.writeByte((byte)value.charAt(i));
            }
        }
        public CharSequence deserialize(DataInput in, int available) throws IOException {
            int SIZE = DataIO.unpackInt(in);
            StringBuilder result = new StringBuilder(SIZE);
            for (int i = 0; i < SIZE; i++) {
                result.append((char)(in.readByte() & 0xFF));
            }
            return result;
        }
        public int fixedSize() {
            return -1;
        }
    };
```

Unfortunately the code would not run because MapDB tries to assert that the object is Serializable and the CharSequence interface is not:  ``` Exception in thread "main" java.io.IOError: java.io.NotSerializableException ``` . Why is this kind of check even necessary? As long as serializer promises to be able to properly handle CharSequence why shouldn't MapDB let it?

Then I've changed my code to use String (and add a wasteful conversion step from StringBuilder to String), but the error remained. Why doesn't MapDB support serializing CharSequences (and maybe other interfaces) natively, as well as writing custom serializers for basic types like String?

**NOTE:** I am using this serializer as part of a composite BTree key, like in the examples

```
Caused by: java.io.NotSerializableException: com.test.XXXX
        at org.mapdb.SerializerPojo.assertClassSerializable(SerializerPojo.java:370)
        at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:433)
        at org.mapdb.SerializerBase.serialize(SerializerBase.java:985)
        at org.mapdb.SerializerBase$17.serialize(SerializerBase.java:371)
        at org.mapdb.SerializerBase$17.serialize(SerializerBase.java:362)
        at org.mapdb.SerializerBase.serialize(SerializerBase.java:980)
        at org.mapdb.SerializerBase.serialize(SerializerBase.java:931)
        at org.mapdb.Serializer.valueArraySerialize(Serializer.java:1714)
        at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:766)
        at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:702)
        at org.mapdb.Store.serialize(Store.java:270)
        ... 7 more
```

**Comment by jankotek** [comment]
Not going to fix, `CharSequence` is not class but interface. I would not know what class to return after deserialization.

Fixed issue in `Serializer.STRING_ASCII`, now it uses 8 bit characters instead of packed ints. If you are using `BTreeMap<String...>` this optimalization is already present.

Also I would perhaps recommend to try `byte[]` instead of string. MapDB does hashing and comparison if `Serializer.BYTE_ARRAY` is specified.

**Comment by dmk23** [comment]
```I would not know what class to return after deserialization.```

Why not return whatever object deserializer returns that matches that interface? Why do you have to have a specific class? You might want to take a look at Chronicle Map project that offers some similar functionality, but does it with full support of CharSequence everywhere to cut down object creation:
https://github.com/OpenHFT/Chronicle-Map

**Comment by dmk23** [comment]
As far as ```Serializer.STRING_ASCII``` I still see the code that overrode it with ```Serializer.STRING```
```
        @Override
        public BTreeKeySerializer getBTreeKeySerializer(Comparator comparator) {
            if(comparator!=null && comparator!=Fun.COMPARATOR) {
                return super.getBTreeKeySerializer(comparator);
            }
            return BTreeKeySerializer.STRING; //TODO ascii specific serializer?
        }
```

**Comment by jankotek** [comment]
BTreeKeySerializer.STRING  downgrades to 
byte[] if only ASCII strings are used.

I could provide Serializer.CHARSEQUENCE which 
does what you want, but could you tell me 
why? What is use case? I think many users 
would find it confusing. And to cut down GC I 
recommend to use byte[] directly anyway.

**Comment by dmk23** [comment]
Conversion to byte[] and back would cause unnecessary creation of objects and copying of the memory. CharSequence would allow the use StringBuilders as mutable strings and have them pass comparisons to mutable strings. StringBuilder can be created once and reused, but every time we create a String it is immutable and has to be discarded.

We use StringBuilder pretty heavily as mutable / poolable strings and CharSequence interface is the way to harmonize them with Strings. We've also wrapped some custom classes in CharSequence interface (which is very easy to implement) to make them behave like strings but be backed by different data structures. There are plenty of other CharSequence examples...

**Comment by dmk23** [comment]
RE: BTreeKeySerializer.STRING  downgrades to byte[] if only ASCII strings are used

I did not realize that! I wanted to try explicit ASCII encoding after a test that converted a certain ASCII text file into a slightly larger BTree file, while I thought it would have lots of common prefixes to compress instead. On the other hand I can see how BTrees would add some storage overhead...

**Comment by jankotek** [comment]
Sorry, still not going to add CharSequence serializer.  But it 
should be easy to use your own serializer for most purposes.

BTW: MapDB requires that stored objects are immutable. If 
you store object, and latter modify it could lead to 
unpredictable behaviour. MapDB has async writer, instance 
cache... For example change in hashCode() could lead to 
infinitive loops or even data corruption.

Jan

**Comment by dmk23** [comment]
I'd love to add such a serializer (per my original post) or other custom serializers based on interfaces but it fails ```SerializerPojo.assertClassSerializable```. Could you make that assert optional as an advanced option to be turned on at user's own risk?

As far as immutability I think that would strictly apply only to fields that actually get serialized. For example we have a few POJOs that include a key field that we do not serialize to MapDB, but add back to the object after loading (through a wrapper around MapDB's get). There could be quite a few other examples of mutating transient state that should not imply true mutability. If we know exactly what objects we are using with certain serializers we can control our own ```hashCode()``` and ```equals()``` to make it work correctly. If JVM is generating a lot of garbage such shortcuts are pretty much necessary.

**Comment by jankotek** [comment]
You are using generic serialization, in that case it 
fails.

What you need to do is to create your own 
serializer, and then pass it as:

        db.createTreeMap("aa").keySerializer(yourserial
izer).make()

**Comment by dmk23** [comment]
That's exactly what I did. I got the SerializerPojo assertion error from my original post.

**Comment by jankotek** [comment]
That is strange, from stack trace it fails on BTreeMap value with default serializer. Are you sure `.valueSerializer()` is set?

Could you send code used to instantiate your map or collection? Also what way are you reopening collection between JVM restarts?

**Comment by dmk23** [comment]
This example was for ```treeSetCreate``` so there was only one serializer.

With other custom POJOs I've gotten the same error for ```treeMapCreate``` with String key (and .STRING key serializer) and custom value serializer. That error went away when I manually added ```implement Serializable``` to my POJOs

That solution however is not possible if I want to create polymorphic serializers based off an interface, like CharSequence or whatever else might be needed later....

**Comment by jankotek** [comment]
That is strange. Generic serialization should not be used with: `treeSetCreate("name").serializer(your_serializer).make()`

Either there is a bug and serializer is not used for some reason. Or the collection already existed and the new serializer was not applied. I will write some tests. I could also use some help. Could you try to recreate the issue on in-memory collection? Also send me code used to instantiate map. I do not need your serializer or any details about your collection. 

Also my email is `jan at kotek.net`

**Comment by dmk23** [comment]
The tree set test was done for a file DB (with file manually deleted before each new run) and the prior map tests were done for direct memory DB. Here is my code to instantiate DB and tree set : 

```
          DB db = DBMaker
                .newFileDB(file)
                .transactionDisable()
                .mmapFileEnable()
                .asyncWriteEnable()
                .make();

            BTreeKeySerializer XYZ_SERIALIZER = new BTreeKeySerializer.ArrayKeySerializer(
                new Comparator[]{Fun.COMPARATOR,Fun.COMPARATOR},
                new Serializer[]{Serializer.ASCII_SERIALIZER, Serializer.ASCII_SERIALIZER}
            );

            NavigableSet<Object[]> multiMap = db.treeSetCreate("xyz")
                .serializer(XYZ_SERIALIZER)
                .make();

           multiMap.add(new Object[] { "str1", "str2" } );
```

I do not have the original code that caused the same exception for the tree map since it was wiped out and rewritten many times over by now. But the exception was exactly the same.

The original map test used ```Serializer.STRING``` for keys and custom POJO serializer for values, so apparently the problem is not specific to BTree composite keys....

Probably there is some bug somewhere... The stack trace is available in my original post...

**Comment by jankotek** [comment]
I added test case, but so far I can 
not replicate this issue. Will try 
again some time soon.

**Comment by dmk23** [comment]
Is it using the same custom ASCII_SERIALIZER with ```CharSequence``` type? Let me know if you are going to check in the test case so I could try it "as is" or identify what is different from what I ran.

**Comment by jankotek** [comment]
Source code for test case is here:
https://github.com/jankotek/mapdb/commit/7dd39481ab55ecc2b745118df8e3802a4f68230b#diff-904b62680fbc6338eb7a5b7721e33c7bR165

**Comment by dmk23** [comment]
Yes, I saw it already - see my updated comment

**Comment by jankotek** [comment]
I think I see where is the problem now. Its not CharSequence, but your Serializer.

MapDB 2.0 tries to store serializers as part of collection definition if Serializer implements Serializable. You are using ArraySerializer, which implements Serializable, but one of the field is your serializer, which is not serializable. And it fails. 

For now move ASCII_SERIALIZER into separate final class and make it to implement Serializable. I will reopen this issue and reformat description.

**Comment by dmk23** [comment]
Thanks for tracking this down. On my end I solved this by deriving all my serializers from this simple abstract wrapper class. I think the same interface could be added to core abstract serializer.

```private static abstract class BaseSerializer<T> extends Serializer<T> implements Serializable {};```

With this change in place my custom serializers works fine for both ```<String>``` and ```<CharSequence>```. They produce identically sized files for both cases and the size is the same as for the original ```Serializer.STRING``` that indeed compresses UTF correctly. With ```<CharSequence>``` it is ~10% slower than with ```<String>``` and the standard serializer is about 10% faster yet.

**Comment by dmk23** [comment]
One more issue, likely related to serialization of serializers. This is what we get on re-opening a collection persisted to file:

```WARNING: Set 'XXX' has serializer defined in Name Catalog, but other serializer was passed as constructor argument. Using one from constructor argument.```

Why would the name catalog save a wrong serializer if the set was duly constructed and should know exactly what serializer we wanted to use?
