### ISSUE TITLE
ClassCastException mapd 1.0.8 

### ISSUE THREAD

**Issue by Skerberus** [jankotek/mapdb#548]
In mapdb 1.0.7 this works fine

private Var<byte[]> lastBlockVar;
	private byte[] lastBlockSignature;

this.lastBlockVar = database.getAtomicVar("lastBlock");
this.lastBlockSignature = lastBlockVar.get();

(here null is returned, which is OK)

In mapdb 1.0.8 an empty String is returned but should be null (starting from scratch).
java.lang.ClassCastException: java.lang.String cannot be cast to [B
    at database.BlockMap.<init>(BlockMap.java:46)
    at database.DBSet.<init>(DBSet.java:95)

**Comment by agran** [comment]
https://github.com/Qoracoin/Qora/blob/0.22.0/Qora/src/database/BlockMap.java

**Comment by jankotek** [comment]
There were some problems with persisting nulls. So I changed default value for Atomic.Var from null to "". Solution for this is to supply your own default value as second parameter: `DB.createAtomicVar("lastBlock",new byte[0]);`

Or use 2.0 which has this problem solved and allows null.s
