### ISSUE TITLE
Reading and removing object from memory

### ISSUE THREAD

**Issue by tamirtrigalo** [jankotek/mapdb#552]
Hi,
There are 2 issues that i wanted to ask.
1. When i am writing to HTreeMap which is connected to a memory direct DB, i want to be able to read the object from the memory and not from the disk, but when i do that i only get the key of the object without its value (the value is null).
2. Another thing is that i want to remove an object from the memory permanently in one atomic action. I don't want to remove the object from the memory and then remove it from the disk. 

Here is an example code for what i want to happen:

        //creating a DB, and two maps, one on disk and one in memory
        DB db = DBMaker.memoryDirectDB()
                .transactionDisable()
                .make();

        HTreeMap onDisk = db.hashMapCreate("onDisk")
                .keySerializer(Serializer.INTEGER)
                .valueSerializer(Serializer.STRING)
                .make();

        HTreeMap inMemory = db.hashMapCreate("inMemory")
                .expireOverflow(onDisk, false)
                .expireStoreSize(0.1)
                .make()

         inMemory.put(1, "one"); //writing an object to memory
         Object object = inMemory.get(1); // object should be "one" but it's null
         inMemory.remove(1);
         object = onDisk.get(1); // object should be null and not "one"

Can you help me with that?
Thanks

**Comment by jankotek** [comment]
1) expiration is approximate, so single entry might get removed, but once you have thousands it will stay.

2) store statistics do not work currently and expireStoreSize(0.1) is broken.

**Comment by jankotek** [comment]
I deprecated the `expireStoreSize` option. Either I fix it in near future, or it will be removed.

**Comment by kobikis** [comment]
Hi,

How do you suggest to use mapdb for memory to file overflow use case?

Thanks,
Kobi

**Comment by jankotek** [comment]
There is maximal map size 
limit

**Comment by kobikis** [comment]
OK so if the memory space is full objects will overflow to file?

Another issue we see is after writing an object and reading it the value is null.

 DB db = DBMaker.memoryDirectDB()
            .transactionDisable()
            .make();

    HTreeMap onDisk = db.hashMapCreate("onDisk")
            .keySerializer(Serializer.INTEGER)
            .valueSerializer(Serializer.STRING)
            .make();

    HTreeMap inMemory = db.hashMapCreate("inMemory")
            .expireOverflow(onDisk, false)
            .executorEnable()
            .make()

     inMemory.put(1, "one"); //writing an object to memory
     Object object = inMemory.get(1); // value should be "one" but it's null

**Comment by jankotek** [comment]
I just fixed the free space reporting, there is a chance it might work in latest commit. Will have look at this tomorrow.

**Comment by jankotek** [comment]
There is beta4 which should have this fixed. Please checkout this example and try it: https://github.com/jankotek/mapdb/blob/master/src/test/java/examples/CacheOffHeapAdvanced.java

Also the expiration is aproximate, you should give it at least gigabyte with 1M+ records to get good results
