### ISSUE TITLE
Compaction bug

### ISSUE THREAD

**Issue by tamirtrigalo** [jankotek/mapdb#554]
Hi,
At version 2.0 I was using MapDB with direct memory, then i wrote objects to it while i was monitoring the mapped and direct memory (with Java VisualVM) and i couldn't see any compaction activity although i was calling to the compact function explicitly.
Note that the compaction does work at version 1.0.7.
Here is a code example:

      DB db = DBMaker
                .memoryDB()
                .compressionEnable()
                .transactionDisable()
                .make();
        
        HTreeMap inMemory= db.hashMapCreate("Container")
                .keySerializer(Serializer.STRING)
                .valueSerializer(Serializer.BYTE_ARRAY)
                .make();
        
        for (int i=0; i<1000; i++){
            inMemory.put(i,"mapped to "+i);
            db.compact();  
        }

Could you take a look at it?
Thanks

**Comment by jankotek** [comment]
I recently fixed a bunch of compaction errors, it should be fine in 2.0 beta4. Could you give it try?

**Comment by jankotek** [comment]
Could not replicate in recent release
