### ISSUE TITLE
Fluent syntax for transactionDisable()

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#558]
If I have a configured boolean whether I want transactions or not, currently it's not possible to create a DB with the builder syntax in one line. I have to go through a DBMaker.Maker variable. It's ugly.

How about adding such a method:

    DBMaker
        .fileDB(myFile)
        .closeOnJvmShutdown()
        .withTransaction(myBoolean) //this here
        .make()

**Comment by jankotek** [comment]
Naming convention tries to be code autocomplete friendly, so most significant part goes first. Also transactions are on by defualt so `withTransaction(true)` is redundant.

**Comment by jankotek** [comment]
Naming convention tries to be code autocomplete friendly, so most significant part goes first. Also transactions are on by defualt so `withTransaction(true)` is redundant.

**Comment by jankotek** [comment]
Naming convention tries to be code autocomplete friendly, so most significant part goes first. Also transactions are on by defualt so `withTransaction(true)` is redundant.
