### ISSUE TITLE
hashMapCreate() confusing naming

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#559]
I did not understand the method names for creating a new db and map at first, only through copy-pasting from examples, and error, I finally got to what I needed.

The problems:
* db.hashMapCreate() does not create a hash map, it creates a map maker.
* there is another method in the same class, with the same name, that actually creates a map and not a maker: `synchronized protected <K,V> HTreeMap<K,V> hashMapCreate(HTreeMapMaker m)`
* the overall syntax db.hashMapCreate("myThing").make() doesn't feel right (create, make)
* the methods make() and makeOrGet(), although obvious after running into an error, have not Javadoc yet.

The suggestions:
* Although the word 'maker' is correct and good, I believe the word 'builder' is more common, with the language Builder.build(). So rename Maker to Builder? And since it happens that one needs a local variable, I would not mind having it as a top level class.
* change method hashMapCreate(name) into newBuilder(), possibly as newBuilder(name), add methods for map type like .mapTypeHashMap() or .mapType(MapTypes.HASHMAP) or something like that.

Instead of this:

    db.hashMapCreate("myCache").maximumSize(999).makeOrGet();

Some imagined new syntax:

    db.newBuilder().name("myCache").mapTypeHashMap().maximumSize(999).build();

Compare with Guava cache:

    CacheBuilder.newBuilder().maximumSize(memoryCacheSize).build();

This got rid of the difference between make() and makeOrGet(), meaning whether it is expected to exist already or not. In the current form, one can enforce that it's new, and it throws if it exists already. However, as I see it, the opposite is not possible, ensuring it's existent.
My guess is that most users don't care, and the above syntax with .build() would do the job. At least that's my use case, using it as a persistent cache.
You could add syntax like .mustExist() or .mustBeNew(), and catch all 3 use cases (yes, no, don't care).

These are my not well researched thoughts. I'm new to mapdb. My feeling so far is that there is one guy (Jan) who works hard on this software. My experience in programming is that the collaborative efforts of multiple people, with feedback, lead to better, cleaner APIs. A co-worker once told me that "a nice API is worth a lot". These small changes seem like not much, they don't add functionality. But I believe they add users.

**Comment by cubefriendly** [comment]
Hi,
I had the same issue but I would continue with giving the data structure in the method name. Also, either you change Maker -> Builder or you change the method name to Maker.

something like : 
````
db.newHashMapMaker().name("myCache").maximumSize(999).makeOrGet();
````

It makes sense to me to call it a maker because the idea is to "make" a map, not build one. In Guice, the builder builds a map with content, here it is not the case.

I would also keep "makeOrGet" as it has an history behind it. but new methods like 
"make" : to make a new one or throw an exception if already exists
"makeNew": to make a new one and override the previous one if existed
(these are only ideas) 

The issue with giving Map types as parameter is that then you have either incomplete config or default values that are dangerous. Configuration should be as explicit as possible for the important decisions.

**Comment by jankotek** [comment]
I do not really see how new API is better.  Current API served awell so far, so I am not going to change it.  
A few notes:

- DP API is originally inspired by SQL, and it aims to be statically typed, latter it was 'tuned down' to be more dynamically typed. (CREATE TABLE....)

- Method naming convention tries to be  IDE code autocomplete friendly, so most significant part goes first. `db.hash...` should give all methods related to hashMap (create, make...)

- Non persistent in-memory collections are very simple use case, but I need to support more complex types, for example HashMap sharded across 16 different storages.  I feel current version allows me more flexibility for future

-  stuff like .mustExist() or .mustBeNew() is on my TODO list. 

- I really think it can not get much better than this. If anything I want to invest time into documentation and 

- Dont care about Guava, there are many libraries, can not please everyone.
