### ISSUE TITLE
Documentation, grammar and spellings

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#560]
I like documentation in Wiki, for example on GitHub.
It's super easy for everyone to contribute.

Mapdb has a site where I would not know how to contribute fixes.
And there is a manual in PDF form.

Jan's native language (Czech) is Slavic, further away from English, and naturally there are more mistakes. The text is understandable, it just looks less professional.
Eg first sentence on homepage http://www.mapdb.org/ "MapDB is embedded database engine." => "MapDB is an embedded database engine."

http://www.mapdb.org/doc/concurrency.html "There are global locks and stop-word states." => stop-the-world I assume.

I would like it if Jan had more time for coding, and would have to spend less on updating documentation.

**Comment by jankotek** [comment]
Typos fixed, they will be at mapdb.org next day.

Site and documentation are at github and it is fairly easy to contribute:
https://github.com/jankotek/mapdb-site

I have cron script which synchronizes repo with website every day.
