### ISSUE TITLE
could mapdb add support for cursor ?

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/mapdb#565]
Recently, Our projects used log4j-flume-ng while it provided the log component integrated with berkleyDB for event log persisted into it. as I'm not familiar with berkeydb and when I read the source code, I felt that we could do something with mapdb which could make use of its Engine for persistent.

as Engine didn't provide any cursor API like berkleyDB did, I could not directly iterator the result sets in Engine file. for as the persistent design of log4j-flume-ng, when it decided to send the log event to the remote agents, it first tried to persist it into the db. for this part I had to save the record id by calling put method in Engine into some data structure like BlocingQueue, for other side it would start some send thread just read(or drain) from the data structure, use the record ids to fetch from db to get the data persisted. 

as commented above, it has some shortcomings for I had to create the shared data structure and it should process once the remote agents was dead and I could not find proper way to load the data from the Engine,  so the cursor API is much needed. one side that I could read the file data if it was started if the data file was not corrupted.  what's more, the db file load and get was hard to use(for it return boolean for most cases I just mean I wanted to get the engine matched directed to the file).

here comes my API for log event with mapdb and I hope @jankotek  you could leave me some advice (for another side, if I started another program just for read the data from the file, how could I implement that ?

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInput;
import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.crypto.SecretKey;

import org.apache.flume.Event;
import org.apache.flume.event.SimpleEvent;
import org.apache.logging.log4j.flume.appender.BatchEvent;
import org.apache.logging.log4j.flume.appender.FlumeAppenderCipherHelper;
import org.mapdb.DBMaker;
import org.mapdb.DataIO;
import org.mapdb.Engine;
import org.mapdb.Serializer;
import org.mapdb.TxMaker;

public class FlumeMapdbHelper {

	// 初始分配的本地文件大小为32M
	public static final long DEFAULT_ALLOCATE_STARTZIE = 32L;

	// 后续增加的文件大小为2M
	public static final long DEFAULT_ALLOCATE_INCRESIZE = 2L;
	
	// 缺省writeQueue大小
	public static final int DEFAULT_WRITE_QUEUESIZE = 1024;
	
	// 缺省 IO buffer大小
	public static final int DEFAULT_IO_BUFFERSIZE = 512;
	
	private FlumeMapdbHelper() {
		
	}

	/**
	 * 
	 * @Time: 2015年8月26日 下午8:51:30
	 * @Title: getTxEngine
	 * @Description: 构建基于dataPath的存储引擎
	 * @param @param dataPath
	 * @param @return
	 * @return Engine
	 * @throws
	 */
	public static Engine getTxEngine(String dataPath) {
		TxMaker txMaker = getTxMaker(dataPath);

		return txMaker.makeTx().getEngine();
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午11:37:54
	 * @Title: commit
	 * @Description: 提交事务
	 * @param @param txEngine  
	 * @return void   
	 * @throws
	 */
	public static void commit(Engine txEngine) {
		if(txEngine != null) {
			txEngine.commit();	
		}		
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午11:38:03
	 * @Title: rollback
	 * @Description: 回滚事务
	 * @param @param txEngine  
	 * @return void   
	 * @throws
	 */
	public static void rollback(Engine txEngine) {
		if(txEngine != null) {
			txEngine.rollback();
		}
	}

	/**
	 * 
	 * @Time: 2015年8月26日 下午8:50:00
	 * @Title: getTxMaker
	 * @Description: 构建基于dataPath的txMaker
	 * @param @param dataPath
	 * @param @return
	 * @return TxMaker
	 * @throws
	 */
	public static TxMaker getTxMaker(String dataPath) {
		return getTxMaker(dataPath, DEFAULT_ALLOCATE_STARTZIE, DEFAULT_ALLOCATE_INCRESIZE, DEFAULT_WRITE_QUEUESIZE);
	}

	/**
	 * 
	 * @Time: 2015年8月26日 下午8:50:13
	 * @Title: getTxMaker
	 * @Description: 同上关联分配的初始大小和递增大小
	 * @param @param dataPath
	 * @param @param startSize
	 * @param @param increSize
	 * @param @param writeQueueSize
	 * @param @return
	 * @return TxMaker
	 * @throws
	 */
	public static TxMaker getTxMaker(String dataPath, long startSize, long increSize, int writeQueueSize) {
		return DBMaker.fileDB(new File(dataPath)).fileMmapCleanerHackEnable()
				      .fileMmapEnableIfSupported().fileMmapEnable()
				      .allocateStartSize(startSize).allocateIncrement(increSize)
				      .asyncWriteEnable().asyncWriteQueueSize(writeQueueSize)
				      .closeOnJvmShutdown().makeTxMaker();
	}
	
	/**
	 * 返回记录编号
	 * 
	 * @Time: 2015年8月27日 上午10:48:33
	 * @Title: persistEvent
	 * @Description: 通过构建引擎(结合序列化器)将event持久化
	 * @param @param persistEngine
	 * @param @param event
	 * @param @param eventSerializer
	 * @param @return  
	 * @return long   
	 * @throws
	 */
	public static long persistEvent(Engine persistEngine, Event event, Serializer<Event> eventSerializer) {
		return persistEngine.put(event, eventSerializer);
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午10:50:17
	 * @Title: getPersistEvent
	 * @Description: 跟进记录编号（及序列化器)从引擎中读取持久化记录
	 * @param @param persistEngine
	 * @param @param persistId
	 * @param @param eventSerializer
	 * @param @return  
	 * @return Event   
	 * @throws
	 */
	public static Event getPersistEvent(Engine persistEngine, long persistId, Serializer<Event> eventSerializer) {
		return persistEngine.get(persistId, eventSerializer);
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午11:43:22
	 * @Title: updatePersistEvent
	 * @Description: 更新存储ID对应的值
	 * @param @param persistEngine
	 * @param @param persistId
	 * @param @param eventSerializer
	 * @param @param event  
	 * @return void   
	 * @throws
	 */
	public static void updatePersistEvent(Engine persistEngine, long persistId, Serializer<Event> eventSerializer,
			     Event event) {
		persistEngine.update(persistId, event, eventSerializer);
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午11:43:25
	 * @Title: deletePersistEvent
	 * @Description: 移除存储ID对应值
	 * @param @param persistEngine
	 * @param @param persistId
	 * @param @param eventSerializer  
	 * @return void   
	 * @throws
	 */
	public static void deletePersistEvent(Engine persistEngine, long persistId, Serializer<Event> eventSerializer) {
		persistEngine.delete(persistId, eventSerializer);
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 下午1:27:10
	 * @Title: deletePersistEvent
	 * @Description: 批量移除存储ID对应的值
	 * @param @param persistEngine
	 * @param @param persistIds
	 * @param @param eventSerializer  
	 * @return void   
	 * @throws
	 */
	public static void deletePersistEvent(Engine persistEngine, long[] persistIds, Serializer<Event> eventSerializer) {
		for(long persistId : persistIds) {
			deletePersistEvent(persistEngine, persistId, eventSerializer);
		}
	}
	
	/**
	 * 
	 * @Time: 2015年8月27日 上午10:52:38
	 * @Title: getPersistBatchEvent
	 * @Description: 跟进批量持久ID记录号构建batchEvent
	 * @param @param persistEngine
	 * @param @param persistIds
	 * @param @param eventSerializer
	 * @param @return  
	 * @return BatchEvent   
	 * @throws
	 */
	public static BatchEvent getPersistBatchEvent(Engine persistEngine, long[] persistIds, Serializer<Event> eventSerializer) {
		BatchEvent batchEvent = new BatchEvent();
		
		for(long persistId : persistIds) {
			Event event = getPersistEvent(persistEngine, persistId, eventSerializer);
			
			batchEvent.addEvent(event);
		}
		
		return batchEvent;
	}

	/**
	 * 
	 * @Time: 2015年8月27日 上午9:47:20
	 * @Title: getFlumeEventSerializer
	 * @Description: 构建满足secretKey方式的序列化器
	 * @param @param secretKey
	 * @param @return
	 * @return Serializer<Event>
	 * @throws
	 */
	public static Serializer<Event> getFlumeEventSerializer(final SecretKey secretKey) {
		return new Serializer<Event>() {

			@Override
			public void serialize(DataOutput out, Event event) throws IOException {

				try {
					byte[] eventData = getEventData(event);

					DataIO.packInt(out, eventData.length);

					out.write(eventData, 0, eventData.length);
				} catch (Exception ex) {
					throw new IOException(ex);
				}

			}

			@Override
			public Event deserialize(DataInput in, int available) throws IOException {
				try {
					byte[] eventData = getEventData(in);

					return deserialize(eventData);
				} catch (Exception ex) {
					throw new IOException(ex);
				}
			}

			/**
			 * 
			 * @Time: 2015年8月27日 上午10:12:57
			 * @Title: getEventData
			 * @Description: 将event进行打包(若存在key则整体进行加密)
			 * @param @param event
			 * @param @return
			 * @param @throws Exception
			 * @return byte[]
			 * @throws
			 */
			private byte[] getEventData(Event event) throws Exception {
				final ByteArrayOutputStream baos = new ByteArrayOutputStream(DEFAULT_IO_BUFFERSIZE);

				final DataOutputStream daos = new DataOutputStream(baos);

				try {
					byte[] body = event.getBody();

					Map<String, String> headers = event.getHeaders();

					daos.writeInt(body.length);
					daos.write(body, 0, body.length);
					daos.writeInt(headers.size());

					for (Map.Entry<String, String> entry : headers.entrySet()) {
						daos.writeUTF(entry.getKey());
						daos.writeUTF(entry.getValue());
					}

					byte[] eventData = baos.toByteArray();

					return (secretKey == null) ? eventData : FlumeAppenderCipherHelper.encrypt(eventData, secretKey);
				} finally {
					daos.close();
				}
			}

			/**
			 * 
			 * @Time: 2015年8月27日 上午10:17:27
			 * @Title: getEventData
			 * @Description: 从in中提取eventData
			 * @param @param in
			 * @param @return
			 * @param @throws Exception
			 * @return byte[]
			 * @throws
			 */
			private byte[] getEventData(DataInput in) throws Exception {
				int size = DataIO.unpackInt(in);

				byte[] eventData = new byte[size];

				in.readFully(eventData);

				return (secretKey == null) ? eventData : FlumeAppenderCipherHelper.decrypt(eventData, secretKey);
			}

			private Event deserialize(byte[] eventData) throws Exception {
				final ByteArrayInputStream bais = new ByteArrayInputStream(eventData);

				final DataInputStream dais = new DataInputStream(bais);

				SimpleEvent event = null;

				try {
					event = new SimpleEvent();

					int length = dais.readInt();
					final byte[] bytes = new byte[length];
					dais.read(bytes, 0, length);

					event.setBody(bytes);

					final Map<String, String> map = new HashMap<String, String>(length);
					for (int i = 0; i < length; ++i) {
						final String headerKey = dais.readUTF();
						final String value = dais.readUTF();
						map.put(headerKey, value);
					}

					event.setHeaders(map);
				} finally {
					dais.close();					
				}

				return event;
			}

		};
	}

}

**Comment by bwzhang2011** [comment]
Another cipher class:

import java.io.ByteArrayOutputStream;
import java.io.Closeable;
import java.io.IOException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.security.Provider;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;

public class FlumeAppenderCipherHelper {

	private FlumeAppenderCipherHelper() {
		
	}
	
	/** 最大文件加密块 */
	private static final int MAX_ENCRYPT_BLOCK = 117;

	/** 最大文件解密块 */
	private static final int MAX_DECRYPT_BLOCK = 128;
	
	public static final String DEFAULT_CIPHER_ALGORITHM = "AES";
	
	public static byte[] encrypt(byte[] text, Key key) throws Exception {
		return encrypt(text, getAlgorithmCipher(null, DEFAULT_CIPHER_ALGORITHM), DEFAULT_CIPHER_ALGORITHM, key);
	}
	
	public static byte[] decrypt(byte[] text, Key key) throws Exception{
		return decrypt(text, getAlgorithmCipher(null, DEFAULT_CIPHER_ALGORITHM), DEFAULT_CIPHER_ALGORITHM, key);
	}

	public static Cipher getAlgorithmCipher(Provider provider, String cipherAlgorithm)
			throws NoSuchAlgorithmException, NoSuchPaddingException {
		return (provider == null) ? Cipher.getInstance(cipherAlgorithm) : Cipher.getInstance(cipherAlgorithm, provider);
	}
	
    public static byte[] encrypt(byte[] text, Cipher cipher, String cipherAlgorithm, Key key) throws Exception {
		return encrypt(getCheckedEncryptCipher(cipher, cipherAlgorithm, key), key, text);
	}
	
	public static byte[] decrypt(byte[] text, Cipher cipher, String cipherAlgorithm, Key key) throws Exception {
		return decrypt(getCheckedDecryptCipher(cipher, cipherAlgorithm, key), key, text);
	}

	private static Cipher getCheckedEncryptCipher(Cipher cipher, String cipherAlgorithm, Key key) throws Exception {
		cipher = (cipher == null) ? Cipher.getInstance(cipherAlgorithm) : cipher;

		cipher.init(Cipher.ENCRYPT_MODE, key);

		return cipher;
	}
	
	private static Cipher getCheckedDecryptCipher(Cipher cipher, String cipherAlgorithm, Key key) throws Exception {
		cipher = (cipher == null) ? Cipher.getInstance(cipherAlgorithm) : cipher;

		cipher.init(Cipher.DECRYPT_MODE, key);

		return cipher;
	}

	private static byte[] encrypt(Cipher cipher, Key pk, byte[] data) throws Exception {
		int inputLen = data.length;

		ByteArrayOutputStream out = new ByteArrayOutputStream(inputLen);

		try {
			int offSet = 0;

			byte[] cache;

			int i = 0;

			// 对数据分段加密(如果超过117字节)
			while (inputLen - offSet > 0) {
				// 支持超过117字节大小的
				cache = (inputLen - offSet > MAX_ENCRYPT_BLOCK) ? cipher.doFinal(data, offSet,
						MAX_ENCRYPT_BLOCK) : cipher.doFinal(data, offSet, inputLen - offSet);

				out.write(cache, 0, cache.length);

				i++;

				offSet = i * MAX_ENCRYPT_BLOCK;
			}

			return out.toByteArray();
		} finally {
			closeCloseable(out);
		}

	}

	private static byte[] decrypt(Cipher cipher, Key pk, byte[] encryptedData) throws Exception {
		int inputLen = encryptedData.length;

		ByteArrayOutputStream out = new ByteArrayOutputStream(inputLen);

		try {
			int offSet = 0;

			byte[] cache;

			int i = 0;

			// 对数据分段解密(如果超过128字节)
			while (inputLen - offSet > 0) {
				cache = (inputLen - offSet > MAX_DECRYPT_BLOCK) ? cipher.doFinal(encryptedData,
						offSet, MAX_DECRYPT_BLOCK) : cipher.doFinal(encryptedData, offSet, inputLen
						- offSet);

				out.write(cache, 0, cache.length);

				i++;

				offSet = i * MAX_DECRYPT_BLOCK;
			}

			return out.toByteArray();
		} finally {
			closeCloseable(out);
		}
	}

	private static void closeCloseable(Closeable closeable) {
		try {
			if (closeable != null) {
				closeable.close();
			}
		} catch (IOException ioe) {
		}
	}
}

**Comment by bwzhang2011** [comment]
My test class, I found the STOREWAL persist speed is not fast, hope @jankotek  you could leave me more advice to improve that.

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.flume.Event;
import org.apache.flume.event.SimpleEvent;
import org.apache.logging.log4j.flume.appender.BatchEvent;
import org.apache.logging.log4j.flume.appender.mapdb.FlumeMapdbHelper;
import org.mapdb.Engine;
import org.mapdb.Serializer;
import java.util.concurrent.Executors;
import java.util.concurrent.ExecutorService;

public class TestFlumeEvent {

	static ExecutorService execute = Executors.newCachedThreadPool();

	private static Map<String, String> getRandomMap(int count) {
		Map<String, String> headers = new HashMap<String, String>(1);

		headers.put("key:" + count, "value:" + count);

		return headers;
	}

	private static byte[] getRandomValue(int count) {
		String time = "count:" + count + ",at:" + System.nanoTime();

		return time.getBytes();
	}

	public static void testEngine(Engine flumeEgine, Serializer<Event> serializer) {
		int count = 1000;

		SimpleEvent simpleEvent = null;

		long t1 = System.currentTimeMillis();

		List<SimpleEvent> simpleEventList = new ArrayList<SimpleEvent>(count);

		for (int i = 0; i < count; i++) {
			simpleEvent = new SimpleEvent();

			simpleEvent.setHeaders(getRandomMap(count));

			simpleEvent.setBody(getRandomValue(count));

			simpleEventList.add(simpleEvent);
		}

		long t2 = System.currentTimeMillis();

		long[] ids = new long[count];

		for (int i = 0; i < count; i++) {
			ids[i] = FlumeMapdbHelper.persistEvent(flumeEgine, simpleEventList.get(i), serializer);
		}

		long t3 = System.currentTimeMillis();

		BatchEvent batchEvent = FlumeMapdbHelper.getPersistBatchEvent(flumeEgine, ids, serializer);

		long t4 = System.currentTimeMillis();

		FlumeMapdbHelper.deletePersistEvent(flumeEgine, ids, serializer);

		long t5 = System.currentTimeMillis();

		System.out.println("batchEvent:" + batchEvent.getEvents().size());

		System.out.println("batch init cost:" + (t2 - t1) + "ms");

		System.out.println("insert cost:" + (t3 - t2) + "ms, batch read cost:" + (t4 - t3)
				+ "ms, batch delete cost:" + (t5 - t4) + "ms");
	}

	public static void main(String[] args) throws Exception {
		int count = 100;

		final Engine flumeEgine = FlumeMapdbHelper.getTxEngine("./file/test.data");

		final Serializer<Event> serializer = FlumeMapdbHelper.getFlumeEventSerializer(null);

		for (int i = 0; i < count; i++) {
			testEngine(flumeEgine, serializer);
			/*
			execute.execute(new Runnable() {

				@Override
				public void run() {
					testEngine(flumeEgine, serializer);
				}

			});
			*/
		}
	}
}

**Comment by bwzhang2011** [comment]
By the way, if we use executor for multiple accessing the Engine for persist, it will wait for the file completed so such test could not use Thread for testing. I hope @jankotek  you could provide more examples for Engine use cases for sometimes We just want to directly use the persist for insert query update or delete operation.

**Comment by jankotek** [comment]
Cursors (Iterators) on Engine is not possible, since Engine is primitive key-value storage and does not contain any sort of link. If you want to iterate over all records in Engine, checkout compaction code. Modification listeners etc could be implemented by Engine wrappers. 

I think you should store list of records somewhere outside mapdb, perhaps LongLongMap or something similar.

**Comment by bwzhang2011** [comment]
@jankotek, would you mind leaving more message about Engine use cases like I referred as above even through it was key-value way, I don't know about more bout compaction or modification listeners for that, I need your help for some as some testing cases.

**Comment by bwzhang2011** [comment]
@jankotek, by the way, would you mind taking a look at the code of mine for Engine integration ? from my testing, it was slow that while persisting the data. so we need your help for more example of engine and more tuning for that.

**Comment by jankotek** [comment]
Sorry, I am very busy for next 
a few weeks.
