### ISSUE TITLE
ERROR: Caused by java.io.IOException: Zero Header, data corrupted

### ISSUE THREAD

**Issue by uwittygit** [jankotek/mapdb#566]
Hi, 
Version: mapdb-2.0.0-SNAPSHOT.jar, built from latest master branch.
ubuntu14.04 64bit, java8

I met with a bug: 
I was building a huge HtreeMap, and then commit it to the disk,  the bug happens when I try to get the HtreeMap size after HTreeMap was commited.
"ERROR: Caused by java.io.IOException: Zero Header, data corrupted"

besides, if the HTreeMap was smaller, the bug will not happen !!!!!!
My test is: generated mapDB file  2.5G is ok, 4.6G bug happened.

/* ================ code =====================*/
Main Thread:
db = DBMaker.fileDB(new File(mapdbPath))
                .cacheSize(cacheSize)
                .cacheLRUEnable()
                .cacheHashTableEnable()
                .make();
        sentenceIndexer = db.hashMap("sentenceIndexer");
        sentenceIndexer.clear();

///  build sentenceIndexer in another single building thread
//// wait for the building thread end job
/// commit to file
        System.out.println("binarizing to file " + mapdbPath + "...");
        db.commit();
        System.out.printf("Done!! total sentences:%d\n", sentenceIndexer.size()); ////// bug happens here
/* ================ code end ==================*/

backtrace:
ERROR: Caused by java.io.IOException: Zero Header, data corrupted:
org.mapdb.SerializerBase$19.deserialize(SerializerBase.java:432)
org.mapdb.SerializerBase.deserialize(SerializerBase.java:1427)
org.mapdb.SerializerBase.deserialize(SerializerBase.java:1415)
org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:158)
org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:132)
org.mapdb.Store.deserialize(Store.java:415)
org.mapdb.StoreWAL.get2(StoreWAL.java:705)
org.mapdb.Store.get(Store.java:253)
org.mapdb.HTreeMap.recursiveDirCount(HTreeMap.java:530)
org.mapdb.HTreeMap.recursiveDirCount(HTreeMap.java:525)
org.mapdb.HTreeMap.recursiveDirCount(HTreeMap.java:525)
org.mapdb.HTreeMap.sizeLong(HTreeMap.java:501)
org.mapdb.HTreeMap.size(HTreeMap.java:472)
cn.smartnlp.semantic.TightSemantics.makeSemantics(TightSemantics.java:342)
cn.smartnlp.semantic.TightSemanticsMaker.run(TightSemanticsMaker.java:55)
fig.exec.Execution.runWithObjArray(Unknown Source)
fig.exec.Execution.run(Unknown Source)
cn.smartnlp.semantic.TightSemanticsMaker.main(TightSemanticsMaker.java:44)
2 errors, 0 warnings

**Comment by jankotek** [comment]
There was issue with random data corruption. I believe it is fixed in 2.0-beta8
