### ISSUE TITLE
mapdb file load too slow

### ISSUE THREAD

**Issue by uwittygit** [jankotek/mapdb#568]
Version: mapdb-2.0.0-SNAPSHOT.jar, built from latest master branch.
ubuntu14.04 64bit, java8
Hi
I built a mapdb file from server1, and then copy the file to server2.
when server2 loaded the file for the first time, it cost much time. very long......
but if the file was loaded, it will be much faster if server2 load the file for the second time. 
I do believe that it was doing some initializing when loaded for the first time, in server2.
So, here is question:
How should I build a file that will be loaded fast, even for the first time.
The code is as followed:

///=========== build code ===============
db = DBMaker.fileDB(new File(modelPath))
                    .cacheSize(cacheSize)
                    .allocateStartSize(StartSize)
                    .allocateIncrement(increment)
                    .cacheLRUEnable()
                    .make();
//// many variables 
semanticIds = db.hashMap("semanticIds");
sentenceIds = db.hashMap("sentenceIds");
sent2semIndexer = db.hashMap("sent2semIndexer");
....................
///// building process
///commit
db.commit();
//============= code end =============

The generated file looks like this:
chengiant@server-150:~/robot$ ll -h ./models/fastbeam/common/
total 4.1G
drwxrwxr-x 2 chengiant chengiant 4.0K Aug 31 17:07 ./
drwxrwxr-x 4 chengiant chengiant 4.0K Aug 23 18:48 ../
-rw-rw-r-- 1 chengiant chengiant 1.0G Aug 31 15:56 commonModel.dat
-rw-rw-r-- 1 chengiant chengiant  33K Aug 31 15:57 commonModel.dat.wal.0
-rw-rw-r-- 1 chengiant chengiant  33K Aug 31 15:57 commonModel.dat.wal.1
-rw-rw-r-- 1 chengiant chengiant 3.1G Aug 31 17:07 commonModel.dat.wal.2
-rw-rw-r-- 1 chengiant chengiant   16 Aug 31 17:07 commonModel.dat.wal.3

///
when load in another sever it costs very long time: 30 minutes

**Comment by jankotek** [comment]
You should also call db.close(). The 
wal.N files means that write ahead 
log was not fully synced to disk, 
db.close() will do that.

**Comment by uwittygit** [comment]
got it
