### ISSUE TITLE
Tuple issue in BTreeMap with Composite Key

### ISSUE THREAD

**Issue by sumit784** [jankotek/mapdb#569]
I was looking into the example of creating a composite key in BTreeMap, where you have used Fun.tuple3. 

But, then in latest version 2.x , it seems like the tuple are being replaced by object[], but you do not have any implementation for it. Its still in your to-do list. 

Any ETA on this completion. we are planning to implement MapDB in our project and usage of composite keys is critical. 

### Also, one suggestion for composite keys :- 
Will / Can there is the functionality of "Partial searching" of keys. Something similar to a "LIKE" operator in datbase sql. So that I can search wide range based on partial search, This way I can totally depend on MapDB and need not to go back to DB for partial search or LIKE queries.  It would be a great addition to the composite keys.

**Comment by jankotek** [comment]
Example is now fixed, you will need latest 2.0 snapshot or 2.0 beta7 (once it is released) to run this.

You can use `BTreeMap.submap()`. Lower limit is missing value (ie shorter strings are smaller than bigger). 

Upper limit is `null`, null is treated as positive infinity and anything else is smaller than null. Nulls are only allowed as parameters for queries, they can not be stored in database.

**Comment by sumit784** [comment]
Hi Jan, 

Thanks for responding. Any expected Date for the release of this new version 2.0 beta7, you have mentioned ?

How long shall we wait for it.
