### ISSUE TITLE
NullPointerException in SerializerPojo when serializing POJOs on JRockit

### ISSUE THREAD

**Issue by gpeche** [jankotek/mapdb#572]
Several JRockit implementations of Java 6 have a caching bug where `ObjectStreamClass.lookup(...)` may return a non-null value when invoked with a non-`Serializable` class. This makes `SerializerPojo` throw a NPE when looping in `makeFieldsForClass(...)`, as (according to the specification) the loop expects `ObjectStreamClass.lookup(Object.class) == null`. Changing the two invocations to `ObjectStreamClass.lookup(...)` in that method to invocations to the following:

```java
    private static ObjectStreamClass fixForLookup(Class<?> c) {
        ObjectStreamClass result = null;
        if (Serializable.class.isAssignableFrom(c)) {
            result = ObjectStreamClass.lookup(c);
        }
        return result;
    }
```

seems to "sort-of solve" the issue (though I suspect the stream format will not be spec-compliant). I have tested this with JRockit R28.2.7, which is the latest publicly available JRockit release.

Ideally this should be corrected in JRockit itself and not worked around in MapDB. The problem is that JRockit has been discontinued after Java 6, and getting patches for it is not straightforward at all. Using MapDB in Jrockit is very uncomfortable without the "fix": either you restrict yourself to types with built-in serializer implementations in MapDB, or you provide custom serializers for all your POJOs. You cannot rely on `SerializerPojo` because of this problem with `ObjectStreamClass.lookup(...)`.

**Comment by gpeche** [comment]
A link describing the JRockit issue:
https://community.oracle.com/thread/2298350

**Comment by jankotek** [comment]
I will look into it, thanks for raising it.

**Comment by jankotek** [comment]
Not going to fix it, sorry. 

I feel restricting lookup to `Serializable` classes might be too dangerous and affect other cases.

**Comment by gpeche** [comment]
Thank you anyway, I see now a warning is logged, that bug is a bit nasty to
find out...

2015-09-30 12:13 GMT+02:00 Jan Kotek <notifications@github.com>:
