### ISSUE TITLE
ArrayIndexOutOfBoundsException on remove

### ISSUE THREAD

**Issue by shabanovd** [jankotek/mapdb#575]
In single transaction batch processing of huge number of operations lead to exception on remove (reproducible)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
    at org.mapdb.BTreeMap.remove2(BTreeMap.java:977)
    at org.mapdb.BTreeMap.remove(BTreeMap.java:1141)

MapDB is 1.0.8. It happen on new created map. At time it fail data file have ~5Gb size.

**Comment by shabanovd** [comment]
how to debug to provide more information?

**Comment by jankotek** [comment]
I would probably recommend to try 2.0-beta6 at this point.

**Comment by shabanovd** [comment]
Yeap, that was one of thoughts - do not spend time on 1.0;
How stable 2.0-beta6? As I remember storage format was not freeze yet, right?
