### ISSUE TITLE
Use WAL for memoryDB recovery?

### ISSUE THREAD

**Issue by velvia** [jankotek/mapdb#576]
Hi folks,

Sorry, I didn't see a mailing list for MapDB, I just have a beginners' question.

I'd like to use MapDB as a memtable of sorts - to store intermediate data in memory before forwarding to another process.  The data does not need to be persisted, except for crash recovery reasons -- i.e. if the app dies, it would be nice to recover the current state of intermediate data from disk.

Initially I thought of using WAL + memoryDB.   However, I cannot find a way to recover the current in-memory state of MapDB from the WAL, it seems it is not designed for this purpose.

I can use a mmap'ed file + WAL, but in this case isn't the WAL redundant?  And the setup seems a little bit heavyweight.

What would you guys recommend?

Thanks.

**Comment by shabanovd** [comment]
Hi,

On Tue, Sep 8, 2015 at 2:29 AM, Evan Chan <notifications@github.com> wrote:

> I'd like to use MapDB as a memtable of sorts - to store intermediate data
> in memory before forwarding to another process. The data does not need to
> be persisted, except for crash recovery reasons -- i.e. if the app dies, it
> would be nice to recover the current state of intermediate data from disk.
>
By your description you need persisted, because other way recovery will not
be possible. Use asyncWriteFlushDelay with value close to your cache
lifecycle.

Initially I thought of using WAL + memoryDB. However, I cannot find a way
> to recover the current in-memory state of MapDB from the WAL, it seems it
> is not designed for this purpose.
>
> I can use a mmap'ed file + WAL, but in this case isn't the WAL redundant?
> And the setup seems a little bit heavyweight.
>
> What would you guys recommend?
>
-- 
Dmitriy Shabanov

**Comment by jankotek** [comment]
MapDB has backup option, backup can be stored on disk, while main store is in memory. See this example:

https://github.com/jankotek/mapdb/blob/master/src/test/java/examples/Backup.java
