### ISSUE TITLE
TxMaker and transactions while having cache

### ISSUE THREAD

**Issue by ZenoFuturista** [jankotek/mapdb#578]
Hello all,
I got confused while experimenting with MapDB (2.0) transaction system. TxMaker underlying engine could not have any cache, therefore my initial intention was having DB with some cache for fast data reading while using transaction system on engine of this store for writing (to be able to discover/solve concurrent conflicts). So I tried to open regular DB and then instantiate TxMaker with its engine, this of course won't work, because snapshots of this engine are read only, so this is not the right approach. I've tried several other methods (which are not worth to be mentioned here :)), again without success, so I think I miss something or this is just how things work and nothing could be done about it - either DB with cache or cacheless TxMaker over one store/engine. Well, I hope that the description of my intention is clear and needs no source attachments. 
I will be glad for any informations regarding this case.
Thanks in advance and have a nice day.
Zeno

**Comment by jankotek** [comment]
TxMaker does not work with instance cache. This bug was fixed recently in 2.0-beta8
