### ISSUE TITLE
Concurrency issue with B-tree `containsKey` right after parallel `put`

### ISSUE THREAD

**Issue by pstutz** [jankotek/mapdb#581]
Hi Jan,

I'm trying to use MapDB 2.0-beta6 for my project, but ran into a concurrency issue. The Scala code below inserts entries in parallel into an in-memory B-tree with `put` and immediately checks that an entry with that key exists with `containsKey`. It crashes with errors like `assertion failed: Key 52500 of entry 510 that was just added is not contained.`:
```scala
object MapDbConcurrencyIssue extends App {
  val db = org.mapdb.DBMaker.memoryDB.make
  val map = db.treeMap[Int, String]("int2String")
  val entries = 1000000
  val strings = (1 to entries).map(_.toString)
  strings.par.foreach { s =>
    val id = s.hashCode
    map.put(id, s)
    assert(map.containsKey(id), s"Key $id of entry $s that was just added is not contained.")
  }
}
```

The same code without using the parallel collection runs fine. The documentation says that [`All classes in MapDB are thread-safe`](http://www.mapdb.org/doc/concurrency.html). Do I have to configure something differently or is this a bug?

Thank you very much for your help,
Philip

**Comment by jankotek** [comment]
`BTreeMap` should be thread-safe, but I am afraid you found a bug.

I verified that problem is in `BTreeMap` itself and not underlying `Store`.  Also version 1.0 does not have this problem which is good starting point.

There were following changes in 2.0, which could cause this problem:

1) Linked Node handling changed. Under concurrent load nodes are split and node-link handles this transition. 

2) Locking changed from overlapping locks to non-overlapping locking. 

3) Specialized Key Serializers were introduced. Some new code could be outside locks.

**Comment by jankotek** [comment]
Java test case

```

    @Test public void issue581() throws InterruptedException {
        DB db = DBMaker.heapDB().make();
        final Map map = db.treeMap("map");
        int entries = 1000000;

        ExecutorService exec = Executors.newFixedThreadPool(20);
        final AtomicReference<Error> ex = new AtomicReference<Error>(null);
        for(int i=0;i<entries;i++){
            final String val = ""+i;
            final int id = val.hashCode();
            exec.submit(new Runnable() {
                @Override
                public void run() {
                    map.put(id, val);
                    if(!map.containsKey(id))
                        ex.set(new AssertionError("does not contain key:"+id+" val:"+val));
                    }
            });
        }

        exec.shutdown();
        while(!exec.awaitTermination(100, TimeUnit.MILLISECONDS)){
            Error e = ex.get();
            if(e!=null)
                throw e;
        }
    }
```

**Comment by pstutz** [comment]
Thank you very much!
