### ISSUE TITLE
NullPointerException in BTreeKeySerializer.STRING on 1.0.8

### ISSUE THREAD

**Issue by mattwigway** [jankotek/mapdb#582]
I'm seeing NullPointerExceptions in BTreeKeySerializer.STRING on MapDB 1.0.8, and I've written [a trivial test case to reproduce](https://gist.github.com/mattwigway/230b9589be891a95e7eb):

```
Matthews-MacBook-Pro:mapdb-issue matthewc$ javac -cp ~/.m2/repository/org/mapdb/mapdb/1.0.8/mapdb-1.0.8.jar StringNPE.java 
Note: StringNPE.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Matthews-MacBook-Pro:mapdb-issue matthewc$ java -cp ~/.m2/repository/org/mapdb/mapdb/1.0.8/mapdb-1.0.8.jar:. StringNPE
Exception in thread "main" java.lang.NullPointerException
	at org.mapdb.BTreeKeySerializer$3.serialize(BTreeKeySerializer.java:183)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:385)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreWAL.put(StoreWAL.java:200)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.Pump.buildTreeMap(Pump.java:470)
	at org.mapdb.DB.createTreeMap(DB.java:875)
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:661)
	at StringNPE.main(StringNPE.java:29)
```

At first bluster, it looks like `keys[start]` in the serialize function is null. Some of the serializers iterate starting at `start + 1` and some (including the string serializer) start at `start`.

This does appear to be an issue with the string serializer as removing the line that uses the string serializer makes the problem go away.

**Comment by mattwigway** [comment]
For what it's worth, I'm using Oracle Java 1.8.0_60 on OS X Yosemite.

**Comment by shabanovd** [comment]
Interesting fact that issue is stable and always fail when
`start = 1; end = 12; keys = [null, null, job_geomerror.1485, job_geomerror.1982,...`

**Comment by mattwigway** [comment]
Right, this doesn't happen with all sets of IDs. Should have mentioned that before.

**Comment by atoulme** [comment]
I adapted your test case to Java 6 style and added it as a unit test to this branch. Sorry, I tried to see if I could fix the issue and I'm not familiar enough with the code to understand the intricacies.
It does look like (pure guess) that the class Pump around line 452 is adding an additional null value.

https://github.com/atoulme/mapdb/tree/issue582-1.0

**Comment by bhavin6431** [comment]
I have also experienced the similar issue and it appears to be related to number of records pumped. In following modified test case from original test case, if i use counter value 

< 6048 Works fine
< 6049 Doesn't work
< 6070 Doesn't work
< 6072 Doesn't work
< 6073 Works fine

Hope that will help troubleshoot a bit further.

public class Issue582Test {
    @Test
    public void test(){
        DB db = DBMaker.newTempFileDB().make();
        Iterator<String> source = new Iterator<String>() {
        	int counter;
			@Override
			public boolean hasNext() {				
				return counter < 6072;
			}
			@Override
			public String next() {
				counter++;
				return "" + counter;
			}
			@Override
			public void remove() {
				// TODO Auto-generated method stub			
			}        	
		};
		db.createTreeSet("test").pumpPresort(1000000).pumpSource(source)        
        .serializer(BTreeKeySerializer.STRING)
        .make();
    }    
}

**Comment by jankotek** [comment]
I was very busy with bugfixing until recently, will have a look soon.

**Comment by mattwigway** [comment]
Thanks!
		
        
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Sun, 01 Nov 2015 05:21:14 -0500  notifications@github.com  wrote ----I was very busy with bugfixing until recently, will have a look soon.

**Comment by jankotek** [comment]
Not going to fix, its too complex and I could break something else. Sorry.

**Comment by Doccrazy** [comment]
I was able to fix the issue locally with the following patch. It modifies the treemap pump code to not split a full node if there are no more source items, because that would leave a new, empty node behind.
```diff
--- a/src/main/java/org/mapdb/Pump.java
+++ b/src/main/java/org/mapdb/Pump.java
@@ -412,7 +412,7 @@
 
             //check node sizes and split them if needed
             for(int i=0;i<dirKeys.size();i++){
-                if(dirKeys.get(i).size()<nload) break;
+                if(dirKeys.get(i).size()<nload || !source.hasNext()) break;
                 //tree node too big so write it down and start new one
                 Collections.reverse(dirKeys.get(i));
                 Collections.reverse(dirRecids.get(i));
```
After patching, the posted tests will work. 
I am however not submitting a pull request because I'm unsure if this is correct or causes other things to break. Tbh I don't fully understand the code.
