### ISSUE TITLE
make null value in TreeMap configurable 

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#585]
First - thanks for adding support for nulls. That's great for avoiding unnecessary waste of space/time creating and managing empty placeholder objects.

However, I am not sure what has motivated hardcoding null value to +infinity. In many use cases we care about storage/iteration order and would like to see the NULL value first to possibly do something immediately after encountering it - vs. having to run through the rest of values to the end.

**Proposal**: Add a configuration option per TreeMap that would fix null to -infinity or alternatively make it equivalent to any arbitrary object, if appropriate (e.g. ```Integer.valueOf(0)```)

**Comment by jankotek** [comment]
`BTreeMap` does not suppurt null keys or values. `null` can be only used in Composite Key Range Queries to supplement +infinity. `null` will never be returned by actual iterator or map (unless value does not exist).

**Comment by dmk23** [comment]
Yes, I was referring to nulls in composit keys, sorry for confusion

Could you reconsider / reopen the issue?

**Comment by jankotek** [comment]
But the composite keys do not allow nulls.

**Comment by dmk23** [comment]
Your example right here shows null used to represent "positive infinity"
https://github.com/jankotek/mapdb/blob/master/src/test/java/examples/TreeMap_Composite_Key.java#L69

Yes, now I see there is a way to do "negative infinity" by shorter array, but I think just overriding the "meaning" of a null value to anything would provide an advantage

Having to use shorter arrays to enforce ordering unnecessarily complicates the client code vs. using the same fixed size with different ("special") values...

**Comment by jankotek** [comment]
That array only serves as query parameter (upper limit). It is not stored in map.

**Comment by dmk23** [comment]
Thanks for clarifying.

Is there a reason MapDB cannot fully support nulls in composite keys? Right now we are forced to create fake "empty" objects wherever necessary and when small objects get deserialized they are needlessly duplicated in memory. To that point, is there a way to enforce use of interned strings or use of ```Integer.valueOf```, ```Short.valueOf```, etc for deserializing keys to minimize memory footprint?

Generally seems to be reading composite keys might result in greater than necessary memory use...

**Comment by jankotek** [comment]
I could reintroduce `Fun.HI` as +positivity, but I prefer not to.

If you are dealing with Integer and Shorts in composite keys, the best way is to byte pack them together into Long.

**Comment by dmk23** [comment]
Looks like my long/detailed comment got lost after the rename.

Did you by any chance receive it by email?

**Comment by jankotek** [comment]
I think I have not got email. But I am not going to fix this. 

This is a corner case, I could introduce alternative such as Fun.HI, but non-null comparasion has performance overhead which would affect all operations, not just ranges.
