### ISSUE TITLE
TreeMap Composite Key - Range query is not working.

### ISSUE THREAD

**Issue by ManishChaurajaWellogicOhum** [jankotek/mapdb#586]
We have Composite key map Like - 
ConcurrentNavigableMap<Object[], SOME_OBJECT> map = db
				.treeMapCreate("test").keySerializer(keySerializer).make();

Where the map's key is - 
Object[] compositeKeys = new Object[] { prodBundleId, categoryId, productCount, discount, bestPrice };

Requirement - I want all the map which has discount between 0 to 5

I have tried following ways - 
1) discountMap = map.subMap(
					new Object[] { null, null, null, 0.0, null },
					new Object[] { null, null, null, 5.0, null });

2) discountMap = map.subMap(
					new Object[] { 0, 0, 0, 0.0, 0.0},
					new Object[] { null, null, null, 5.0, null });

but nothing works. Please suggest

**Comment by jankotek** [comment]
You need multiple loops, keys are hierarchically sorted. So iterate throw all:  prodBundleId, categoryId, productCount and perform range query on each.
