### ISSUE TITLE
Query Layer for Object Graph 

### ISSUE THREAD

**Issue by crudbug** [jankotek/mapdb#593]
It will be very useful to query mapdb object graph with something similar to SQL. 

Is there a query layer for mapdb planned. 

related:
http://stackoverflow.com/questions/93417/how-do-you-query-object-collections-in-java-criteria-sql-like

**Comment by crudbug** [comment]
Need to explore more : https://github.com/npgall/cqengine

**Comment by fshamim** [comment]
you can convert the maps into list and then can perform simple queries using RxJava filter operators. You can do, almost all of the SQL queries using RxJava.

**Comment by crudbug** [comment]
Thanks for #Rxjava direction.

**Comment by jankotek** [comment]
MapDB is not really an object database and I have no plan to go that direction. Too complicated and there is already some competition. 

But I have plan to make native Graph Database implementation. In that case the Object Graph could be implemented on top of that.

**Comment by crudbug** [comment]
True, OrientDB has taken that approach with mutli-model solution.

**Comment by code4passion** [comment]
ubsubscribe

On Tue, Oct 6, 2015 at 11:01 AM, Alan Kash <notifications@github.com> wrote:

> True, OrientDB has taken that approach with mutli-model solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jankotek/mapdb/issues/593#issuecomment-145947412>.
>



-- 
Regards,
Damodar Shetyo

**Comment by code4passion** [comment]
unsubscribe

On Sat, Oct 10, 2015 at 4:50 PM, akshay shetye <akshay.shetye@gmail.com>
wrote:

> ubsubscribe
>
> On Tue, Oct 6, 2015 at 11:01 AM, Alan Kash <notifications@github.com>
> wrote:
>
>> True, OrientDB has taken that approach with mutli-model solution.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jankotek/mapdb/issues/593#issuecomment-145947412>.
>>
>
>
>
> --
> Regards,
> Damodar Shetyo
>



-- 
Regards,
Damodar Shetyo
