### ISSUE TITLE
Stop using IOError

### ISSUE THREAD

**Issue by stephenc** [jankotek/mapdb#596]
The general concept of exceptions in Java is that exceptions that extend from Error are not meant to be recoverable from.

I get the transformation of IOException from a checked exception, but migrating to an Error is not a good idea. A better choice would be to migrate to a subclass of RuntimeException if you want to avoid using checked exceptions... otherwise all the other code that follows the pattern:

```
try {
   ...
} catch (RuntimeException e) {
  ...
} catch (Exception e) {
  ...
} catch (Error e) {
  // not supposed to do anything with Errors
  throw e;
} catch (Throwable e) {
  ...
}
```

(A pattern that is often used in e.g. `Callable` decorators, etc) will be somewhat surprised by the propagated `IOError`)

**Comment by lmprice** [comment]
I second this; I'd like to see a better exception hierarchy. It's difficult to diagnose problems with the database when everything throws an IOError.

**Comment by jankotek** [comment]
Already done in 2.0:

https://github.com/jankotek/mapdb/blob/master/src/main/java/org/mapdb/DBException.java
