### ISSUE TITLE
Problem with Pump.backup

### ISSUE THREAD

**Issue by chanderr2** [jankotek/mapdb#609]
While taking a backup, the entire content is not getting backed-up. 
The following code fragment results in a) the backup not taking a full snapshot of committed data, and b) a nullpointerexception after the restore because there is no data to restore.

        File dbFile = new File("./mapdb.dat");
        DB db = DBMaker.fileDB(dbFile)
                .make();

        ConcurrentMap<Long,String> map = db.hashMap("collectionName");
        for(long i = 0; i < 2; i++)
                map.put(i, "Num_" + i);
        db.commit();

        File backupFile = new File("./backup.dat");
        Pump.backupFull(db, new FileOutputStream(backupFile));
        db.close();

        DB db2 = Pump.backupFullRestore(
                DBMaker.memoryDB().transactionDisable(),
                new FileInputStream(backupFile));
        ConcurrentMap<Long,String> m = db2.hashMap("collectionName");
        System.out.println(m);

**Comment by jankotek** [comment]
Not going to fix. Backup code is probably even more broken and i have no time to verify it.
