### ISSUE TITLE
Stack and Queue support ?

### ISSUE THREAD

**Issue by eix128** [jankotek/mapdb#61]
Hello , i ve searched on internet persistent queue and stack for my java app client but i could not see any good solution except you.But you dont have support directly for queue and stack like collections.

it will be good if you add ;
        final DB db = DBMaker.newFileDB(new File("testdb")).closeOnJvmShutdown().make();

```
    Queue queue = db.createQueue
    //queue.enqueue and queue.dequeue poll peek offer
    Stack stack = db.createStack
    //push and pop
```

**Comment by asafm** [comment]
If the queue implementation is not sequentially write to disk (like in BigQueue) won't this hinder performance?
