### ISSUE TITLE
Speed vs. Crash recovery

### ISSUE THREAD

**Issue by bubblefoil** [jankotek/mapdb#617]
Hi, I would like to ask for an advice on persistent storage configuration.
Can I make use of the mmap performance improvement without risking loosing all changes whenever JVM crashes? With transactions enabled, all the wal files only get flushed when application is restarted normally. Otherwise they I ignored and changes they contain are lost. With transactions disabled, I risk corrupting the DB file when JVM exits unexpectedly, which did happen.

**Comment by jankotek** [comment]
MapDB has crash resistant write ahead log. Disk sync is slow.

**Comment by bubblefoil** [comment]
How can I restore data from the wal in case of improper JVM shutdown?
With following setting, all changes since the application start were lost after a crash.
DBMaker.fileDB(new File(dbPath))
				.compressionEnable()
				.asyncWriteEnable()
				.allocateIncrement(10)
				.asyncWriteQueueSize(5000)
				.cacheHashTableEnable(2000000)
				.fileMmapEnable()
				.fileMmapCleanerHackEnable()
				.closeOnJvmShutdown()
				.make();

**Comment by jankotek** [comment]
WAL will be replayed next time 
storage is opened.
I think you need to call commit 
sometimes
