### ISSUE TITLE
Dependency not being resolved in sbt

### ISSUE THREAD

**Issue by CatiaFerreira6** [jankotek/mapdb#619]
Hi,

Since about 3 hours ago our sbt dependency
`"org.mapdb" % "mapdb" % "2.0.0-SNAPSHOT"`

stopped working can you help us solve this issue?

Here is the full sbt log in case it helps:

[warn] 	module not found: org.mapdb#mapdb;2.0.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/sofia/.ivy2/local/org.mapdb/mapdb/2.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.mapdb/mapdb/2.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== SonatypeReleases: tried
[warn]   http://oss.sonatype.org/content/repositories/releases/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom
[warn] ==== Jasper Reports Third Party: tried
[warn]   http://jaspersoft.artifactoryonline.com/jaspersoft/third-party-ce-artifacts/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom
[warn] ==== Moquette: tried
[warn]   http://dl.bintray.com/andsel/maven/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom
[warn] ==== Eclipse Paho: tried
[warn]   https://repo.eclipse.org/content/repositories/paho-releases/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom
[warn] ==== Sonatype Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-20151029.110527-139.pom
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/mapdb/mapdb/2.0.0-SNAPSHOT/mapdb-2.0.0-SNAPSHOT.pom

I would really appreciate your help =)

**Comment by jankotek** [comment]
Repo seems fine. Perhaps it was just server glitch.
