### ISSUE TITLE
temp DB files not deleted after JVM shutdown

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#621]
I am creating temporary maps using ```DBMaker.tempTreeMap()```. According to the intent of DBMaker code the files are supposed to be removed after DB close or JVM shutdown. However after a shutdown using ```System.exit(0)``` the files still remain in the temp directory.

Additionally, I'd like to have ability to customize the temp file naming. Including the revealing prefix ```mapdb``` into the file name may not always be appropriate in some environments.

The problem was found in 2.0-beta8. Related issue: https://github.com/jankotek/mapdb/issues/120

**Comment by dmk23** [comment]
I tried to prototype some changes to temp file code (e.g. changing temp file suffix/prefix) by copying the code of ```public static <K,V> BTreeMap<K,V> tempTreeMap()```. Surprisingly I got the following error: ```closeEngine() has protected access in org.mapdb.DB.BTreeMapMaker```

Is there a reason why ```closeEngine()``` is not public?

**Comment by BarakBurger** [comment]
I am facing the same problem with version 2.0 beta 10 (Happens also on 2.0 beta 9)
in previous version of mapdb version 1.07 file has been deleted successfully.

**Comment by dmk23** [comment]
@BarakBurger : Thanks for confirming the issue

I have a few more reasons to report for making ```closeEngine()``` public. Basic ```tempTreeMap()``` is not suitable for generating temp maps with custom serializers. Therefore it is necessary to make all the calls used to make the standard temp map available to the client code as well...

@jankotek : I have another question re: maps backed by temp files. To what extent do you believe ```asyncWriteEnable``` and ```asyncWriteFlushDelay``` may or may not be helpful here? I understand temp files are supposed to be a lot faster than regular ones given how OS manages them, but I suppose async batching may still make a difference. It would be helpful to do an official benchmark...

**Comment by BarakBurger** [comment]
If that's helps solving the problem I'm using this way to create DBMaker. Make();



		return DBMaker.tempFileDB().closeOnJvmShutdown()
                .fileMmapEnable()
                .deleteFilesAfterClose()
                .cacheHashTableEnable()
                .fileMmapEnable()
		.cacheSize(cacheSize)
                .transactionDisable().make();

**Comment by jankotek** [comment]
Will have a look

**Comment by sysoev-a** [comment]
I have the same problem, as described above, on 2.0-beta12.
However, I managed to find a workaround. I use the following code:
try (final DB db = DBMaker.tempFileDB().deleteFilesAfterClose().closeOnJvmShutdown().make();
final HTreeMap\<String,String\> index = db.hashMapCreate("temp").make()) {
...
}
and the temporary file is deleted.

The problem seems to be something like that: DB class is responsible for deleting file on close,
however its close() method is not invoked.
DB instance is not passed to instantiated HTreeMap (or other class), thus it becomes lost without being correctly closed.

**Comment by jankotek** [comment]
Merged
