### ISSUE TITLE
shared vs. separate DB files

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#622]
When working with multiple maps a decision needs to be made about whether to place them into the same DB file or create separate files for each map.

I'm wondering about the performance implications of this choice. Would having multiple maps increase file fragmentation and possibly degrade the performance? Is there any benchmark data (or even anecdotal evidence) of multiple maps in a file being a good or bad thing?

**Comment by jankotek** [comment]
You will have to call db.compact() sometimes in any case after updates.

In general single file is preffered if you need single transaction across multiple maps. 

Separate files are recommended when you want to delete content of map quickly.

**Comment by dmk23** [comment]
Thanks. Quick follow-on question.

Would compaction (in the latest 2.0) actually remove any empty leaf nodes (and ideally merge the sparse ones)? I have an interesting case with a BTreeSet used to hold the "last updated" timestamp-based index of records that are frequently refreshed. This is supposed to quickly result in the the head of the BTreeSet being completely empty as records get refreshed and timestamps updated.

Would MapDB compact remove those dead nodes or they'll continue accumulating indefinitely? If not I think at least the empty node removal should be implemented and hopefully merger of sparse nodes...

**Comment by jankotek** [comment]
Compaction will not remove empty leafs. There is BTree level compaction, but that 
is not imlemented yet. Best way is to move BTreeMap content into new one with 
Data Pump. 

Another option is to implement single-threaded mode for BTreeMap, which would 
remove empty leafs on the fly. That will be in 2.1

Jan

On Monday, November 09, 2015 02:58:11 dmk23 wrote:


Thanks. Quick follow-on question. 
Would compaction (in the latest 2.0) actually remove any empty leaf nodes (and 
ideally merge the sparse ones)? I have an interesting case with a BTreeSet used to 
hold the "last updated" timestamp-based index of records that are frequently 
refreshed. This is supposed to quickly result in the the head of the BTreeSet being 
completely empty as records get refreshed and timestamps updated. 
Would MapDB compact remove those dead nodes or they'll continue accumulating 
indefinitely? If not I think at least the empty node removal should be implemented 
and hopefully merger of sparse nodes... 
—Reply to this email directly or view it on GitHub[1].[2]




--------
[1] https://github.com/jankotek/mapdb/issues/622#issuecomment-155028335
[2] 
https://github.com/notifications/beacon/AAV6bSnsvu9AxkwQFFaDoNdIkIMzvxT2ks5
pEHPDgaJpZM4Gd2Im.gif

**Comment by dmk23** [comment]
Any chance for this pump export/import to be automated inside of MapDB? It just seems like tremendous waste to have to do a custom re-code of this process for every DB/schema ...

**Comment by jankotek** [comment]
@dmk23  I am planing both (BTree background compaction and BTree reimport) for 2.1

**Comment by dmk23** [comment]
Sounds great! Any chance for this to get backported into 2.0.x branch?

Format-changing upgrades seem to be extremely painful in production (unless handled automatically) and at least BTree reimport seems to be feasible to implement outside of the core engine.

Could it be suitable for a 2.0.x backport without having to make disruptive changes?

**Comment by jankotek** [comment]
There is not going to be backport. 2.1 will get long term support once its out. It will be storage/api compatible with 2.0

**Comment by dmk23** [comment]
Thanks, this sounds just as good.

Just curious if storage/api would remain the same, why would it be 2.1 instead of 2.0.x ?

**Comment by jankotek** [comment]
@dmk23 2.0 is optimized on stability, but performance is not best. I prefer to get it right and LTS optimized version.
