### ISSUE TITLE
huge table memory overflow

### ISSUE THREAD

**Issue by smartnlp** [jankotek/mapdb#643]
Hi, I have a model to make, and the model was to be stored in mapdb
Version: mapdb2.0 SnapShot
program logic:
      source data -----> some algorithm ---> model
(1) source data: prepared data in mapdb format ,11G, 10,000,000 keys in HashTree, 
          init code:
           db = DBMaker.fileDB(new File(mapdbPath))
                .cacheSize(cacheSize)  ///// cacheSize = 100000
                .cacheLRUEnable()
                .cacheHashTableEnable()
                .make();

(2) model: mapdb format, about 40G (never success)
     model feature: huge keys, random fectch and put keys 
(3) Server parameters: 56G RAM

My problems:
    I tried many method to initiate  mapdb which is supposed to store the model
   (1). model initial code:
          db = DBMaker.fileDB(new File(modelPath))
                    .cacheSize(cacheSize)            ///cacheSize = 100000
                    .allocateStartSize(StartSize)    //// StartSize = 1* 1024 * 1024 * 1024; // default 1G
                    .allocateIncrement(increment) /// increment = 64 * 1024 * 1024;     // default 64M
                    .cacheLRUEnable()
                    .make();
      phenomenon：
　　the program processed 5,000,000 source data, and the memory overflowed. and I noticed that the Mapdb never store any data into the disk.
     (2) so I decided to commit data into the disk manually  every time the program processed 500,000 source data
         if (Math.floorMod(count, 100) == 0) {
                    System.out.printf("%c ============>  processed  sentences: %d ================", 13, count);
                    if (Math.floorMod(count, 500000) == 0) {
                        db.commit();
                        System.gc();
                    }
                }
      phenomenon：
          every time the program continued processing source data after db.commit(), the memory Soar alot, very fast. the memory overflowed after 1,000,000 source data was processed.
    (3) I tried another way to initiate model mapdb, and commit every 500,000 source data. Still,the memory overflowed after 1,000,000 source data was processed.
          db =  DBMaker.fileDB(new File(modelPath))
                    .cacheSize(cacheSize)
                    .cacheLRUEnable()
                    .cacheHashTableEnable()
                    .make();
what should I do ?

**Comment by smartnlp** [comment]
I do wonder,  while writting, if  mapdb hits it cache size, but the system has sufficient memory, what will happen？ will mapdb enlarge the cache size automatically or store the surpass data into the disk?

**Comment by jankotek** [comment]
MapDB stores uncommited data in-memory. So disable transactions for import.

Jan

On Thursday, December 03, 2015 17:52:55 奇智 wrote:


Hi, I have a model to make, and the model was to be stored in mapdbprogram 
logic:source data -----> some algorithm ---> model(1) source data: prepared data in 
mapdb format ,11G, 10,000,000 keys in HashTree, init code:db = 
DBMaker.fileDB(new File(mapdbPath)).cacheSize(cacheSize) ///// cacheSize = 
100000.cacheLRUEnable().cacheHashTableEnable().make(); 
(2) model: mapdb format, about 40G (never success)model feature: huge keys, 
random fectch and put keys (3) Server parameters: 56G RAM 
My problems:I tried many method to initiate mapdb which is supposed to store the 
model(1). model initial code:db = DBMaker.fileDB(new 
File(modelPath)).cacheSize(cacheSize) ///cacheSize = 
100000.allocateStartSize(StartSize) //// StartSize = 1/1024/1024/1024; // default 
1G.allocateIncrement(increment) /// increment = 64/1024*1024; // default 
64M.cacheLRUEnable().make();phenomenon：the program processed 5,000,000 
source data, and the memory overflowed. and I noticed that the Mapdb never store 
any data into the disk.(2) so I decided to commit data into the disk manually every 
time the program processed 500,000 source dataif (Math.floorMod(count, 100) == 
0) {System.out.printf("%c ============> processed sentences: %d 
================", 13, count);if (Math.floorMod(count, 500000) == 0) 
{db.commit();System.gc();}}phenomenon：every time the program continued 
processing source data after db.commit(), the memory Soar alot, very fast. the 
memory overflowed after 1,000,000 source data was processed. 
(3) I tried another way to initiate model mapdb, and commit every 500,000 source 
data. Still,the memory overflowed after 1000000 source data was processed.
      db =  DBMaker.fileDB(new File(modelPath))
                .cacheSize(cacheSize)
                .cacheLRUEnable()
                .cacheHashTableEnable()
                .make();
 
what should I do ? 
—Reply to this email directly or view it on GitHub[1].[2]




--------
[1] https://github.com/jankotek/mapdb/issues/643
[2] 
https://github.com/notifications/beacon/AAV6bWWCt4MHzVSgsMXDrBPPfTqDRpI-ks5pMOl3gaJpZM4Guh8E.gif
