### ISSUE TITLE
db file load  cost too much time

### ISSUE THREAD

**Issue by smartnlp** [jankotek/mapdb#646]
Hi, 
(1) I have a db file, which has the keys:
private `HTreeMap<String,List<Integer>>` wordIdentityMap = null;
private `HTreeMap<String,List<Integer>>` phraseAlignmentMap = null;
the `List<Integer>` is an array with a length no more than 50,000 ;
total db file is about 11G in size

(2) db initial code:
            db = DBMaker.fileDB(new File(modelPath))
                    .cacheSize(cacheSize) //// 50,000
                    .allocateStartSize(StartSize) /// 100000
                    .allocateIncrement(increment) //// 10000
                    .cacheLRUEnable()
                    .make();
            wordIdentityScoreMap = db.hashMap("wordIdentityScoreMap");
            phraseAlignmentMap = db.hashMap("phraseAlignmentMap");
        long total = semanticIds.size() + sentenceIds.size() + sent2semIndexer.size() + posDeletionScoreMap.size();
/////////////////////   costs very long time to go to here !!
        long counter = 0;
`
(3) problems:
it costs lots of time to load this db file. In fact I wait for almost 2 hours, and give up! most of the time, the CPU is hanged up, CPU usage is very low......
what is more, it costs lots of time to generate this db file too (almost 1 day to run db.commit).
Is there any way to solve this problem?

**Comment by jankotek** [comment]
Could be problem with 
transactions? What happens if you 
disable transactions?

**Comment by smartnlp** [comment]
I will have a try tomorrow. 
but i am sure that if I cut down the size of  `List<Integer> ` in  `HTreeMap<String,List<Integer>>`, it will work well

**Comment by smartnlp** [comment]
update: as far as I know the program is blocked by `long total = semanticIds.size() + sentenceIds.size() + sent2semIndexer.size() + posDeletionScoreMap.size();`

**Comment by smartnlp** [comment]
I didn't see any difference with transactionDisable() when loading the db file. I will try it in generating db file later.
     I meet with a new problem that I get 1000 keys from the db file with total 5,000,000 keys costs 17 seconds, which is too slow. but if I get the same keys for the second time, it only cost 100ms. It seems that the database was not warmed up, and the size() function costs lots of time.

**Comment by shabanovd** [comment]
```
long total = semanticIds.size() + sentenceIds.size() + sent2semIndexer.size() + posDeletionScoreMap.size();
```

@smartnlp Is it your code?

Can you avoid it?

If not use".counterEnable()" when create map (this can't enabled on existing map).

**Comment by smartnlp** [comment]
＠shabanovd do you mean .metricsEnable() ?   I did't find a function called .counterEnable()

**Comment by shabanovd** [comment]
@smartnlp you use 1.x or 2.x?

**Comment by smartnlp** [comment]
mapdb-2.0.0-SNAPSHOT.jar

**Comment by smartnlp** [comment]
@jankotek 
(1) transactionDisable() works when generating db file, the memory is stable!
(2) I add .fileMmapEnable() when init db file, It is faster than before, when randomly get 1000 keys from db file which has total 5,000,000 keys. but still not fast enough(11 sec for the first time), any other method?

**Comment by shabanovd** [comment]
Here the example
```
db.createHashMap("wordIdentityScoreMap").counterEnable().make();
```

**Comment by jankotek** [comment]
I also thing problem is in counter. By default hashMap has to traverse all its elements to count them

**Comment by smartnlp** [comment]
@shabanovd 
thanks for your example.
@jankotek 
is there a possible that transactionDisable() will lose data?
I meet with this problem, The difference between two model is transactionDisable(),  the same data source, but the model accuracy is not the same. data is insufficient

**Comment by shabanovd** [comment]
@smartnlp If you have big number of items remember that ```size()``` method limited by integer, use ```sizeLong()``` for long.

```transactionDisable()``` must not affect data util jvm close normally and db was properly closed.

**Comment by smartnlp** [comment]
@shabanovd  the above code, output zero size. but if transactionDisable() is removed, the output size is 100000.

**Comment by shabanovd** [comment]
@smartnlp think that it's simple: ```test.put("1",list);``` must be after ```for``` block before ```db.commit();```

**Comment by smartnlp** [comment]
@shabanovd  thanks!
one more question: 
does .fileMmapEnable() work ,  if the db file was generated without this switch ?
