### ISSUE TITLE
mapdb data corruption

### ISSUE THREAD

**Issue by poornima-apakau** [jankotek/mapdb#650]
I am using mapdb as an in-memory cache.
I have transactionDisable() called while creating.
I have not changed the data structure of anything that I am storing in the cache.
But after running for 3 hrs or so, I see that DataCorruption Exception. Can you please help ?

**Comment by shabanovd** [comment]
@poornima-apakau what version do you use?

**Comment by poornima-apakau** [comment]
Hi,

I use the mapdb 2.0 beta version.

I use mapdb on a servlet running on jetty. When I restart jetty, I 
believe that all the earlier data indexes is cleared. Please confirm.

Regards,
Poornima.

**Comment by jankotek** [comment]
There was number of bugfixes which could have caused it, so please make sure you use lattest beta

**Comment by jankotek** [comment]
No answer, closing.
