### ISSUE TITLE
Need stable on-disk map 'yesterday'

### ISSUE THREAD

**Issue by xamde** [jankotek/mapdb#651]
I am following the mapdb project (and its predecessors) for a about 2 years now. Jan, I see you are adding a ton of cool features, but at the cost of not yet having a stable release.

I am looking for a map-structure on disk, used by a single thread. Should have a stable binary format which I can write and read for a year or two. 

Is this easy to extract from the current code base? Is it likely that I can do that?
Is there any other open-source project with these simplified requirements?

(To be sure: Once MapDB 2.x gets released, I would love to migrate)

**Comment by jankotek** [comment]
I dont have a good answer for that right now. Wait for two weeks, there are some news comming.

**Comment by xamde** [comment]
Thanks for the very quick response. Looking forward to the news :-)
