### ISSUE TITLE
Permormance issue when loading 4 indexes

### ISSUE THREAD

**Issue by Nasreddine** [jankotek/mapdb#657]
I've relatively small 4 indexes that I load each time I start the execution of my algorithm. 
Loading takes ~100 ms using hashMap, and ~300ms using BtreeMap.

Here how each index is loaded: 
BTreeMap<String, String[]> map = db.treeMapCreate("map")
                .keySerializer(Serializer.STRING)
                .valueSerializer(new Serializer.Array(Serializer.STRING))
                .makeOrGet();

I've noticed that the first index takes always the highest execution time compared to other indexes.
Is there a way to optimise loading my indexes ? 
I'm using the latest version 2.0-beta12.

**Comment by jankotek** [comment]
Hi,

use valuesOutsideNode() settings, also maybe change node size. 

Jan

On Monday, January 04, 2016 15:16:49 Nasreddine Cheniki wrote:


I've relatively small 4 indexes that I load each time I start the execution of my 
algorithm. Loading takes ~100 ms using hashMap, and ~300ms using BtreeMap. 
Here how each index is loaded: BTreeMap map = 
db.treeMapCreate("map").keySerializer(Serializer.STRING).valueSerializer(new 
Serializer.Array(Serializer.STRING)).makeOrGet(); 
Is there a way to optimise loading my indexes ? I'm using the latest version 2.0-
beta12. 
—Reply to this email directly or view it on GitHub[1].[2]




--------
[1] https://github.com/jankotek/mapdb/issues/657
[2] 
https://github.com/notifications/beacon/AAV6be2JSdOs5RD2sifrGZH_0K2RtqOBks
5pWvThgaJpZM4G-cyy.gif
