### ISSUE TITLE
Provide a public method that deletes the physical files of the DB

### ISSUE THREAD

**Issue by datumbox** [jankotek/mapdb#665]
This is a feature request concerning adding a public method on the DB object that deletes all the files that have been created by MapDB or returns a list with their paths.

**Comment by lmprice** [comment]
This is something that we'd really like as well.

**Comment by davidmoten** [comment]
I poked around looking for this so I could clean up files and I did notice the method I needed called `DBMaker.deleteFilesAfterClose()`. Is this enough for you?

**Comment by datumbox** [comment]
Hey David,

I'm not sure this is equivalent because you have to define it before you open the map. What if you want to delete it afterwards? 

Here is a use-case: In datumbox framework MapDB is used to persist the coefficients of Machine Learning models. A user of the lib has the ability to delete a particular model by calling the delete method. Currently I am forced to "manually" keep track of the files generated by MapDB and [delete them](https://github.com/datumbox/datumbox-framework/blob/devel/datumbox-framework-common/src/main/java/com/datumbox/framework/common/persistentstorage/mapdb/MapDBConnector.java#L137) but this is kind of ugly. It would be great if MapDB could provide a way to delete method and remove any file associated with the db/map.

If I misunderstood what you said, please do correct me. :)

**Comment by davidmoten** [comment]
So I guess you could close the `DB` instance, reopen it with the mentioned option then close it again and would work. A bit clunky of course but at least you don't have to make guesses about what files a particular version creates.

**Comment by jankotek** [comment]
`deleteFilesAfterClose()` should work this way

**Comment by MartinanderssonDotcom** [comment]
I don't want to be the one who will be the one but I will be the one.. HOWEVER.... I can't find the method `deleteFilesAfterClose()` in version 3.0.0-M4 or have I gone crazy?

**Comment by jankotek** [comment]
`deleteFilesAfterClose` is not in M4, it will be in M5 very soon

**Comment by jankotek** [comment]
Already added

**Comment by datumbox** [comment]
The described solution of reopening the db and closing afterwards is a bit hacky. A more straightforward way would be to have a closeAndDeleteFiles() method on the DB object. Do you think this is possible?

**Comment by jankotek** [comment]
also I will add new option `fileDeleteAfterOpen()`. This way database file will be visible only to DB object itself (on unix).

**Comment by jankotek** [comment]
`fileDeleteAfterOpen()` is now in 3.0-RC1. 

I will not add `closeAndDeleteFiles()`, but there is other way. `DB.getStore().getAllFiles()` will give you all files associated with store. You can use this method before close, close the store, than delete all files
