### ISSUE TITLE
Compare-and-Swap API for maps

### ISSUE THREAD

**Issue by eiennohito** [jankotek/mapdb#666]
It would be useful to have CAS-like API for maps usable in the pattern

```
V obj;
V updated;
do {
  obj = = map.get(key);
  V updated = computeUpdated(obj); //an user-provided operation
} while(map.CAS(key, obj, updated));
```

where if obj == null, there would be an insert
and if updated == null, there would be a delete.

Right now there is replace which do can not insert or delete items,
insertIfAbsent and delete could be used to do the same thing,
however the integrated approach would be more useful I believe.

**Comment by shabanovd** [comment]
Why you can't use ```compute``` method?

**Comment by jankotek** [comment]
`ConcurrentMap.replace()` does exactly what CAS in this scenario:
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentMap.html#replace(K,%20V,%20V)

Also I have plan for functional atomic updates. (instead of value pass transform function).

**Comment by jankotek** [comment]
I have not noticed how null handle deletes/updates. I added this to TODO list for 3.0

**Comment by datumbox** [comment]
In the context of using ConcurrentMap with AtomicInteger, the suggested way to increase the counter atomically is: map.get(myKey).incrementAndGet()

Nevertheless in MapDB the value needs to explicitly be stored back in the map. Is there currently a way to do this atomically with MapDB?
