### ISSUE TITLE
Disabling transactions causes slow performance

### ISSUE THREAD

**Issue by wavenger** [jankotek/mapdb#668]
Greetings! I am really happy to have found MapDB - I'm primarily using the tempfiledb to store data that doesn't easily fit into memory and which needs to expire after a day.

We had a really weird performance problem that I tracked down to DBMaker.transactionDisable(). Apparently, when this flag is set, the database gets much slower:

    Took: 3610 with useTransactions: false and useExpire: false
    Took: 5077 with useTransactions: false and useExpire: true
    Took: 152 with useTransactions: true and useExpire: false
    Took: 151 with useTransactions: true and useExpire: true

(note that "false" here means that transactionDisable was called)

Also, looking over the source code, it seems like disabling transactions when expiration is enabled is recommended ("HTreeMap Expiration should not be used with transaction enabled. It can lead to data corruption, commit might happen while background thread works, and only part of expiration data will be commited."). So I'm pretty stumped. Do you have any insight on this issue?

If you'd like to run/test yourself, here's a repo that demonstrations the problem:

https://github.com/wavenger/mapdb-test

**Comment by jankotek** [comment]
Transactions keeps uncommited data in 
memory, which serves as write cache. 
Solution is to enable Async Write Cache and 
Disable Transactions.

**Comment by wavenger** [comment]
That's very interesting, thank you. Is it safe to use transactions with expiration if the executor is not enabled?

**Comment by jankotek** [comment]
Yes it is safe

**Comment by wavenger** [comment]
Thanks for your help.
