### ISSUE TITLE
SimpleQueue.isEmpty() > peek() may throw NullPointerException

### ISSUE THREAD

**Issue by zhoupo** [jankotek/mapdb#669]
MapDB version: 1.0.8.

The exception is thrown at line 117 in Queues.java with the following code snippet:
```
return (E) n.value;
```

I access SimpleQueue object in two different thread, and guess what causes npe is ```final long head2 = head.get();``` in peek() is modified or deleted somewhere. I debug the code and found "r" is {} in the following method, which means "StoreWAL.get2()" will return null.

    @Override
    protected <A> A get2(long ioRecid, Serializer<A> serializer) throws IOException {
        assert(locks[Store.lockPos(ioRecid)].getWriteHoldCount()==0||
                locks[Store.lockPos(ioRecid)].writeLock().isHeldByCurrentThread());

        //check if record was modified in current transaction
        long[] r = modified.get(ioRecid);
        //no, read main version
        if(r==null) return super.get2(ioRecid, serializer);
        //check for tombstone (was deleted in current trans)
        if(r==TOMBSTONE || r==PREALLOC || r.length==0) return null;

**Comment by jankotek** [comment]
Not going to fix.
