### ISSUE TITLE
Copy database

### ISSUE THREAD

**Issue by pozharko** [jankotek/mapdb#671]
Hi!

Is there a way to copy full database? When I copy database file, all it's data is lost. 
I see db.snapshot() method and that's like what I need, but I couldn't find a way to save this snapshot to file.
If its not possible, is there a way to copy full collection inside db?

**Comment by jankotek** [comment]
Right now there is no way to copy database. If you copy file, make sure that DB is closed.

This feature is easy to implement by copying binary Volumes, but there is no public function for that yet.
