### ISSUE TITLE
MapDB 3.0 expects file to not exist if creating a new database

### ISSUE THREAD

**Issue by esnellman** [jankotek/mapdb#672]
If I create a empty file and ask MapDB 3.0  to init on it, It will fail on windows.

**Comment by esnellman** [comment]
Also on re-open I am getting.  org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect
	at org.mapdb.DB.<init>(DB.kt:95)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:78)


Perhaps I am missing a close on jvm exit.

**Comment by jankotek** [comment]
M1 and M2 do not support store reopen yet. That will be in milestone 3.
