### ISSUE TITLE
Open Volume was GCed, possible file handle leak

### ISSUE THREAD

**Issue by pozharko** [jankotek/mapdb#675]
```
Feb 05, 2016 3:30:59 PM org.mapdb.Volume finalize
WARNING: Open Volume was GCed, possible file handle leak.
```
Can you explain, what's wrong with that? And what should I do to prevent this.

Thanks!

**Comment by jankotek** [comment]
It is just too paranoid setting. It means that file was not closed and there might be file handle leak.
