### ISSUE TITLE
Add source jar in maven repo

### ISSUE THREAD

**Issue by omar391** [jankotek/mapdb#679]
Hi, 
Please consider adding source jar in maven in repo so it becomes more easy for dev to checkout the implementation.

Regards.

**Comment by jankotek** [comment]
Hi, I checked maven repo for M3, sources are included:
http://central.maven.org/maven2/org/mapdb/mapdb/3.0.0-M3/

What is your usage scenario, that sources are not found in?

**Comment by omar391** [comment]
Somehow, IDEA couldn't download the source autometically as it always does and when I checked google I went into "http://mvnrepository.com/artifact/org.mapdb/mapdb" instead of maven central site. That's how the confusion. 

Thanks for pointing the correct site. We can close this issue.
