### ISSUE TITLE
how can i load a dbfile?

### ISSUE THREAD

**Issue by chaosWho** [jankotek/mapdb#682]
iv created a db file named "cache.db",and put my cached map in, when i load the cache file, it throws Exception: Exception in thread "main" org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect

my usage is as flows:
====
Maker maker = DBMaker.fileDB("cache.db");
DB db = maker.make();
HTreeMap map = db.hashMap("onDisk").open();

my system: mac os X 11, 64bit, java8

thx!

**Comment by sargunster** [comment]
This is the same as #680

**Comment by jankotek** [comment]
#680 was fixed recently. M4 will be out in a few days.
