### ISSUE TITLE
MapDB 3: SortedTableMap - negative "valsBinarySize" in get

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#684]
There is missing test for last value in SortedTableMap line 298.
https://github.com/jankotek/mapdb/blob/master/src/main/java/org/mapdb/SortedTableMap.kt#L298
val valsBinarySize = offset + volume.getInt(offsetWithHead+4+(pos+nodeCount+1)*4) - valOffset

Fixed code:
val valsBinarySize = offset + (pos == nodeCount - 1 ? pageSize : volume.getInt(offsetWithHead + 4 + (pos + nodeCount + 1) * 4)) - valOffset

Fix is same like on other places in code.
Is this correct to use "pageSize" instead of correct end offset for last value?
I think that offset for first key can be computed from nodeCount. So it is no necessary to store it. And available space can be used for storing end offset for last value.

**Comment by jandam** [comment]
Same problem is with some iterators.

**Comment by jankotek** [comment]
Will have a look at this. I need to document SortedTableMap a bit more. I am also adding writeable option

**Comment by jankotek** [comment]
I see the problem now, working on rewrite
