### ISSUE TITLE
MapDB 3: SortedTableMap - entryIterators loads only keys in loadNextNode

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#685]
There is missing loading values in loadNextNode for entryIterator. findLo is OK

**Comment by jankotek** [comment]
I added test case, but could not replicate this problem. Would you provide more details?

**Comment by jandam** [comment]
Problem is at entryIterator - loadNextNode for subMaps. https://github.com/jankotek/mapdb/blob/master/src/main/java/org/mapdb/SortedTableMap.kt#L1756
  There is missing code for loading values.

**Comment by jandam** [comment]
Same problem is in valueIterator for subMap. There are invalid assignments in methods (~6 occurences) findLo, findHi.
 this.page = keyPos.toLong()
should be
 this.page = offset
And there should be following change in findLo at line 1739 and maybe on other places. Otherwise first call to findNextNode in iteration return same keys and values as after calling findLo
"this.node = nodePos + 1" instead of "this.node = nodePos"
