### ISSUE TITLE
1.0.9: useLocks meaning?

### ISSUE THREAD

**Issue by davidmoten** [jankotek/mapdb#688]
Using MapDB 1.0.9 when I call 
```java
boolean useLocks = false;
BlockingQueue<T> queue = db.createQueue("q", serializer, useLocks);
```
I receive a `java.util.concurrent.BlockingQueue` which is by its contract a thread safe queue. What does `useLocks` do?

**Comment by jankotek** [comment]
There is a difference how MapDB updates store. It could use non-blocking API which leaves tumbstones (disk space leak), or use concurrency lock without tumbstones.

In short you want `useLocks=true`
