### ISSUE TITLE
HashSets throw IllegalAccessError

### ISSUE THREAD

**Issue by gravityfox** [jankotek/mapdb#689]
Version: MapDb 3.0.0-M4

Making a hashset and then trying to add things to it throws an IllegalAccessError.

It appears that it's simply trying to add to a hashmap's keyset.

This effectively makes hashsets read-only, which could be okay in some circumstances. Since it uses HTreeMap along with Hashmaps they could be used interchangably... maybe...

Either way this should be fixed so that HashSets can actually be written to.

Thank you!

**Comment by jankotek** [comment]
It fails on reopen, will fix tmrw

**Comment by jankotek** [comment]
Fixed in de176b09676b12fc7d6e38135cc0decbf8a7d2ba
