### ISSUE TITLE
Atomic Primitive maker's getValue() returns null

### ISSUE THREAD

**Issue by gravityfox** [jankotek/mapdb#691]
Pretty much the title.

`database.atomicBoolean("somekey").getValue()` will return null even if

`database.atomicBoolean("somekey").make().get()` returns an actual value.

**Comment by shabanovd** [comment]
`getValue` return [3rd parameter](https://github.com/jankotek/mapdb/blob/6d855acada07832938fdb1754cb08ae451f95ada/src/main/java/org/mapdb/DB.kt#L1195) that is null in your case.

`database.atomicBoolean` return `AtomicBooleanMaker`, so you must call `create` or `make` or `createOrOpen` or `open` to get instance.

**Comment by jankotek** [comment]
`database.atomicBoolean("somekey").getValue()` should be protected. Fixed
