### ISSUE TITLE
Maker.create() and Maker.make() behave inconsistently.

### ISSUE THREAD

**Issue by MartinanderssonDotcom** [jankotek/mapdb#694]
Firstly, let me just say that I have no idea about the details of these methods as I haven't found them documented anywhere. So maybe what I report next is not a bug, but I doubt it.

Please note that these examples produce same result with or without an actual value put in the `Atomic.String`. I cut this value-assignment out from my examples to compress the size a little.

Run this once:

    DB db = DBMaker.fileDB("file.db").make();
    Atomic.String str = db.atomicString("Hello").create();

And it succeeds. Run it again, and it crash with this expected exception:

    org.mapdb.DBException$WrongConfiguration: Named record already exists: Hello
	    at org.mapdb.DB$Maker.make2(DB.kt:1114)
	    at org.mapdb.DB$Maker.create(DB.kt:1097)

Switch to `make()` and it will not crash no matter how many times you run this code:

    DB db = DBMaker.fileDB("file.db").make();
    Atomic.String str = db.atomicString("Hello").make();

We can make even `create()` "work" if we add a small trick to the code. This snippet also run without crashing:

    DB db = DBMaker.fileDB("file.db").make();
    
    if (db.exists("Hello")) {
        // Reading this guy once make create() turn Jesus.
        db.atomicString("Hello").open();
    }
    
    Atomic.String str = db.atomicString("Hello").create();

I would have expect both methods to crash all the time, with or without a read of the entry before creating it a second time.

**Comment by jankotek** [comment]
`create` will only work if collection does not exist. So use `make` always. I added some javadoc

**Comment by MartinanderssonDotcom** [comment]
So what is the difference between `make()` and `createOrOpen()`? I think maybe we should completely get rid of the `make()` method?

**Comment by jankotek** [comment]
There is no difference, 
make() is for 
compatibility with older 
versions.

**Comment by MartinanderssonDotcom** [comment]
Since we're going to 3.0.0, isn't it possible to remove it?

**Comment by shabanovd** [comment]
There are some api changes why keep that compatibility then? That just add confusion. @Deprecated it as minimum (with reference to new method)

**Comment by MartinanderssonDotcom** [comment]
Jan, why is this ticket closed? Inserting this snippet will **not** make `create()` crash:

    if (db.exists("Hello")) {
        // Reading this guy once make create() turn Jesus.
        db.atomicString("Hello").open();
    }

What in this code "remove" the database? Well, nothing I imagine. I have tested and `db.exists()` return true before calling `create()` which for some reason doesn't crash anymore.

**Comment by jankotek** [comment]
use `make()` or `createOrOpen()`

**Comment by MartinanderssonDotcom** [comment]
But it's really this call:

    db.atomicString("Hello").open();

..that has some weird side-effect to it such that `create()` down the road think all of a sudden that the entry doesn't exist anymore? As if "open" actually "removed"?
