### ISSUE TITLE
MapDB 3.0 M5 SortedTableMap Question and Pump Example

### ISSUE THREAD

**Issue by sselvia** [jankotek/mapdb#697]
The SortedTableMap expects everything to be pre-sorted prior to loading by the key, do you have a Pump example to load content into the SortedTableMap?

If the sorted map is supposed to sort the content during the create process it is not working?

    Volume volume = MappedFileVol.FACTORY.makeVolume(mapDBFile.getAbsolutePath(), false);

    SortedTableMap.Sink<Integer, String> sink = SortedTableMap.create(volume,
                                                                     Serializer.INTEGER,
                                                                     Serializer.STRING)
                                                             .createFromSink();

    for (int i = 0; i < 10; i++)
    {
        sink.put(i, "value" + i);
    }

or 

    for (int i = 10; i >= 0; i--)
    {
        sink.put(i, "value" + i);
    }

    SortedTableMap<Integer, String> sortedMap = sink.create();
    
    for (Integer key : sortedMap.navigableKeySet())
    {
        System.out.println(key + sortedMap.get(key));
    }
    
    volume.close();

0value0
1value1
2value2
3value3
4value4
5value5
6value6
7value7
8value8
9value9

versus

10value10
9null
8null
7null
6null
5null
4null
3null
2null
1null
0null

**Comment by jankotek** [comment]
Please try latest beta, there some bugs in SortedTableMap were recently fixed.
