### ISSUE TITLE
MapDB 3.0.beta1 / 2: org.mapdb.DBException$NewMapDBFormat

### ISSUE THREAD

**Issue by lkolek** [jankotek/mapdb#698]
reopening created mapdb files throws exception (stack trace below). 
It works in M6 and seems to be broken in beta1 & beta2.
Seems that configuration for key/value serializers is lost.
I mostly use BTreeMap.

<pre>org.mapdb.DBException$NewMapDBFormat: Name Catalog has some new unsupported features: [roads#keySerializer: required parameter not found, roads#valueSerializer: required parameter not found]
	at org.mapdb.DB.<init>(DB.kt:135)
	at org.mapdb.DB.<init>(DB.kt:37)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:426)
	at pl.geostreaming.geostr.core.model.CacheSystem.<init>(CacheSystem.java:110)
...
</pre>

**Comment by jankotek** [comment]
Problem is in custom serializer. It is a 
bug, MapDB should not treat it as an 
error, will fill fix in next beta

**Comment by jankotek** [comment]
Fixed in recent commit, 
beta3 will follow on 
Wednesday

**Comment by lkolek** [comment]
Fixed, works great.
