### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by chonamdoo** [jankotek/mapdb#699]
i use  compile 'org.mapdb:mapdb:3.0.0-M6'

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: kotlin/internal/InlineOnly.class

**Comment by jankotek** [comment]
Android is not supported in 3.0, 
build would fail in any case with 
Java8 specific API and Unsafe 
which will be added latter

**Comment by lkolek** [comment]
Will it be supported on Android N?
