### ISSUE TITLE
org.mapdb.DBException$DataCorruption after reboot

### ISSUE THREAD

**Issue by shyiko** [jankotek/mapdb#706]
Hi. This is not of immediate importance as we don't intend to use MapDB in production, but I thought it might of interest to you:

```kotlin
val db = fileDB(...).closeOnJvmShutdown().make()
db.hashMap("...").keySerializer(Serializer.STRING).createOrOpen()
db.hashMap("...").keySerializer(Serializer.STRING).createOrOpen()
db.treeMap("...").keySerializer(SerializerArrayTuple(Serializer.STRING, Serializer.STRING)).createOrOpen()
```

(db file itself - https://transfer.sh/10HejT/mapdb.corrupted)

As it says in the title - MapDB failed with "org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly, or is corrupted" after the reboot.

**Comment by lkolek** [comment]
In 3.0 transactions are disabled by default. I wonder how it would work with transactions enabled.

**Comment by shyiko** [comment]
I'll take it for a spin. Thanks.

**Comment by shyiko** [comment]
With transactions enabled, terminating the process with SIGINT resulted in:

```
Caused by: org.mapdb.DBException$GetVoid: Record does not exist, recid=1
	at org.mapdb.StoreWAL.getIndexVal(StoreWAL.kt:141)
	at org.mapdb.StoreWAL.get(StoreWAL.kt:470)
	at org.mapdb.DB.nameCatalogLoad(DB.kt:233)
	at org.mapdb.DB$Maker.make2(DB.kt:1224)
	at org.mapdb.DB$Maker.createOrOpen(DB.kt:1212)
	at org.mapdb.DB$HashMapMaker.createOrOpen(DB.kt:827)
```

(the only operation that was used was putIfAbsent)

mapdb@3.0.0-M6

**Comment by shyiko** [comment]
(db file - https://transfer.sh/13DGtt/mapdb.wtx.corrupted)

**Comment by jankotek** [comment]
There is new `3.0.0-beta3` release. Please try with that

**Comment by shyiko** [comment]
The good news - https://github.com/jankotek/mapdb/issues/706#issuecomment-217977621 isn't happening on mapdb@3.0.0-beta3. I'll try to reproduce org.mapdb.DBException$DataCorruption on newer version with transactions enabled (the last time it took 3 days of constant use) but, just to clarify, should mapdb be used with transactions disabled (default) or there are no data-integrity guaranties in that case? Thanks again.

**Comment by jankotek** [comment]
I did investigation. SIGINT triggers shutdown hook. The DB object is referenced using WeakReference from shutdown hook. So it could fail to close if DB is no longer referenced, and was GCed before shutdown. 

Will fix WeakReference in a few hours
