### ISSUE TITLE
HTreeMap clear with expiration and overflow

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#708]
By the way my code looks like this:

```
diskDb = DBMaker.fileDB(file).fileMmapEnable().closeOnJvmShutdown().make();
memDb  = DBMaker.memoryDB().make();

valueMap = diskDb.hashMap("valueMap", Serializer.INTEGER_DELTA, Serializer.STRING).createOrOpen();

memValueMap = memDb.hashMap("valueMap", Serializer.INTEGER_DELTA, Serializer.STRING)
        .counterEnable()
        .expireAfterGet(1, TimeUnit.SECONDS)
        .expireOverflow(valueMap)
        .expireStoreSize(1024*1024*100) // 100 MB memory
        .expireExecutor(Executors.newSingleThreadScheduledExecutor())
        .create();

```

On Tuesday, May 10, 2016 at 10:09:12 AM UTC+2, Guillaume B wrote:
>
> Hi there,
>
> I am using MapDB beta 3 and the disk DB  + memory DB with expiration 
> overflow method, so that I can keep the most used lookups in a small 
> heap-based DB, and the rest backed by disk.
>
> When I am finished with working with my values, I would like to make sure 
> that my memory db forces expiration of all keys and consolidates all values 
> in the disk db. Can I do that without waiting for time-based expiration?
> Something like memDB.expireAll().
>
> I have found the HTreeMap.expireEvict() method but there is no 
> documentation whether it does what I want.
>
> Any help?
>
> Best regards,
> Guillaume
>

**Comment by abhishekmaheshwari86** [comment]
Hi,

I am facing issue with expireStoreSize. while expiry is running its removing the key but its still using heap. Code and log is below . Please let me know what i did wrong (API Version 3.0.7)

         
          final DB db;
          final HTreeMap onDisk;
          final  DB dbMemory;
          File fileDir = new File(dir);
          fileDir.mkdirs();
          String filePath=fileDir.getAbsolutePath()+"/" + cacheName;
         
         db = DBMaker
                 .fileDB(filePath)
                 .executorEnable()
                 .allocateStartSize(1*1024*1024l) 
                 .allocateIncrement(1*1024*1024l)
                 .fileLockDisable()
                 .fileMmapEnable()
                 .transactionEnable()
                 .closeOnJvmShutdown()
                 .make();
         onDisk =  db
                 .hashMap(cacheName, new Serializer<Integer>()
                 {
                     @Override
                     public void serialize(@NotNull DataOutput2 out, @NotNull Integer value) throws IOException
                     {
                         out.write(keyCodec.encode(value).array());
                     }

                     @Override
                     public Integer deserialize(@NotNull DataInput2 input, int available) throws IOException
                     {
                         byte[] data = new byte[available];
                         input.readFully(data);
                         return keyCodec.decode(ByteBuffer.wrap(data));
                     }
                 }, new Serializer<Integer>()
                 {
                     @Override
                     public void serialize(@NotNull DataOutput2 out, @NotNull Integer value) throws IOException
                     {
                         out.write(valueCodec.encode(value).array());
                     }

                     @Override
                     public Integer deserialize(@NotNull DataInput2 input, int available) throws IOException
                     {
                         byte[] data = new byte[available];
                         input.readFully(data);
                         return valueCodec.decode(ByteBuffer.wrap(data));
                     }
                 })
                 .counterEnable()
                 .createOrOpen();
         dbMemory = DBMaker
                 .memoryDB().executorEnable()
                 .make();
         HashMapMaker<Integer,Integer> storeBuilder = (HashMapMaker<Integer,Integer>) dbMemory
                 .hashMap(cacheName+"_inMemory")
                 .expireStoreSize(100*1024*1024);
         HTreeMap<Integer,Integer> store=storeBuilder
                 .expireOverflow(onDisk)
                 .expireExecutor(Executors.newScheduledThreadPool(2))
                 .expireExecutorPeriod(1000)
                 .create();
         final SizeOf sizeOf=SizeOf.newInstance();
         service.submit(()->{
        	 while(true){
        		 System.out.println("Memory Store Size:"+store.size()+" Size in bytes :"+sizeOf.deepSizeOf(store));
        		 System.out.println("Disk Store Size:"+onDisk.size()+" Size in bytes :"+sizeOf.deepSizeOf(onDisk));
        		 Thread.currentThread().sleep(10000);;
        		 
        	 }
         });
         Map<Integer,Integer> map=new ConcurrentHashMap<>();
         IntStream intStream = IntStream.range(1, 100000000);
         intStream.parallel().forEach(e->{
        	 store.put(e, e);
        	 if(e%100000==0){
	        	dbMemory.commit();
        	 }
         });

LOG
Memory Store Size:0 Size in bytes :6857864
Disk Store Size:0 Size in bytes :4324216
Memory Store Size:185074 Size in bytes :112656536
Disk Store Size:425105 Size in bytes :112674552
Memory Store Size:155323 Size in bytes :266361776
Disk Store Size:964607 Size in bytes :267441560
Memory Store Size:1449 Size in bytes :357144984
Disk Store Size:1542374 Size in bytes :290434416
Memory Store Size:93998 Size in bytes :509319872
Disk Store Size:2027007 Size in bytes :430026712
Memory Store Size:48940 Size in bytes :671834568
Disk Store Size:2716112 Size in bytes :576944392
Memory Store Size:164179 Size in bytes :691005120
Disk Store Size:3189456 Size in bytes :691027272
Memory Store Size:126685 Size in bytes :708736152
Disk Store Size:3776823 Size in bytes :775877464
Memory Store Size:19227 Size in bytes :1261946696
Disk Store Size:4321956 Size in bytes :1129174856
Memory Store Size:77660 Size in bytes :1284358504
Disk Store Size:4794159 Size in bytes :1140051976
Memory Store Size:89940 Size in bytes :1306397216
Disk Store Size:5454729 Size in bytes :1307618112
Memory Store Size:16312 Size in bytes :1325724984
Disk Store Size:5953150 Size in bytes :1153106424
Memory Store Size:187961 Size in bytes :1341394448
Disk Store Size:6396499 Size in bytes :1341556592
Memory Store Size:60565 Size in bytes :1362890880
Disk Store Size:6993521 Size in bytes :1166407488
Memory Store Size:13633 Size in bytes :1921487104
Disk Store Size:7499716 Size in bytes :1713216288
Memory Store Size:28114 Size in bytes :2491599080
Disk Store Size:7961409 Size in bytes :2273223064
Memory Store Size:2226 Size in bytes :2509267536
Disk Store Size:8341948 Size in bytes :2281073496
Memory Store Size:69791 Size in bytes :2526311568
Disk Store Size:8724530 Size in bytes :2289728992
