### ISSUE TITLE
Does mapdb 3 must use jdk 1.8

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#709]
I can't use jdk 1.7 to compile my project when use mapdb 3
Must to use more than 1.8 version?

**Comment by shabanovd** [comment]
yes, java 1.8 required for mapdb 3.x

**Comment by KeyOfSpectator** [comment]
Is there any stable release of MapDB for jdk 1.7?
I can only found alpha or beta release in MapDB version 2.*
Is there any stable release for version 2?
And what is the difference between version 2 and version 3?
