### ISSUE TITLE
DBMaker#makeEngine() does not always close open files (volumes)

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [jankotek/mapdb#711]
It seems that `DBMaker#makeEngine()` does not always close the Volumes. The problem seems to occur in the code which inserts a testing record. I will try to come up with a solution soon.

**Comment by LukeButtersFunnelback** [comment]
Hi I created a Fix: 
https://github.com/jankotek/mapdb/pull/712 
Hopefully I created the pull request correctly. I have not created a test as it is not immediately obvious on how to do it.

**Comment by jankotek** [comment]
Hi, I will merge this, but MapBD 1.0 is unsupported now, it might take a while before there will be new release

**Comment by LukeButtersFunnelback** [comment]
Hi, thanks for accepting my merge request. I very much look forward to the next release.
