### ISSUE TITLE
how to let mapdb3 compatible jdk7?

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#715]
I find mapdb3 is much better than mapdb2,what's the different between them?
On the other hand,If there a way to let mapdb3 compatible jdk7?
Thank you!

**Comment by jankotek** [comment]
MapDB 3 is written in Kotlin programming language, uses external libraries and needs Java8. Java 7 suppport is in theory possible, but I am not going to add it unless someone sponsors it.
