### ISSUE TITLE
 java.lang.AssertionError: data were not fully read, check your serializer 

### ISSUE THREAD

**Issue by synth3** [jankotek/mapdb#718]
The problems described in #515 still seem to exist in version 1.0.9.
Env:
- Java(TM) SE Runtime Environment (build 1.8.0_73-b02) 64-Bit
- Windows 7

Details:
- The stack traces are the same as in the referenced ticket.
- The db probably got corrupted after trying to write to the db with no free memory left on the used file system.

**Comment by jankotek** [comment]
1.0 branch is no longer supported, sorry :(
