### ISSUE TITLE
BTreeMap - partitioning, physical layout control - question

### ISSUE THREAD

**Issue by lkolek** [jankotek/mapdb#720]
Are there any possibilities to control how BTreeMap entries are stored, except for allowing values to be stored outside? 
What I'd ideally want is to be sure to keep entries that have similar keys together in file level, to be sure they are loaded together.
Of coure, one possibility is to do this outsied of BTreeMap. Are there any other places (eg. volume store) where that could be implemented?

**Comment by jankotek** [comment]
To keep nodes together use Pump: `db.treeMap("map").createFrom(...)`. That will nodes in proximity to each other. 

There is a plan to enable more detailed partitioning. For example put values in one store, leafs with keys into second and directories in third. However that will be in future versions. So far there is only stab of documentation:
http://www.mapdb.org/doc/layout/
