### ISSUE TITLE
Infinite loop when use mapdb2.0.0-beta13

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#722]
Here is my code：
private BTreeMap<KeyIndex,Long> index;
 for(;;) {
                    old = index.putIfAbsent(i, s.getId());//return old is not null
                    if (old == null) {
                        dataStat.incStat(DataStat.StatClassify.CIC);
                        putOrConflictSolve(s, sessionConflict);
                        break;
                    } else {
                        SessionAncestor os = session.get(old);
                        if (null == os){
                            if(index.replace(i,old,s.getId())){//replace return false,infinite loop
                              putOrConflictSolve(s,sessionConflict);
                                break;
                            }else{
                                continue;
                            }
                        }else {
                            sessionConflict.conflictSolve(os, s);
                            break;
                        }
                    }
                }

----------------------------------------------------

**Comment by jankotek** [comment]
Please migrate to 3.0, version 2 is not supported anymore

**Comment by zhouyibing** [comment]
In my company's product environment not supported jdk8,is jdk7.
so, I can not use mapdb 3.0
It's really bad
