### ISSUE TITLE
Working transaction example for 3.0.0

### ISSUE THREAD

**Issue by kk00ss** [jankotek/mapdb#738]
I don't see a method makeTxMaker(), well.. scala compiler doesn't see it either...

**Comment by kk00ss** [comment]
I assume this is it - https://github.com/jankotek/mapdb/blob/968c7768856d772354cb5b5aa8e7eb3fd27c0927/src/test/java/org/mapdb/StoreTxTest.kt ?

**Comment by jankotek** [comment]
3.0.0 does not have TxMaker, it will be added in 3.1
