### ISSUE TITLE
MAPDB memory problems

### ISSUE THREAD

**Issue by smartnlp** [jankotek/mapdb#742]
Hi,
I made a huge mapdb file, and read keys only in use.

    private int cacheSize = 1024;
    private DB db = null;
    private long StartSize = 1000; // default 1G
    private long increment = 1000;     // default 64M
db = DBMaker.fileDB(new File(modelPath))
                    .cacheSize(cacheSize)
                    .allocateStartSize(StartSize)
                    .allocateIncrement(increment)
                    .cacheLRUEnable()
                    .transactionDisable()
                    .make();
MY problem:
1. when reading keys, the memory goes up untill the jvm's top memory.
2. program start up memory: 20G. jvm Xmx,Xms 50G

I hope the mapdb can use fixed memory just like cacheSize defined. and not eat memory as a hungry animal. 
My version 2.0. How should I configure mapdb ?
Thank you

**Comment by smartnlp** [comment]
when JVM meets top memory 50G, the system will do gc() every 60s. the program will hang up for 10s. Anyway the program is stable for 4 hours. so I think there is a way to configure mapdb not to eat up memory. 

^Cchengiant@server-150:~/robot$ jstat -gcutil 5225 10000
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00  91.76   0.00  98.84  96.24  90.00   1809  875.282    76  855.293 1730.575
 91.90   0.00  86.16  38.92  96.24  90.00   1812  876.397    76  866.801 1743.198
 93.87  75.70 100.00  50.83  96.24  90.00   1817  878.231    76  866.801 1745.031
  0.00  99.97  29.75  61.45  96.24  90.00   1821  880.559    76  866.801 1747.360
  0.00  93.06  63.92  71.69  96.24  90.00   1825  882.464    76  866.801 1749.265
  0.00 100.00  92.56  81.89  96.24  90.00   1829  884.388    76  866.801 1751.189
 91.75   0.00   0.00  94.77  96.24  90.00   1834  886.838    76  866.801 1753.639
 93.92   0.00   0.00  99.78  96.24  90.00   1836  887.795    77  866.801 1754.596
  0.00  99.96  76.47  33.83  96.24  90.00   1837  887.993    77  878.570 1766.563
 38.00  95.91 100.00  45.01  96.24  90.00   1842  889.870    77  878.570 1768.440
 94.74   0.00  24.47  56.79  96.24  90.00   1846  892.199    77  878.570 1770.769
 94.63   0.00  56.37  66.93  96.24  90.00   1850  894.099    77  878.570 1772.669
 96.34   0.00  84.45  77.23  96.24  90.00   1854  896.046    77  878.570 1774.615
 96.76  58.13 100.00  88.97  96.24  90.00   1859  898.004    77  878.570 1776.574
 93.63   0.00   0.00  97.46  96.24  90.00   1862  899.882    78  878.570 1778.452
  0.00   0.00  87.10  33.84  96.24  90.00   1862  899.882    78  889.704 1789.586
  0.00  97.69  10.67  44.02  96.24  90.00   1867  901.963    78  889.704 1791.666
  0.00  96.56  41.77  54.17  96.24  90.00   1871  903.821    78  889.704 1793.525
  0.00  95.94  73.62  64.43  96.24  90.00   1875  905.722    78  889.704 1795.426
 20.09  99.94 100.00  75.03  96.24  90.00   1880  907.634    78  889.704 1797.338
 70.17   0.00  20.61  87.34  96.24  90.00   1884  910.008    78  889.704 1799.711
 75.26   0.00  76.62  97.03  96.24  90.00   1888  911.820    78  889.704 1801.524
  0.00  72.16   0.00  99.48  96.24  90.00   1889  912.282    79  889.704 1801.986
 76.56   0.00  68.28  38.72  96.24  90.00   1892  913.368    79  901.087 1814.454
 87.36  38.89 100.00  49.70  96.24  90.00   1897  915.191    79  901.087 1816.277
  0.00  88.57  28.01  61.33  96.24  90.00   1901  917.529    79  901.087 1818.615
  0.00  88.44  66.06  71.39  96.24  90.00   1905  919.415    79  901.087 1820.502
  0.00  89.95  99.30  81.23  96.24  90.00   1910  921.311    79  901.087 1822.398
 91.83   0.00   8.90  93.91  96.24  90.00   1914  923.704    79  901.087 1824.790
 94.72   0.00   0.00  98.87  96.24  90.00   1916  924.650    80  901.087 1825.737
 92.07   0.00   6.60  36.44  96.24  90.00   1918  925.295    80  912.077 1837.371
 94.25   0.00  40.27  46.76  96.24  90.00   1922  927.163    80  912.077 1839.240
 94.91   0.00  78.17  56.97  96.24  90.00   1926  929.029    80  912.077 1841.106
 95.42  22.45 100.00  67.64  96.24  90.00   1931  930.931    80  912.077 1843.007
  0.00  99.93  16.53  79.77  96.24  90.00   1935  933.327    80  912.077 1845.404
  0.00  99.93  45.56  89.77  96.24  90.00   1939  935.246    80  912.077 1847.323
 97.63   0.00   0.00  97.49  96.24  90.00   1942  936.704    81  912.077 1848.781

**Comment by smartnlp** [comment]
@jankotek

**Comment by kk00ss** [comment]
I would suggest you to take a look at https://github.com/deephacks/lmdbjni it's java driver for an awesome Lightning Memory Mapped Database by Howard Chu.

**Comment by jankotek** [comment]
Disable `.cacheLRUEnable()`, or use smaller size. That is causing memory leak
