### ISSUE TITLE
Implementation Examples for version 2.0-beta13

### ISSUE THREAD

**Issue by Loeing** [jankotek/mapdb#748]
Hi Jan,
I am working on a project that uses Java 1.7 and jdbm2. I've been thinking of updating to using mapdb (version 2.x.x since version 3 requires Java 1.8) but I can't seem to find any examples for it's implementation. I'm mainly interested in the usage of StoreDirect and would be grateful if you had any old examples of it in use.
Thanks,
Josh

**Comment by jankotek** [comment]
https://github.com/jankotek/mapdb/tree/release-2.0/src/test/java/examples
