### ISSUE TITLE
Problems after switch version to 3.0.1

### ISSUE THREAD

**Issue by Miger88** [jankotek/mapdb#753]
Hello,

I tried to use the new Version 3.0.1 because you told me version 1.0 and 2.0 are not longer supported. But now there are some errors within my code.

ConcurrentMap fahrtenmap = db.hashMap("fahrten").make();
make is deprecated
What shall I do instead?

cannot resolve method db.delete("xxx");
How can I delete one single hashmap?

If I try to build my App now in Android Studio I got the following error:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK LICENSE-EDL-1.0.txt
	File1: C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.eclipse.collections\eclipse-collections-forkjoin\7.1.0\7fea818153155d7107d01fe3c2f329cf7416c806\eclipse-collections-forkjoin-7.1.0.jar
	File2: C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.eclipse.collections\eclipse-collections\7.1.0\2376a19880033964254d6d57c82c1c5587d4c2fb\eclipse-collections-7.1.0.jar
	File3: C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.eclipse.collections\eclipse-collections-api\7.1.0\db56a4c791fbc1898ef62bc0b0090c1ab42a8552\eclipse-collections-api-7.1.0.jar

**Comment by lkolek** [comment]
You can use create, open or createOrOpen methods.
e.g. db.hashMap("fahrten").createOrOpen()

http://www.mapdb.org/dokka/latest/mapdb/org.mapdb/-d-b/-hash-map-maker/index.html

**Comment by Miger88** [comment]
Ah thanks, Using createOrOpen looks like the right solution for the first problem.

**Comment by Miger88** [comment]
After adding some excluding packaging Options to the build.gradle because of the third error in the first post here, I got another Error:

Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing org/mapdb/Atomic.class
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_20\bin\java.exe'' finished with non-zero exit value 1

**Comment by lkolek** [comment]
you need java 1.8 version - also in gradle.

sourceCompatibility = 1.8

**Comment by Miger88** [comment]
How can I change this?

**Comment by jankotek** [comment]
I am afraid that java 8 is not supported on android.

**Comment by Miger88** [comment]
Hello,

I think Java 8  is   supported in Android, look at the following Document from Android Developer:
https://developer.android.com/guide/platform/j8-jack.html

**Comment by Miger88** [comment]
I got it. Now it works for me. But it only works with Api 24. 

My Build Gradle:
apply plugin: 'com.android.application'

android {
    packagingOptions {
        pickFirst 'LICENSE-EDL-1.0.txt'
        pickFirst 'LICENSE-EPL-1.0.txt'
    }
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "com.example.michael.mapdb"
        minSdkVersion 24
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        jackOptions {
            enabled true
        }
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile group:'org.mapdb', name:'mapdb', version:'3.0.1'
}


You have to add this line in your gradle.properties(Project Properties)
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

After this,   it works.
