### ISSUE TITLE
expireMaxSize confusion for HTreeMap

### ISSUE THREAD

**Issue by amit2103** [jankotek/mapdb#754]
Hey,

Many thanks for creating this wonderful project.
We are trying to use this for our production application.

In our case I am a bit confused by the documentation of HTreeMap.
In the doc it is mentioned that :- 

Map cache = db
        .hashMap("map")
        .expireMaxSize(16 * 1024*1024*1024)
        .expireAfterGet()
        .create();

Will create a map which will expire after 16GB . However in the next example it is written that  .expireMaxSize(128) will set a maximal size for the map (this is in numbers I guess).

However how does MapDB when to use a number of entries vs size based on the same parameter? Or I am missing something? Looking at the test cases it seems that storeSize specifies the total size in memory after which data will be expired. Is the under standing correct?

**Comment by jankotek** [comment]
typo, use `expireStoreSize`
