### ISSUE TITLE
Can get a value with specified Serializer in HTreeMap Or BTreeMap?

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#757]
Can get a value with specified Serializer in HTreeMap Or BTreeMap?
like: map.get(key,Serializer.Long)
I can specified a serializer when invoked "get"
There have a way to do that?

**Comment by jankotek** [comment]
No, there is not. You need to specify serializer when map is created, it can not be changed latter at runtime.

But maps can be reopened with different serializer

**Comment by zhouyibing** [comment]
how to reopened the maps?

**Comment by jankotek** [comment]
db.close(), than reopen db, and use different serializer when reopening
map.
