### ISSUE TITLE
Data were not fully read,check your serializer

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#758]
Can you help me take a look at why will appear this problem?
mapdb version is 2.0-beta13 (The online environment of our company can't use the JDK 8,so i can not use mapdb 3.0)
Thank you very much!

Exception in thread "main" org.mapdb.DBException$DataCorruption: Data were not fully read, check your serializer. Read size:63, expected size:127

Here is my test code!
-----------------------------------------------------------------------------------------------------
public class TestMapDB {
    public static void main(String[] args) throws InterruptedException, FileNotFoundException {
        DB db = DBMaker.memoryDirectDB().transactionDisable().closeOnJvmShutdown().make();
        HTreeMap<Integer,Session> sessions = db.hashMapCreate("session")
                .keySerializer(Serializer.INTEGER)
                .valueSerializer(Serializer.JAVA)
                .makeOrGet();
        //1.put some data
        for(int i=0;i<100;i++){
            sessions.put(i,new Session(i,i+""));
        }
        //2.dump data
        StoreDirect.forDB(db).backup(new FileOutputStream(new File("D:\\session")),false);
        db.close();
        //3.load data
        DB db2 = DBMaker.memoryDirectDB().transactionDisable().closeOnJvmShutdown().make();
        StoreDirect.forDB(db2).backupRestore(new InputStream[]{new FileInputStream(new File("D:\\session"))});
        HTreeMap<Integer,Session> sessions2 = db2.hashMapCreate("session")
                .keySerializer(Serializer.INTEGER)
                .valueSerializer(Serializer.JAVA)
                .makeOrGet();
        //4.put some new data
        for(int j=1000;j<10000;j++){
            sessions2.put(j,new Session(j,j+""));//here occurred an exception
        }
    }

    static class Session implements Serializable{
        private int id;
        private String content;

        public Session(int id, String content) {
            this.id = id;
            this.content = content;
        }
    }

}

**Comment by jankotek** [comment]
Sorry, 2.x branch is unsupported
