### ISSUE TITLE
Delete problem

### ISSUE THREAD

**Issue by surest** [jankotek/mapdb#759]
Hi,
I use the DB.atomicInteger method by version 3.0.1. When I don't use the Integer any more, I want to delete it cause it takes up the space, but I didn't find the method to do this.

I also don't want to delete the db file (I use the DBMaker.fileDB method) cause it contains other data.

I see someone make an [issue](https://github.com/jankotek/mapdb/issues/753) about the delete problem, but there's no answer in it.

Can you tell me how can I do ?

As well as method atomicInteger, when I use DB.hashMap to create a Map, how can I delete it without delete the disk file?

Thanks !

**Comment by jankotek** [comment]
It is recently fixed in not yet released 3.1 branch

**Comment by jankotek** [comment]
delete was recently added to 3.1 branch, it will be released in a few
weeks.
