### ISSUE TITLE
About Queue<T>

### ISSUE THREAD

**Issue by surest** [jankotek/mapdb#764]
Hi, 
I'm using the version 3.0.1 and I don't find the method to make a Queue<T>.
I only found the QueueLong class to fill a queue with Long.
Is there any future version will integrate the Queue<T> method ?

Thank you !

**Comment by jankotek** [comment]
Yes, Queues will be addded in future version.

**Comment by cjaeriksson** [comment]
I'm in need of queues as well, any idea now when this might be available ?

**Comment by thmarx** [comment]
I'm also still using mapdb 1.0.9 because I need the queue.

**Comment by nddipiazza** [comment]
+1 why did we close the issue if the queues aren't yet available? might be good to leave it open.
