### ISSUE TITLE
mapdb seems incompatible with latest eclipse collections

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/mapdb#766]
@jankotek, ec version in mapdb arranged from 7.0 to 7.20 but the latest one was 8.0.0, when upgraded to that version, there exited complied error for IndexTreeLongLongMap class in mapdb. 
![image](https://cloud.githubusercontent.com/assets/749788/18816416/19454678-837c-11e6-8e97-fce95972ffcb.png)

**Comment by jankotek** [comment]
I will upgrade 3.1 branch to newer version. Thanks

**Comment by bwzhang2011** [comment]
@jankotek, thanks for quick view and release 3.1 branch in the future. what's more, hope more performance report could be provided especially compared to chronicle map if you take interest in.
