### ISSUE TITLE
introduce method "Map void putOnly(<k>, <v>)"

### ISSUE THREAD

**Issue by patriknw** [jankotek/mapdb#769]
I was surprised that deserialize was called when using `put` in `HTreeMap` (and `BTreeMap`). I think this is because old value is needed for modification listeners. It should be possible to avoid that if there are no modification listeners registered. It would be a major performance improvement.

**Comment by jankotek** [comment]
`Map.put` returns old value. So mapdb needs to deserialize old value in order to return it.

**Comment by jankotek** [comment]
introduce method "Map void putOnly(<k>, <v>)" 

Hazelcast has interface for network optimized maps (no return values), see if it can be implemented

**Comment by shabanovd** [comment]
Will it be possible to add method that do not return old value?

**Comment by jankotek** [comment]
putOnly does that

**Comment by patriknw** [comment]
thanks
