### ISSUE TITLE
when create two map from the same db,  throw exception

### ISSUE THREAD

**Issue by shuzhongling** [jankotek/mapdb#783]
the code is blow:
DB db = DBMaker.fileDB("D:\\test0.db").closeOnJvmShutdown().make();
HTreeMap map = db.hashMap("szl").createOrOpen();
HTreeMap map1 = db.hashMap("szl1").createOrOpen();
map.put("shuzhongling", "luyuhuan");
map.close();
map1.put("shuzhongling1", "luyuhuan1");

the last line will throw exception.   java.lang.IllegalAccessError: Store was closed

**Comment by jankotek** [comment]
map.close() will close underlying database, not just single map
