### ISSUE TITLE
should throw exceptions instead of errors

### ISSUE THREAD

**Issue by roxchkplusony** [jankotek/mapdb#802]
Errors mean very serious system-level problems that could abort the program. Since mapdb is a component in a larger system, it should not throw Errors, but instead Exceptions. Looking at the descriptions of a few, especially IllegalAccessError, it's clear that these aren't to be thrown lightly.

**Comment by jankotek** [comment]
There is discussion about checked versus unchecked exceptions. MapDB decided to use unchecked exceptions for compatibility with interfaces such as `java.util.Map`. But the `IllegalAccessError` should not be thrown, all exceptions should be unified under common `org.mapdb.Exception`

**Comment by roxchkplusony** [comment]
If you'd like, I'll look into replacing exceptions like IOException with org.mapdb.Exception equivs.

**Comment by jankotek** [comment]
@roxchkplusony please do. You can add new subclasses to `org.mapdb.Exception`. Also keep on mind that Kotlin does not catches exceptions, so the `IOException` might remain unhandled in Kotlin code.

**Comment by scottcarey** [comment]
There is UncheckedIOException (https://www.google.com/search?q=UncheckedIOException) in the stdlib.   It may be useful to use or extend it when wrapping an IOException.
