### ISSUE TITLE
LRU cache and Asynchronous Writes in MapDB3

### ISSUE THREAD

**Issue by datumbox** [jankotek/mapdb#804]
MapDB3 seems to have a better and more modular architecture than its predecessors. Unfortunately though at the moment it is missing some of the key features of MapDB 1 that made it very fast in real world applications. The 2 core features are the support of LRU caching and the asynchronous writes. Are we going to see them on MapDB 3? If yes what is their priority in the roadmap?

I am particularly interested in including the latest version of MapDB on Datumbox ML Framework. I have already a [branch](https://github.com/datumbox/datumbox-framework/tree/mapdb3) which supports it but unfortunately without the two afforementioned features it is extremely slow.

**Comment by jankotek** [comment]
Instance cache and async writes will be added in 3.1 release. It is major missing feature in MapDB3.

**Comment by datumbox** [comment]
Awesome Jan, thanks for the update.

**Comment by vikumar-ciena** [comment]
@jankotek : I was looking for "LRU cache and Asynchronous writes" functionality . Which release will have them ?
