### ISSUE TITLE
very occasionally It is blocked when DB delete is executed. (version 1.0.9)

### ISSUE THREAD

**Issue by Jinstarry** [jankotek/mapdb#806]
mapdb version 1.0.9
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

I have a question. I'm using mapdb well but very occasionally It is blocked when DB delete is executed.
It's a very serious problem for me. :( 
In addition, version compatibility is only available for 1.0.x versions.

I just use m_db.delete(clientID) methods.
How can I help solve this problem? I need advice.

I checked tcp dump log.

"nioEventLoopGroup-3-3" prio=10 tid=0x00007f5cec032800 nid=0x2fdf runnable [0x00007f5cd8a04000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)
        at org.mapdb.BTreeMap.lock(BTreeMap.java:2899)
        at org.mapdb.BTreeMap.remove2(BTreeMap.java:965)
        at org.mapdb.BTreeMap.remove(BTreeMap.java:950)
        at org.mapdb.DB.delete(DB.java:1529)
        - locked <0x00000000c0623ee0> (a org.mapdb.DB)

"nioEventLoopGroup-3-4" prio=10 tid=0x00007f5cec033000 nid=0x2fff waiting for monitor entry [0x00007f5cd8d07000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.mapdb.DB.delete(DB.java:1490)
waiting to lock <0x00000000c0623ee0> (a org.mapdb.DB)

java.lang.Thread.State: BLOCKED (on object monitor)
at org.mapdb.DB.delete(DB.java:1490)
waiting to lock <0x00000000c0623ee0> (a org.mapdb.DB)

Please give me some advice. Thanks.

**Comment by jankotek** [comment]
Looks like deadlock problem. I would try to disable async writes if they are enabled. 

I am sorry but I no longer support 1.x branch. I would be happy to help out for money (mailto: jan at kotek dot net)
