### ISSUE TITLE
StoreOnHeap#getTotalSize() implementation

### ISSUE THREAD

**Issue by jmveramaiquez** [jankotek/mapdb#810]
Hi,
in order to create automatic proceses to free memory when running out, will be very interesting to have an equivalent implementation to StoreDirect#getTotalSize() in StoreOnHeap.

I'm not asking for a byte precision value, but at least with the already allocated structures.

thanks,
    JM

**Comment by jankotek** [comment]
Not possible without much overhead. Serializer could provide size estimates for data (long takes 8 bytes), but it would not include pointers, class structure overhead...

Heap store uses `Map<recid, record>`, so perhaps it could return size of this map.

**Comment by jankotek** [comment]
I added `Store.getAllRecidsSize()` to get number of records in store
