### ISSUE TITLE
Tuple2

### ISSUE THREAD

**Issue by marc0x71** [jankotek/mapdb#813]
Hi
I would like to use Tuple2, as described in this example 

https://jankotek.gitbooks.io/mapdb/content/btreemap/composite-keys.html

but it seems not present into 3.0.3 version :(

Could you help me
Thanks

**Comment by jankotek** [comment]
Tuples are in 3.1 branch, which is not relased yet.

**Comment by Purus** [comment]
Any idea when 3.1 will be available for use?
