### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [jankotek/mapdb#817]
in mapdb the index using trie is all loaded in memory or your implementation permits to load trie partially when is necessary?

**Comment by scottcarey** [comment]
If it answers your question: I have used it with 300GB of indexes on disk open, but only 32GB of RAM.

**Comment by publicocean0** [comment]
Normally  in what I see trie ( b tree or Patricia tree ) structure is all in memory but the memory block is load Partially . I asked it because I wish  to develop for curiosity a mini database system but normally trie algorithms are designed for working all in memory but a partial loading maybe would be more flessible
