### ISSUE TITLE
HTreeMap: "stores size wrong" when using a custom concShift

### ISSUE THREAD

**Issue by javier-godoy** [jankotek/mapdb#819]
In HashMapMaker.open2 `stores` is initialized with segmentCount = _concShift, before reading _concShift from the catalog.

If the name has not been instantiated before, a call to `db.get(name)` (for an existing HTreeMap constructed with a custom layout) results in `open2` being called with the default value of _concShift, which raises an exception in HTreeMap constructor: "**stores size wrong**".

This issue applies to mapdb 3.0.3.

**Comment by jankotek** [comment]
Fixed in 30 and 31 branches
