### ISSUE TITLE
ClassNotFoundException MutableLongList

### ISSUE THREAD

**Issue by Tyvain** [jankotek/mapdb#822]
Followed the guide but got:
```
 java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
```
More about this error here:
http://stackoverflow.com/questions/43425367/mapdb-classnotfoundexception-kotlin-jvm-internal-intrinsics

It quite urgent, if someone could help/guide me here.

**Comment by Alhasanhussein** [comment]
[08392254264900.txt](https://github.com/jankotek/mapdb/files/957324/08392254264900.txt)








[Anvisningar för praktikrapporten.pdf](https://github.com/jankotek/mapdb/files/957323/Anvisningar.for.praktikrapporten.pdf)

**Comment by jankotek** [comment]
You need to have all jar files in classpath.
