### ISSUE TITLE
HTreeMap.replace destroys the map

### ISSUE THREAD

**Issue by xorqe** [jankotek/mapdb#825]
I work on a project where we used mapdb 1.0.8 and I'm now trying to upgrade to version 3.0.4. 

We use mapdb as a temporary data storage because we wanted a solution that purely runs on the JVM.

Temporary means: We load datasets from files and store them in the db. Then we request a backend for the items we just imported, and update those items from the backend with the data we just imported. After that, we need to replace the items in the mapdb with the merged items, before we upload the result back to the backend. After that, the db will be cleared&closed until we get the next file to import.

However, I'm creating a database and a hashmap:

```
DB db = DBMaker
                .tempFileDB()
                .transactionEnable()
                .closeOnJvmShutdown()
                .fileDeleteAfterClose()
                .make();

HTreeMap<String, Item> items = db
                .hashMap("items")
                .keySerializer(Serializer.STRING)
                .valueSerializer(ItemSerializer.getInstance())
                .createOrOpen();
```

Then I have a method that inserts/replaces values into the map:

```
public Item add(Item item) {
        final String key = item.getID();
        final Item previous = items.get(key);
        if (previous != null) {
            items.replace(key, previous, item);
        } else {
            items.put(key, item);
        }
        return previous;
    }
```

Replacement simply doesn't work any longer, with 1.0.8 it worked (code was a little different, I just used put(..) in both cases and it worked and just replaced the old value). Now if I step through it in the Debugger and have the items map "open", after the .replace(..) it says `Unable to evaluate the expression Method threw 'java.lang.RuntimeException' exception.`. 
After that I still can get the key-index from the map, but as soon as I try to iterate over the items or even get a specific one, the map just returns null.

**Comment by jankotek** [comment]
Would you post more information? I need
* stack trace when you try to reopen the map* `ItemSerializer.equals`
method content (to make sure that equals works always)* content of
`Item`, is it immutable?* what happens if you use on-heap db instead of
file?
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jankotek/
> mapdb","title":"jankotek/mapdb","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jankotek/mapdb"}},"updates":{"snipp
> ets":[{"icon":"DESCRIPTION","message":"HTreeMap.replace destroys the
> map (#825)"}],"action":{"name":"View
> Issue","url":"https://github.com/jankotek/mapdb/issues/825"}}}

**Comment by xorqe** [comment]
There's never an Exception being thrown that I could catch, so I don't have a stacktrace, I'm afraid. That's the only line I get from the debugger, because it is unable to analyse the object after the replace.

An Item is not immutable per-se, it's a rather complex thing containing multiple inner maps and flags. The Serializer serializes the object to a JSON-String. I didn't implement equals on the Serializer, is that required?

When I use heapdb, at first glance I'd say it is a bit strange: The item I get back as "previous" from the map is in fact the same instance as the one I'm trying to write into it. With the filedb it was 2 different instances, and that's what I'd expect since I thought they were serialized to json in between?

**Comment by xorqe** [comment]
Alright, that was it, there was a case missing in the deserializer. All the unit tests work now again, therefore the upgrade was successful. 
Thanks for your help.
