### ISSUE TITLE
Slow loading of file around 2GB

### ISSUE THREAD

**Issue by aleSuglia** [jankotek/mapdb#830]
Hi,

I am using MapDB to create a `HTreeMap<String, double[]>` that I will use to efficiently retrieve a vector according to a specific key. In my scenario, I need to create the storage once and use it in read-only mode. I have created a MapDB storage using the API in this way:
```
       DB embeddingsDB = DBMaker.fileDB(dbFile).
                        fileMmapEnable().
                        fileMmapEnableIfSupported().
                        fileMmapPreclearDisable().
                        fileLockDisable().
                        make();
```
Unfortunately, when I try to load it it is really slow and causes my application startup a pain. This is the code that I'm using in order to create the *DB* instance: 
```
     DB embeddingsDB = DBMaker.fileDB(embeddingsDBFile).
                        readOnly().
                        fileMmapEnable().
                        fileMmapEnableIfSupported().
                        fileMmapPreclearDisable().
                        fileLockDisable().
                        make();
```
The file that I am loading is about 2GB. I've chosen to use MapDB in order to efficiently load and access the data structure however at the moment I am experiencing this really slow loading (about 10 minutes).

May you give me some suggestions in order to speed-up the loading phase?

Thank you in advance,
Alessandro

**Comment by jankotek** [comment]
there are allocation options, mapdb memory maps store in 1MB chunks,
and there is option to increase it
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jankotek/
> mapdb","title":"jankotek/mapdb","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jankotek/mapdb"}},"updates":{"snipp
> ets":[{"icon":"DESCRIPTION","message":"Slow loading of file around
> 2GB (#830)"}],"action":{"name":"View
> Issue","url":"https://github.com/jankotek/mapdb/issues/830"}}}

**Comment by aleSuglia** [comment]
I've tried using the tips that you've reported here: https://jankotek.gitbooks.io/mapdb/content/performance/. However, I obtain the following error: `Channel not open for writing - cannot extend file to required size`. Am I not allowed to change the allocation size when the storage is in read-only mode?
