### ISSUE TITLE
TreeSetMaker lacks createFrom and createFromSink methods

### ISSUE THREAD

**Issue by DomKM** [jankotek/mapdb#835]
Though `TreeSetMaker`'s `createFrom` and `createFromSink` are [documented](https://jankotek.gitbooks.io/mapdb/content/btreemap/import.html) and in the [codebase](https://github.com/jankotek/mapdb/blob/7e6e04b19543267e15da6fdd7fe8040bde1d87ed/src/main/java/org/mapdb/DB.kt#L1387-L1425), they appear to be missing from the Maven Central 3.0.4 release.

`TreeMapMaker` has these methods and they appear to work correctly.

**Comment by jankotek** [comment]
Fixed in master branch, will be in 4.0, not goint to fix in 3.0
