### ISSUE TITLE
HashSet is doing a linear search for contains!

### ISSUE THREAD

**Issue by mina-asham** [jankotek/mapdb#836]
The `HTreeMap.KeySet` class is not overriding the `contains` method and is instead depending on the `AbstractSet.contains` which calls `AbstractCollection.contains`, which utilizes the iterator doing a linear search, this is highly inefficient!

I had a look at `BTreeMap.KeySet` and it overrides the `contains` method properly delegating to inner `ConcurrentNavigableMap2`.

Is there something I am missing, or is that by design for some reason?

**Comment by jankotek** [comment]
it is a bug, will fix that, thanks

**Comment by thecoop** [comment]
This also means that HashSet.contains() doesn't use the serializer to compare equality, it uses java object equality

**Comment by jankotek** [comment]
This bug was already fixed in 3.0.5 release
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jankotek/
> mapdb","title":"jankotek/mapdb","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jankotek/mapdb"}},"updates":{"snipp
> ets":[{"icon":"PERSON","message":"@thecoop in #836: This also means
> that HashSet.contains() doesn't use the serializer to compare
> equality, it uses java object equality"}],"action":{"name":"View
> Issue","url":"https://github.com/jankotek/mapdb/issues/836#issuecomme
> nt-314470882"}}}
