### ISSUE TITLE
Guava version - dependency conflict 

### ISSUE THREAD

**Issue by irfany** [jankotek/mapdb#850]
Hi,

I am using Guava version 23.0 in my project, however when I add MapDB dependency in my POM my project is unable to run due to MapDB having an older version of Guava v19. I the only way I have got my project to work is by changing Maven to:

<dependency>
    <groupId>org.mapdb</groupId>
    <artifactId>mapdb</artifactId>
    <version>3.0.5</version>
    
        <exclusions>
    	<exclusion>
    		<artifactId>guava</artifactId>
    		<groupId>com.google.guava</groupId>
    	</exclusion>
    </exclusions>
    
</dependency>
  

Is it possible to upgrade the version of Guava you are using in your project?

Thanks

**Comment by jankotek** [comment]
I will change Mapdb deps to have no upper limits, this way it will work
in future. 
It will be in 3.0.x maintenance release for Java9 compatibility
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jankotek/
> mapdb","title":"jankotek/mapdb","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jankotek/mapdb"}},"updates":{"snipp
> ets":[{"icon":"DESCRIPTION","message":"Guava version - dependency
> conflict  (#850)"}],"action":{"name":"View Issue","url":"https://gith
> ub.com/jankotek/mapdb/issues/850"}}}

**Comment by bavardage** [comment]
also running into this - any timeline on the 3.0.x release?
