### ISSUE TITLE
How to backup mapdb files ? 

### ISSUE THREAD

**Issue by buptljy** [jankotek/mapdb#855]
I am using mapdb to contruct a high available service, which cannot be stopped because we need to provide a stable service to clients. To prevent from removing data accidently, I am going to backup mapdb files and move them to hdfs every midnight, but I cannot stop the service and close mapdb.
Is there any way to help me backup data without closing the mapdb ?

**Comment by hejian991** [comment]
I met the same problems ..
Could you tell me  if you find out any solutions ?

**Comment by andrm** [comment]
Currently you need the help of the OS for that: Make a lv snapshot (Linux)( or a shadow volume (? Windows) of the volume with the mapdb file on it and then copy them. You probably need Storage WAL for that, but even that is (I think) no guarantee. MapDB 4 will address this better, see issue #831
