### ISSUE TITLE
Improve serialization performance using Unsafe-based tricks

### ISSUE THREAD

**Issue by romix** [jankotek/mapdb#87]
It could be interesting to check if some java.misc.Unsafe based tricks can be used to improve serialization performance. In addition they can be used to serialize directly into off-heap memory without using an intermediate buffer on the heap.

I implemented this kind of optimizations for Kryo and it resulted in a significant performance boost (check e.g. the UnsafeInput and UnsafeOutput classes in the trunk). In particular, serialization of object graphs containing arrays of primitive types is sometimes an order of magnitude faster. I've seen speedups up to 10-30 times, depending on the size of an array. 

I also implemented UnsafeMemoryInput and UnsafeMemoryOutput classes, which allow to write directly into off-heap memory. Performance of these classes is the same as if you write into a byte array on the heap.

The implementation could be borrowed from Kryo with not so many changes needed I guess.

For some discussions about the implementation based on java.misc.Unsafe please have a look at the https://code.google.com/p/kryo/issues/detail?id=75&can=1

What do you think about it?

**Comment by jankotek** [comment]
I changed my mind. Unsafe brings about 15% performance improvement.

MapDB 2.0 master branch now has Unsafe build in. Use `DBMaker.newMemoryUnsafeDB().make()`
