### ISSUE TITLE
java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner; when closing DB on Mac with Java 9

### ISSUE THREAD

**Issue by drivenbyentropy** [jankotek/mapdb#879]
Let me begin by saying how much I value MapDB and the concept it represents. I forms an integral part of my own project. 

When running MapDB using Java 9 on MacOS 
```
$java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

closing any map fails with 

```
java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
	at org.mapdb.volume.ByteBufferVol.unmap(ByteBufferVol.java:340)
	at org.mapdb.volume.MappedFileVol.close(MappedFileVol.java:183)
	at org.mapdb.StoreDirect.close(StoreDirect.kt:877)
	at org.mapdb.DB.close(DB.kt:472)
	at org.mapdb.HTreeMap.close(HTreeMap.kt:1343)
```

Please let me know if you require additional information. 

Thanks!

**Comment by drivenbyentropy** [comment]
I found out that this is related to the .cleanerHackEnable() option. When removing this flag from the database builder, I am not getting the above exception.

**Comment by jasonwzs** [comment]
@jankotek, can this issue be fixed while keeping cleanerHackEnable() option?
