### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1048576 in org.mapDB version 3.0.5 with indexTreeList

### ISSUE THREAD

**Issue by cjoantony** [jankotek/mapdb#881]
Hello Everyone,

I am trying to store about 100 odd entries into mapdb.
I am using org.mapDB version 3.0.5
I get "java.lang.ArrayIndexOutOfBoundsException: 1048576" as described below:
Can you please guide us through this problem .

My code :
```
DB db = DBMaker.memoryDB().closeOnJvmShutdown().make();
 Serializer<Person> customserializer = new CustomSerializer();
List<Person> IPersonDTOmapDBList    = this.db.indexTreeList(mapDBListName, customserializer).createOrOpen();

```
I am able to succesfully add objects to the list., like using API addAll() of the java.io.List
However, when I am extracting the objects, one object at one time from the mapDB-List, i get below exception.

> java.lang.ArrayIndexOutOfBoundsException: 1048576
> 	at org.mapdb.DataInput2$ByteArray.unpackInt(DataInput2.java:162)
> 	at org.mapdb.DataInput2.readUTF(DataInput2.java:491)
> 	at com.company.mylistproj.personhandler.parser.CustomSerializer.deserialize(CustomSerializer.java:48)
> 	at com.company.mylistproj.personhandler.parser.CustomSerializer.deserialize(CustomSerializer.java:1)
> 	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
> 	at org.mapdb.StoreDirect.get(StoreDirect.kt:546)
> 	at org.mapdb.IndexTreeList.get(IndexTreeList.kt:114)
> 	at org.mapdb.IndexTreeList$iterator$1.next(IndexTreeList.kt:139)
> 	at com.company.mylistproj.import.PersonTransformer.transformPersonEntries(PersonTransformer.java:30)

	
At (PersonTransformer.java:30) my code is :
```
	    for (IPerson person : personEntriesList) {
		//my business logic
		
		}
```
		
CustomSerializer , I have given the required member-variables of <Person> as the values for serialize and deserialize method
<Person> class has also got the same member-variables as part of its overridden equals() method.

My applicaiton Enviroment:
Windows OS - Win 7
Applicaiton hosted on Apache Tomcat v8

Thanks,
Cjo

**Comment by zkmake520** [comment]
Met a same problem. 
Version:3.0.5
Anyone know how to solve it?

`java.lang.IndexOutOfBoundsException: Index: 4, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_92]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_92]
        at java.util.Collections$SynchronizedList.get(Collections.java:2417) ~[?:1.8.0_92]
        at org.mapdb.WriteAheadLog.walGetRecord(WriteAheadLog.java:863) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.StoreWAL.get(StoreWAL.kt:522) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.IndexTreeListJava.treeGetNonBinary(IndexTreeListJava.java:254) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.IndexTreeListJava.treeGet(IndexTreeListJava.java:189) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.IndexTreeLongLongMap.get(IndexTreeLongLongMap.kt:77) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.HTreeMap.removeprotected(HTreeMap.kt:479) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.HTreeMap.expireEvictEntry(HTreeMap.kt:914) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.HTreeMap$expireEvictSegment$1.take(HTreeMap.kt:881) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.QueueLong.takeUntil(QueueLong.kt:153) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.HTreeMap.expireEvictSegment(HTreeMap.kt:859) ~[mapdb-3.0.5.jar:?]
        at org.mapdb.HTreeMap.put(HTreeMap.kt:322) ~[mapdb-3.0.5.jar:?]`

**Comment by Dealus** [comment]
Hello,

same issue as OP here.

> 
> java.lang.IndexOutOfBoundsException
>         at java.nio.Buffer.checkIndex(Buffer.java:540)
>         at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
>         at org.mapdb.DataInput2$ByteBuffer.unpackLongArray(DataInput2.java:428)
>         at org.mapdb.IndexTreeListJava$1.deserialize(IndexTreeListJava.java:64)
>         at org.mapdb.IndexTreeListJava$1.deserialize(IndexTreeListJava.java:16)
>         at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
>         at org.mapdb.StoreWAL.get(StoreWAL.kt:527)
>         at org.mapdb.IndexTreeListJava.treeGetNonBinary(IndexTreeListJava.java:254)
>         at org.mapdb.IndexTreeListJava.treeGet(IndexTreeListJava.java:189)
>         at org.mapdb.IndexTreeLongLongMap.get(IndexTreeLongLongMap.kt:77)
>         at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:629)
>         at org.mapdb.HTreeMap.get(HTreeMap.kt:603)

Happens on a Centos/Tomcat8.5/Jdk7 environment.
Using MapDb conf:
		db = DBMaker.fileDB(dataFolder + "/file.db")
				.fileChannelEnable()
				.closeOnJvmShutdown()
				.readOnly()
				.fileLockDisable()
				.make();
		map = db.hashMap("data")
				.keySerializer(Serializer.STRING)
				.valueSerializer(Serializer.JAVA)
				.createOrOpen();

This happens systematically when shutting down the application via Tomcat Manager.
Shutting down the JVM doesn't lead to this issue.

The store seems to be corrupted at this point. At least one entry cannot be manipulated at all.

**Comment by cjoantony** [comment]
Guys, I found the root cause and fix also for the issue I reported above.

**Cause :** 
In the custom serializer, while serializing the list to the mapdb buffer [DataOutput2] i did not take care of NULL values. When NULL values are serialized  the buffer index does not increment. But, while retrieving values from buffer [de-serializing]  the buffer index progress for each data type regardless the presence of data.

eg:  
`int data = 5;`
`String value = null;`
`***** serializing ****`
`buf.writeInt(data); // buffer index shifts by int data type size`
`buf.writeUTF(value); // buffer index does not shift`

So, by the end of serialization, the buffer has got only size of int and String size is not considered as it is  NULL.
`*****de- serializing ****`
`int data = dataIn.readInt(); // gets the int [5] value;`
`String value = buf.readUTF(); // throws **IndexOutOfBoundsException** as the buffer was assigned with only int size.`

**Solution :**
While serializing, if the value to be serialized is NULL set the corresponding default value. [_Empty string instead of NULL_]
