### ISSUE TITLE
BTreeMap should have a PairIterator

### ISSUE THREAD

**Issue by allanwax** [jankotek/mapdb#886]
Every so often I need to copy a `BTreeMap` in one DB to another DB.  To do this I use a` .createFrom()` with an iterator.  `createFrom` is expecting a` Iterator<Pair<K, V>>` but java `TreeMap` `map.entries.iterator` produces an `Entry<K, V>` object.  To solve this issue I created a class that does nothing but create a `new Pair<K, V>` item for each Entry<K, V>.  This generates lots of new objects that get thrown away.

It would be nice is BTreeMap had a method to produce the iterator directly and save the intermediate waste of space.  Something like:
```
dbTmp.treeMap("map", Serializer.BYTE_ARRAY, Serializer.STRING) //
                    .createFrom(currentMap.pairIterator());
```

Or better yet modify createFrom to just accept a map and let it work out the details, hopefully doing it in the most efficient manner.
```
dbTmp.treeMap("map", Serializer.BYTE_ARRAY, Serializer.STRING) //
                    .createFrom(currentMap);
```

**Comment by jankotek** [comment]
I am not sure what is difference between `Entry` and `Pair`. It is just another object, or is there some performance overhead?

Anyway the iterators are wastefull on their own. Much more efficient is to use `.forEach`.

**Comment by allanwax** [comment]
The documentation describes that using (a) Pump is a fast way to load a map if the values are sorted.  It also mentions creating a map using .createFrom().  From a Java perspective (Entry), not Kotlin (Pair), I'm trying to do this as fast as possible and if I can avoid an Iterator, even better.  I'd also like it to be convenient, so having createFrom also accept a map and it internally does it the fastest way possible would be usefull to me.

If you could update the documentation with more Java examples, that might help
