### ISSUE TITLE
Mapdb performance issue

### ISSUE THREAD

**Issue by hina1234** [jankotek/mapdb#887]
Hi,

I am trying to use Mapdb in our project . I am facing performance issues inserting entries using fileMap.

Below is the code snippet - 
 DB db = DBMaker.fileDB("file2.db").transactionEnable().fileChannelEnable().allocateStartSize( 10 * 1024*1024*1024)  // 10GB
          .allocateIncrement(512*1024*1024).cleanerHackEnable().make();
      HTreeMap<Hit,HitPatch> hmap = db.hashMap("test").keySerializer(Serializer.JAVA)
          .valueSerializer(Serializer.JAVA)
          .create();

To insert one million entries it takes around 40 secs.
Is there any configuration to improve this?

**Comment by jankotek** [comment]
Use better serializer (Serializer.JAVA is slow and space inefficient). Commit in large batches.
