### ISSUE TITLE
Concurrent/Multi User

### ISSUE THREAD

**Issue by pitosalas** [jankotek/mapdb#889]
This is not a bug or an issue but I couldn't find the "right place" to ask this. 

From what I remember last I used mapdb for my Java course, this is a single user database. Only one process can open the file at the time.

Is that ever going to change or is it a fundamental part of the vision?

**Comment by jankotek** [comment]
No it is not going to change. MapDB is primarly embedded library. I might provide access over socket, but that has low priority.
