### ISSUE TITLE
No way to delete or rename named objects from the db

### ISSUE THREAD

**Issue by nddipiazza** [jankotek/mapdb#896]
Older version of MapDB (1.x) had a 

`db.remove`
and
`db.rename`

The latest 3.x version does not have any way to delete a table or rename the named objects.

How are we supposed to do that in the 3.x version?

**Comment by nddipiazza** [comment]
In order to work around, you need to create a "name map". The name map will alias the names of named objects.

So every time you want to get a named object from the db, you need to first get the "real" name, then get that instead.

Now deleting is simply a task of clearing out the real entry and delete the name from the name map.

And renaming is just renaming the name in the alias map.

**Comment by jankotek** [comment]
wontfix
