### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by jmclulus** [jankotek/mapdb#911]
So I'm storing a whole bunch of possibly big complex `Item` objects, and I've got a system for storing them in place, however I need an index of all the Items that are in the system.  So I've got a simple `ItemEntry` class with a few properties, simplified (minus the getters, setters, and constructors) is:

```
class ItemEntry {
    String address;
    String clazz;
    String path;
    long offset;
    Item item = null;
}
```

The idea being that for all the `ItemEntry`s that are cached in memory, there is an instantiated copy of the `Item`, but most importantly, when that's written to disk, the system knows where to find that Item (path, offset).  I'm not sure if that memory plan is viable with mapDB, otherwise I'll have to maintain a separate in-memory array of `Item`s with some kind of priority system for most recently used.

Either way, complex Object that shouldn't be saved to disk aside, I can't get this disk-based mapDB thing to work, it keeps giving me a serialization error, I think I don't have the Serializer properly attached to the map.  :/

```
public class ItemIndex {
	
	DB db;
	BTreeMap<String, ItemEntry> map;
	
	public ItemIndex() {
		
		// initialize a MapDB database
		db = DBMaker.fileDB("items.db")
		.closeOnJvmShutdown()
		.make();
		
		// create or load the Map
		map = db.<String, EntrySerializer>treeMap("items")
		        .keySerializer(Serializer.STRING)
		        .valueSerializer(Serializer.JAVA)
		        .counterEnable()
		        .createOrOpen();
	}
	
	public ItemEntry put(Item item) throws InvalidFileException, MissingItemException, InvalidAddressException {
		String addy = item.address().toString();
		ItemEntry entry = map.get(addy);
		
		//if there is no entry, we must be loading this Item for the first time
		if (entry == null) {
			entry = Library.instance().write(item);
		}
		
		map.put(addy, entry);		//todo: do I really have to put it again?
		db.commit();
		
		return entry;
	}
	
	public void put(ItemEntry entry) {
		map.put(entry.address(), entry);
		db.commit();
	}
	
	public ItemEntry get(String addy) throws InvalidAddressException {
		ItemEntry entry = map.get(addy);
		return entry;
	}
	

	public int size() {
		return map.size();
	}
	
	class EntrySerializer implements Serializer<ItemEntry>, Serializable{
        @Override
        public void serialize(DataOutput2 out, ItemEntry value) throws IOException {
        	out.writeUTF(value.address());
            out.writeUTF(value.clazz());
            out.writeUTF(value.path());
            out.writeLong(value.offset());
        }

        @Override
        public ItemEntry deserialize(DataInput2 in, int available) throws IOException {
        	return new ItemEntry(in.readUTF(), in.readUTF(), in.readUTF(), in.readLong());
        }
    }
}
```

Should I be running that whole big createOrOpen() thing every time I do a get or a put?  That seems wrong somehow, I need this (and a similar but simpler mapDB object in another class) to be constantly getting and putting throughout my application lifecycle.

Thanks!

**Comment by jmclulus** [comment]
This is the relevant parts of the 

```
Exception in thread "JavaFX Application Thread" org.mapdb.DBException$SerializationError
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:246)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:631)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:408)
	at org.mapdb.BTreeMap.put(BTreeMap.kt:292)
```

**Comment by jmclulus** [comment]
Additionally, I would really like to be able to get a list of all the ItemEntry objects that have a certain clazz value.  Am I asking too much of mapDB?

**Comment by andrm** [comment]
Use
` .valueSerializer(new EntrySerializer())`
instead of
  ` .valueSerializer(Serializer.JAVA)`

**Comment by jmclulus** [comment]
@andrm My compiler doesn't seem to like that.  It gives me this error:

`The method valueSerializer(GroupSerializer<A>) in the type DB.TreeMapMaker<String,capture#2-of ?> is not applicable for the arguments (ItemIndex.EntrySerializer)`

**Comment by andrm** [comment]
Make EntrySerializer static:
`static class EntrySerializer implements Serializer<ItemEntry>, Serializable{
`
 and try 
```
map = db.<String, ItemEntry>treeMap("items")
		        .keySerializer(Serializer.STRING)
		        .valueSerializer(new EntrySerializer())
		        .counterEnable()
		        .createOrOpen();
```

**Comment by andrm** [comment]
MapDB has such a feature with expiry. Or use a Guava cache.

Please close this issue.
