### ISSUE TITLE
Cannot find MapDB IntelliJ Maven

### ISSUE THREAD

**Issue by boris-barath** [jankotek/mapdb#921]
Hi, it seems that when I try to add MapDB to a project in intellij through Maven, it does not find MapDB. Do you know why this can be happening?

**Comment by allanwax** [comment]
I happen to use the following and IntelliJ seems to have no issues with it.

```
<!-- https://mvnrepository.com/artifact/org.mapdb/mapdb -->
        <dependency>
            <groupId>org.mapdb</groupId>
            <artifactId>mapdb</artifactId>
            <version>3.0.5</version>
        </dependency>
```
Do you have more details
