### ISSUE TITLE
DB.compact()

### ISSUE THREAD

**Issue by allanwax** [jankotek/mapdb#926]
In searching through documents about MapDB I come across references to DB.compact() to reduce the size of data on disc.  But I can't seem to find the function.  Has it been removed?  Is there a better way to do it now.

Note this is not about disc compression but removing dead spaces in the file store.  My issue is that MapDB does not automatically compact and that is specified in the documents and I have periodic adds and delete of a large number of records.  I'd like to compact the DB after a bulk add to save space.

**Comment by teenriot** [comment]
I found a compact methode at: 
BTreeMap<Integer, Integer> data;
data.getStore().compact();

But i did not test it.

**Comment by allanwax** [comment]
Thanks

**Comment by nddipiazza** [comment]
@allanwax  did this work for you?
