### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ashaychangwani** [jankotek/mapdb#929]
I'm very new to this, but I hope you might be able to help me with my issue. I'm trying to create a Map of data onto a file, since my RAM is very less. However, no matter what configuration I try, the data seems to be stored on the RAM itself.

this is how I'm defining the db instance:

        db = DBMaker.fileDB("F:/db0").make();

and my map:

map2=db.hashMap("maMap2", Serializer.LONG, Serializer.STRING).create();

I hope you might take the time out to help me out. Thanks.

**Comment by jankotek** [comment]
You need to use 'db.commit()'
