### ISSUE TITLE
Store without Index File 

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#93]
Right now MapDB uses following algorithm to get record: 

1) take recid which is offset in Index File 
2) read 8-byte-long from Index File to get offset and size in Physical File
3) read data from Physical File
4) deserialize and so on. 

Index File is needed when physical record location  can change (delete, update). However for read-only stores Index File is not necessary and introduces unnecessary seek operation (step 2). 

If Recid would be offset in Physical File, it is possible to eliminate Index File. Such store would only allow two operations: get and insert (append to end of file). This brings challenge with building tree structures, since they need to be constructed from bottom and not from top (no updates are allowed). 

But I believe we could provide  utility methods for BTreeMap in Data Pump to construct btree inside such store.

**Comment by cubefriendly** [comment]
I see now that I have only one file when I close my db file. Doesn't that mean that this task is done?

**Comment by jankotek** [comment]
@cubefriendly No. Current storage format still has index table, it is just merged.

**Comment by jankotek** [comment]
This will probably be in next beta in 2.0 branch

**Comment by cubefriendly** [comment]
great!!! Looking forward to try that !

**Comment by jankotek** [comment]
Initial implementation is in. So far it only supports single `BTreeMap` per file, but in future I will support multiple including HashMaps and sets.

An example:

```
        File f = TT.tempDbFile();
        NavigableMap source = new TreeMap();
        for(int i=0;i<10000;i++){
            source.put(i,""+i);
        }

        Pump.archiveTreeMap(
                source,
                f,
                new DB.BTreeMapMaker("name")
                    .keySerializer(Serializer.INTEGER)
                    .valueSerializer(Serializer.STRING)
        );

        DB db = DBMaker.archiveFileDB(f).make();
        Map m = db.treeMap("name");
```

**Comment by cubefriendly** [comment]
Great! Multiple would be better for sure but already it should be very useful that way!

Let me try that and I'll get back to you.

Should I expect performance improvements? You talked about fewer seek and read that should lead to better performance.

**Comment by jankotek** [comment]
No idea about performance at this point. 

I will add TreeSet and multiple map/sets soon. But HashMaps will take some time.

**Comment by cubefriendly** [comment]
I am not using hashmaps so it is ok for me :) 

I would argue that a task per data type makes sense. Then you don't need to wait for HashMap to be done to close the one for BTree. I am sure they are very different.

I will see what is the result space and performance wise of this.  Looking forward to it!

**Comment by jandam** [comment]
Missing config.pumpIgnoreDuplicates instead of false in Pump::archiveTreeMap at lines 913 and 958

**Comment by jankotek** [comment]
Closing, it will be added eventually agian in 3.x
