### ISSUE TITLE
No Progress Since 8 Months.. Everything Okay ?????

### ISSUE THREAD

**Issue by mangaldev** [jankotek/mapdb#933]
I havent seen any progress on this project since 8 months.  @jankotek  Everything is fine or not?

**Comment by cdluv** [comment]
I guess it's up to us now to maintain it??

**Comment by jankotek** [comment]
I had some personals troubles, I am back. MapDB 4 update will be today or tomorrow.

**Comment by mangaldev** [comment]
I am so glad that you are back. Take care man.

**Comment by jhult** [comment]
Any news since [this blog post](http://www.mapdb.org/blog/mapdb4-update/) on March 14, 2019?
