### ISSUE TITLE
how to store my own object as HTreeMap value?

### ISSUE THREAD

**Issue by hfcheng66** [jankotek/mapdb#993]
Sorry not sure where to ask question so trying post here, if this is not the right place, please let me know.

I looked at https://jankotek.gitbooks.io/mapdb/content/htreemap/. However I didn't find any example showing how to store my own object as value when using HTreeMap. Should I just skip the serializer definition so it will use the generic serialization? Could someone point me to any guide/example? 

Thanks!

**Comment by sreeshan90** [comment]
check this - https://github.com/sreeshan90/object-store/blob/ec68b3e47f7c7f57583b42fde0e6cbf8674f3e5f/src/main/java/com/theom/challenge/service/DBService.java#L24

**Comment by hfcheng66** [comment]
thank you!
